### PR TITLE
Updated SSO docs

### PR DESCRIPTION
**Pull request by jerae-duffin**
Updated SSO Docs

### CODE REVIEW

**Comment by usha-mandya** [comment]
Thanks @jerae-duffin. Could you also clarify the note about managing users through the IdP account and that owners don't have to manually add users through the Invite tab when SSO is enabled?

**Comment by jerae-duffin** [comment]
Thanks! @usha-mandya Updated the note with new message

**Comment by jerae-duffin** [comment]
Close PR. Merging changes to ENGDOCS-607

**Comment by usha-mandya** [comment]
Sure. Sounds good.

**Pull request closed without merging**
