### PR TITLE
Notes styles cleanup, and add background color to regular notes

### PR DESCRIPTION
**Pull request by thaJeztah**
Before

Screenshot 2020-10-19 at 22 10 33

After

Screenshot 2020-10-19 at 22 10 22

### CODE REVIEW

**Comment by thaJeztah** [comment]
@usha-mandya ptal

**Comment by usha-mandya** [comment]
Thank you @thaJeztah. The note format looks really good. 

Can we extend this further by adding a different coloured block to 'warning' and 'important' admonitions? Something on the lines of https://getbootstrap.com/docs/4.0/components/alerts/

**Comment by thaJeztah** [comment]
@usha-mandya yes, we can; I wanted to slightly cleanup the styling before adding new ones, but can do a follow up with some options so that we can discuss the styling, icon, etc.

**Review by usha-mandya — APPROVED** [review]

**Comment by usha-mandya** [comment]
Yes, we can discuss the options later. This PR looks good.

**Pull request merged**
