### PR TITLE
Fix link

### PR DESCRIPTION
**Pull request by aevesdocker**

### CODE REVIEW

**Review by dvdksn — APPROVED** [review]

**Comment by crazy-max** [comment]
I will take a look to have degraded mode for GitHub users but LGTM in the meantime.

**Review by crazy-max — APPROVED** [review]

**Comment by crazy-max** [comment]
Also a bit out of scope with this PR but in dark mode, icons don't look great: https://docs.docker.com/contribute/overview/

image

We should have light and dark mode icons I think.

**Comment by aevesdocker** [comment]
@crazy-max yes, aware the icons need changing. Am working with one of the designers to get this sorted asap

**Comment by crazy-max** [comment]
Awesome thx @aevesdocker

**Pull request merged**
