### PR TITLE
Fix package link and correctly curl GPG keys into APT (Debian Linux)

### PR DESCRIPTION
**Pull request by Sieabah**
### Proposed changes

_sudo apt-key add_ needed the dash after to properly pipe the key into apt

https://apt.dockerproject.org/repo/pool/ is the wrong directory it needs to be pointing to
https://apt.dockerproject.org/repo/ as the dists folder is not found in pool/.

This is the error that happens when the url is _https://apt.dockerproject.org/repo/pool/_
`
Get:8 https://apt.dockerproject.org jessie/main amd64 Packages [454 B]
Err https://apt.dockerproject.org jessie/main amd64 Packages
  HttpError403
Hit http://httpredir.debian.org jessie/contrib amd64 Packages
W: Failed to fetch https://apt.dockerproject.org/repo/pool/dists/jessie/main/binary-amd64/Packages  HttpError403
`

### CODE REVIEW

**Comment by Sieabah** [comment]
Weird how the build failed...

**Comment by johndmulhausen** [comment]
Looks like we need to force-update this fork, @mstanleyjones -- the crazy is still going on in this one.

**Comment by mstanleyjones** [comment]
Thanks for the report. This was fixed already by #1271 and the instructions should now be correct.

**Comment by Sieabah** [comment]
Still doesn't fix the apt GPG key, unless that was in another issue @mstanleyjones

**Comment by mstanleyjones** [comment]
Yes, I rebased your commits on master and they were both empty. I can't push into your master to prove it because this PR is closed. Again, thanks for the report though!

**Pull request closed without merging**
