### PR TITLE
Move "docker-for-windows" and "docker-for-mac" inside the "desktop" directory

### PR DESCRIPTION
**Pull request by thaJeztah**
This brings all desktop-related content into a single directory;

- /docker-for-windows/ -> /desktop/windows/
- /docker-for-mac/ -> /desktop/mac/

This makes the URLs more consistent/predictable, and easier to navigate.

### CODE REVIEW

**Comment by thaJeztah** [comment]
This will likely conflict with https://github.com/docker/docker.github.io/pull/13352 and https://github.com/docker/docker.github.io/pull/13351, but I can rebase after those are merged


@usha-mandya @StefanScherer ptal (probably best to keep this one for after the weekend in case fix-ups are needed)

**Comment by StefanScherer** [comment]
Overall a good idea. But I remember we had problems with redirects with anchors.
When we do this we should also adjust links from DD to the docs accordingly as we did eg. in https://github.com/docker/pinata/pull/16021

Currently I can find these links with anchors that are used in DD:
- https://docs.docker.com/docker-for-mac/#file-sharing
- https://docs.docker.com/docker-for-mac/troubleshoot/#incompatible-cpu-detected
- https://docs.docker.com/docker-for-windows/#file-sharing
- https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization
- https://docs.docker.com/docker-for-windows/wsl/#develop-with-docker-and-wsl-2

**Comment by thaJeztah** [comment]
Yes, I already opened a PR to update the links; https://github.com/docker/pinata/pull/16249, but ideally we should change all links in DD itself to use `https://docs.docker.com/go/...` "permalinks" / redirects (https://github.com/docker/docker.github.io/pull/11460), that way we can update them to different locations (and anchors) in the documentation without changing the links in Desktop.

**Comment by StefanScherer** [comment]
Thanks that you already thought about the changes in pinata, the PR looks good! 
Regarding the `/go/` permalinks/redirects, this wouldn't resolve the missing anchors, right?

For this PR I think it's the best what we can do for older DD versions (anchors not working), but with 4.0.0 we have it corrected again. So I'm fine with merging this PR anytime before 4.0.0.

**Review by StefanScherer — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
> Regarding the /go/ permalinks/redirects, this wouldn't resolve the missing anchors, right?

The `redirect_to` actually works with anchors (e.g. `/go/foobar/` can redirect to `/some/page/#some-anchor`), which is nice

**Comment by usha-mandya** [comment]
Thank you @thaJeztah. LGTM

**Review by usha-mandya — APPROVED** [review]

**Comment by usha-mandya** [comment]
@thaJeztah Are we good to merge this, or should we wait until the Pinata PR is ready to go live?

**Comment by thaJeztah** [comment]
> @thaJeztah Are we good to merge this, or should we wait until the Pinata PR is ready to go live?

Yup! Checked internally, and all links from Docker Desktop open in a browser, so should redirect as usual

**Pull request merged**
