### PR TITLE
Add bash information about return codes.

### PR DESCRIPTION
**Pull request by lucile-sticky**

### CODE REVIEW

**Comment by joaofnfernandes** [comment]
@shin- while this PR might be true today, do we have any assurances that the return codes won't change at any time?

**Comment by shin-** [comment]
Hm, I don't think those numbers are subject to change at this point, but the PR isn't entirely accurate.

Exit code 2 will only be returned when shutdown is forced (Ctrl-C twice). If containers are allowed to stop normally (Ctrl-C once), exit code will be 0.

**Comment by joaofnfernandes** [comment]
@lucile-sticky do you care to update your changes based on @shin- 's feedback

**Comment by lucile-sticky** [comment]
@joaofnfernandes @mstanleyjones section about shell return values edited following @shin- comment!

**Comment by joaofnfernandes** [comment]
@lucile-sticky looks like it's time to ship it 🚀

**Pull request merged**
