### PR TITLE
Fixing and improving build-images.md, run-containers.md and develop.md for Python guide

### PR DESCRIPTION
**Pull request by manelbdcosta**
### Proposed changes
- Virtual environment should be created and activated so `pip3 freeze` reflects just the project's dependencies
- App should be binded to `0.0.0.0` so container is accessible from outside (as necessary in the next step of the guide)
- Testing flask via the command `python3 app.py` for coherence with Dockerfile CMD
- Fixing run-containers.md as it was showing command examples from the Node.js guide
- Fixing ports used in run-containers.md as flask server is by default exposed on `5000`, not `8000`
- Minor text and style improvements

### CODE REVIEW

**Comment by usha-mandya** [comment]
@manelbdcosta Thanks for the PR. 

@StefanScherer Could you PTAL?

**Comment by StefanScherer** [comment]
Hey @manelbdcosta,
Thank you for your contribution and suggested fixes.  We have another PR #12217 with similar fixes and we decided to prefer the other PR. What do you think?  Is there  anything missing?  Maybe we should merge the other and then see what we can still improve according your suggestions.

**Comment by manelbdcosta** [comment]
Hey @StefanScherer, 
Sure. I went over the other PR and noticed:
- it has a better approach to flask initiation than mine :) 
- it addresses mistakes on the output of `docker ps` that mine doesn't
However:
- It doesn't address a lot of the text issues addressed in this one
- curls are less explicit
- requirements.txt will be full of user python packages (no venv) - very prone to confusion
- No clear differentiation between command input and output
--
I believe it would make more sense to edit this one or merge and make another PR to improve: flask initiation, fix `docker ps` output. Up to you guys, happy either way! 

Thanks for the review!

**Comment by usha-mandya** [comment]
@manelbdcosta The other PR has been merged. Could you rebase your PR and add then add any improvements? Thanks.

**Pull request closed without merging**
