### PR TITLE
explained how to pin whale to taskbar

### PR DESCRIPTION
**Pull request by londoncalling**
### Proposed changes

Docker for Windows whale icon with all settings dialogs is hidden by default under Notifications. Explained this better, and included tip on how to pin it to the taskbar.

### Please take a look

@friism

### CODE REVIEW

**Comment by londoncalling** [comment]
@johndmulhausen not sure why Netlify is failing here. I slacked you about it but also looked again at the files changed, and I don't think anything I did here could have caused a problem with the builds.

**Comment by mstanleyjones** [comment]
I don't have access to view the logs for some reason...

**Comment by londoncalling** [comment]
Me neither? :-( It's got to be @johndmulhausen I guess to have a look?

**Comment by londoncalling** [comment]
LGTM

**Pull request merged**
