### PR TITLE
Added arm specific docker pull -- DO NOT MERGE

### LINKED ISSUE #2709: Document multi-architecture support and how to tag images to make it work
Docker Engine will pull the image that's appropriate for the host that's pulling the image, based on tags. We should have a topic showing how to tag images so this happens transparently.

cf. [Microsoft Azure Container Registry Manages Docker Images](http://www.eweek.com/cloud/microsoft-azure-container-registry-manages-docker-images)

### PR DESCRIPTION
**Pull request by surajnarwade**
### Proposed changes

Added `docker pull` info for ARM

### Related issues (optional)

Partially resolves #2709

### CODE REVIEW

**Comment by mstanleyjones** [comment]
This is correct from a `pull` point of view, but the `push` and repo support is not yet merged in `docker/docker`. I think we should award the points but not yet merge this. cc/ @johndmulhausen

**Comment by surajnarwade** [comment]
@mstanleyjones , agreed, what should I add more, maybe in installation part regarding arm ,
shall i proceed?

**Comment by mstanleyjones** [comment]
This is pending merging of https://github.com/docker/docker/pull/27455 and we can't really merge it until that is merged. It's still under design discussion.

**Comment by joaofnfernandes** [comment]
@mstanleyjones isn't the data on `_data/engine-cli-edge/*` being generated from `moby/moby`? If that's the case this PR should be made against that repo, otherwise these changes will be lost down the road.

**Comment by johndmulhausen** [comment]
@surajnarwade We gave you some points for this, but this PR needs to be done upstream. Thanks a lot for your contribution. :)

**Pull request closed without merging**
