### PR TITLE
correct missing bullet points

### PR DESCRIPTION
**Pull request by carehart**
Signed-off-by: Charles Arehart <charlie@carehart.org>

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

@usha-mandya

**Comment by carehart** [comment]
Glad I could help. Can anyone let me know what the process (or typical delay is) to get such a change propagated to the real site? I am still seeing the content without bullets, at https://docs.docker.com/engine/context/ecs-integration/. Sorry if I'm showing some naivete here. I will learn from whatever you may tell me. :-)

**Comment by thaJeztah** [comment]
Changes get published when they are merged to the publish branch; looks for "publish updates from master" pull requests; https://github.com/docker/docker.github.io/pulls?q=is%3Apr+publish+in%3Atitle+is%3Aclosed

This is a manual step, so likely this will go out after the weekend

**Comment by carehart** [comment]
Ah, OK. Thanks. :-)

**Comment by usha-mandya** [comment]
@carehart This is now live on docs.docker.com

**Comment by carehart** [comment]
Yep, I'd seen.  Thanks, @usha-mandya. I had been torn about writing a note of acknowledgment, not wanting to add any burden, but now I will just to thank you for that. :-) 

And again, as important now I understand that when changes are made, they can take some time to finally show up in the actual docs--and that I (or others in such a case) can trust that they will. :-) Thanks to everyone for your efforts on all this (and I do mean "all of this" great project).

**Comment by usha-mandya** [comment]
@carehart Thank you SO much for your kind words :)

**Pull request merged**
