### PR TITLE
Add breadcrumbs

### PR DESCRIPTION
**Pull request by thaJeztah**
Some works still to be done:

- [x] when scrolling, the left- and right-hand navigation scroll behind the breadcrumbs
- [x] styling may need some tweaking
- [x] mobile needs to be checked (make sure it's hidden)
- [x] if we don't have breadcrumbs for a page, positioning of other elements should
  be adjusted

Screenshot 2021-04-30 at 20 08 33

Screenshot 2021-04-30 at 20 08 51

And the problem when scrolling (need to look how we addressed this);

Screenshot 2021-04-30 at 20 08 40
Screenshot 2021-04-30 at 20 08 46

### CODE REVIEW

**Comment by thaJeztah** [comment]
oh! interesting; CI is failing? let me check

**Comment by thaJeztah** [comment]
Fixed; LOL, forgot to stage a "somewhat" important file for this 😂 

```
Liquid Exception: Could not locate the included file 'breadcrumbs.html' in any of ["/usr/src/app/md_source/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in /_layouts/docs.html
```

**Comment by thaJeztah** [comment]
@usha-mandya PTAL - I fixed the "scroll" issue, and some other touch-ups, and moved this out of draft.

**Comment by usha-mandya** [comment]
Thank you @thaJeztah. Would it be possible to add a Home icon for users who'd like to visit the landing page?

image

**Comment by usha-mandya** [comment]
Just left a comment about adding a Home button. Looks good otherwise for phase-1. 

@StefanScherer Do you mind taking another look?

For phase-2, we can implement the focussed ToC where the ToC displays only the contextual section and hides the rest of the left navigation. For example, if a user selects a topic in Docker Desktop, the ToC would only display the Docker Desktop section and hides the rest of the left navigation. Users can click on the breadcrumbs to navigate to the other sections

**Comment by thaJeztah** [comment]
Added a "home" link to the breadcrumbs:

Screenshot 2021-05-10 at 17 06 07
Screenshot 2021-05-10 at 17 06 14

**Review by usha-mandya — APPROVED** [review]
LGTM

**Pull request merged**
