### PR TITLE
Spelling mistakes

### LINKED ISSUE #2969: Lots of spelling mistakes
### Problem description
Found a bunch of spelling mistakes across 40 documents

### Suggestions for a fix
Will upload fix

### PR DESCRIPTION
**Pull request by stevenhanna6**
Spelling mistakes

### Related issues (optional)
Fixes #2969

### CODE REVIEW

**Comment by johndmulhausen** [comment]
Fix your merge conflicts, and we'll get this in. Great work, @stevenhanna6 :)

**Comment by stevenhanna6** [comment]
I didn't do this right, I think it messed it up trying to get my master branch up to date with the main one. I'm still learning how to use git. I'll try to figure out what I did wrong

**Comment by stevenhanna6** [comment]
I'm lost if I did this right or not, should I close this pull request and redo everything from the new updated master bran. I think the conflicts came because I wasn't keeping the master I was working on up to date, but when I updated it I didn't know how to pull those changes in the the spellfix branch I was using. So I merged the spellfix branch into the new updated master then did another push. Where did I screw up?

**Comment by johndmulhausen** [comment]
@stevenhanna6 Popped in there and fixed the extra page thing. :) This is fantastic, thanks so much.

**Pull request merged**
