### PR TITLE
Engine reference BUILD tarball contexts mangled

### PR DESCRIPTION
**Pull request by dsheets**
Closed code fence, removed duplicate text. Perhaps caused by bad merge?

### CODE REVIEW

**Comment by johndmulhausen** [comment]
Thanks, @dsheets !

**Comment by mstanleyjones** [comment]
This needs to be reverted as we don't maintain these files in this repo.

**Comment by dsheets** [comment]
Where do the files live?

**Comment by mstanleyjones** [comment]
The source files are in the `docker/docker` repository under `docs/reference/commandline/build.md`.

**Pull request merged**
