### PR TITLE
Info about IP 50 needing to be open

### PR DESCRIPTION
**Pull request by afrazkhan**
### Describe the proposed changes

Added information about needing IP 50 open for overlay networks with the `--opt encrypted` flag to the docs.

### Project version

1.12 and up (anything with Docker Swarm mode).

### Please take a look

@thaJeztah

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Nice @afrazkhan !!  Thanks

Looks like there's a typo with `encrypted`: 

> `encyrpted`

**Comment by afrazkhan** [comment]
@nathanleclaire Oops, thanks fixed.

**Comment by johndmulhausen** [comment]
@nathanleclaire Does this look good to you now?

**Comment by nathanleclaire** [comment]
LGTM -- makes sense to have in its own little blurb, I'd say, since it's a protocol not a port

**Pull request merged**
