### PR TITLE
CI - don't allow absolute links to docs.docker.com

### PR DESCRIPTION
**Pull request by aduermael**
### Describe the proposed changes

Added a test to prevent absolute links to `docs.docker.com`. 
Also made a few absolute links relative for this test to pass.

### CODE REVIEW

**Comment by johndmulhausen** [comment]
Deploy preview ready!

Built with commit e68bbc60163c97964b249bfbb4318cbb39d68fc6

https://deploy-preview-823--docker-docs.netlify.com

**Comment by aduermael** [comment]
@johndmulhausen I'll now add more tests in the same scope to check for dead links or infinite redirection loops... But this one can be merged already.

**Comment by sanscontext** [comment]
Will we have the ability to disable this for specific layout features? I'm specifically thinking of links in banners which might be applied at build time, and which since they could be applied anywhere, would need a static url.

**Comment by aduermael** [comment]
@sanscontext sure, it's super flexible. so far it only checks published markdown files. we can add exceptions if needed.

**Comment by sanscontext** [comment]
SGTM! Thanks.

**Comment by aduermael** [comment]
@johndmulhausen can you merge it please? I'll submit new tests today, but I would prefer that one to be merged first. Thanks!

**Comment by aduermael** [comment]
I rebased and had to fix a new absolute link in `engine/installation/binaries.md`...

**Comment by johndmulhausen** [comment]
@aduermael I agree with the goal of this test, however it appears you're parsing links with RegEx here. I don't want to set a precedent of relying on clever/arcane RegEx Markdown processing instead of freely available Go libraries such as Blackfriday.

With Blackfriday you can use Bluemonday to sanitize input:

```
import (
    "github.com/microcosm-cc/bluemonday"
    "github.com/russross/blackfriday"
)

// ...
unsafe := blackfriday.MarkdownCommon(input)
html := bluemonday.UGCPolicy().SanitizeBytes(unsafe)
```

Then, if that completes (obviously the CI check should fail if it doesn't), run `html` through [the html Go library](https://godoc.org/golang.org/x/net/html) and do the link checking there with a data structure that represents the document object model. 

Parsing raw Markdown with RegEx is a recipe for unintended consequences.

**Comment by aduermael** [comment]
@johndmulhausen It's way easier to parse markdown than html... I know `blackfriday` and we may have to use it for other tests, but I don't understand why in this case I would transform our markdown into html before parsing it. Sorry I just don't get it.

> Parsing raw Markdown with RegEx is a recipe for unintended consequences.

Please give me a concrete example.

**Comment by johndmulhausen** [comment]
I understand it's easier to implement it this way, but I'm afraid it is also a low-quality approach that is fragile. Just to cite one concrete example: What if we want to document how our Markdown works for contributors? We've talked about such a project.

The probem is, your code has no concept of what a link is, it just hopes that matching `[]()` will always do what you want. When you started validating YAML with CI tests you knew it was important to include a YAML parser so that you would have strongly-typed data and ready-made functions that had a notion of a YAML structure. Now you want to venture into processing page content but with no concept of a document? I don't think we should go there.

**Pull request closed without merging**
