### PR TITLE
Added Aruba Cloud to available drivers

### PR DESCRIPTION
**Pull request by nicolaeusebi**
### Proposed changes

Added link to drivers for service [Aruba Cloud](https://www.arubacloud.com/)

### CODE REVIEW

**Comment by nicolaeusebi** [comment]
Hi @johndmulhausen ,
thank you for your answer. I have made the changes you requested.

**Comment by nathanleclaire** [comment]
Hi @nicolaeusebi, thanks for the contribution. As Machine maintainer I'd suggest that we don't add this to the official documentation as it's for a 3rd party (non-core) driver. Instead, I'd suggest hosting the in-depth docs you have here at the plugin's repository and linking to it from https://github.com/docker/docker.github.io/blob/master/machine/AVAILABLE_DRIVER_PLUGINS.md, which is a comprehensive list of Machine plugins that are available.

**Comment by nicolaeusebi** [comment]
Hi @nathanleclaire , i have removed Aruba references from official documentation as you suggested.
Documentation in this file:
https://github.com/docker/docker.github.io/blob/master/machine/AVAILABLE_DRIVER_PLUGINS.md,
was already updated with Aruba Cloud references.

**Comment by nathanleclaire** [comment]
👍

**Comment by nathanleclaire** [comment]
LGTM

**Pull request merged**
