### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by QwertyZW**
Fixed a link pointing to the same page and 2 other links that are returning 404s

### CODE REVIEW

**Comment by sanscontext** [comment]
Hey @QwertyZW thanks for the head's up. That first link is actually linking to a subsection of the doc, and is correct as it was. (It should jump down the page.) Those other two are broken, you're correct, but were not intended to be links to the documentation - rather directly into the Hub UI. They should both go to `https://hub.docker.com/add/automated-build/bitbucket/`

**Comment by sanscontext** [comment]
Hi @QwertyZW, do you want to edit your patch and re-push? :) Or do you want to close it and I'll make the correction in the next batch of Hub updates?

**Comment by johndmulhausen** [comment]
@sanscontext You can actually edit his patch directly if you click the pencil in the "files" tab in this PR. :)

**Comment by sanscontext** [comment]
Fixed the links. Merging.

**Pull request merged**
