### PR TITLE
Update understanding-docker.md

### PR DESCRIPTION
**Pull request by galeneca**

### CODE REVIEW

**Comment by johndmulhausen** [comment]
Deploy preview processing.

Built with commit b6446a8a0aeda331623a2fe14c6eb6ecd65157b5

https://app.netlify.com/sites/docker-docs/deploys/581ea89971e20a5508befbe1

**Comment by johndmulhausen** [comment]
Hey @galeneca, sorry about the deploy preview message. It's because your fork doesn't have `.ruby-version` and `Gemfile` - might wanna update it at some point. :) These were just added recently to enable our CI checks.

**Comment by mstanleyjones** [comment]
@galeneca please rebase your commit against current `master` so that you get the files you need for the Netlify check to succeed. I could do it for you but I would need to force-push into your branch. Let me know if you need me to do that. Thanks!

**Comment by johndmulhausen** [comment]
This has merge conflicts, isn't that material of a change, and the author is awol. Closing. :(

**Pull request closed without merging**
