### PR TITLE
Release notes for 2.0.4.0 mac (Edge)

### PR DESCRIPTION
**Pull request by gtardif**

### CODE REVIEW

**Comment by ulrich** [comment]
@usha-mandya sorry for forgetting

**Comment by usha-mandya** [comment]
@ulrich - No worries

I've already merged the following PRs created by @mat007 

https://github.com/docker/docker.github.io/pull/8752
https://github.com/docker/docker.github.io/pull/8753

Content has been published to the docs website. We should be able to see the updates in a few minutes.

CC @gtardif

**Comment by ulrich** [comment]
@usha-mandya I did not see the PRs sorry. I can't close the PR created with the account of Guillaume.

**Comment by usha-mandya** [comment]
@ulrich I think I can close the PR. Let me add a comment and close it to avoid any confusion.

**Comment by usha-mandya** [comment]
Edge release notes for Mac and Windows have been updated as part of 

#8752
#8753

Closing this PR as 'duplicate'.

**Pull request closed without merging**
