### PR TITLE
Add note on subscription changes to DD overview, clean up a couple of…

### PR DESCRIPTION
**Pull request by usha-mandya**
… other topics related to subscription updates

Added a note on the update to DD terms of use on the DD overview page
Clean up a couple of topics related to subscription updates

### CODE REVIEW

**Review by jerae-duffin — DISMISSED** [review]
LGTM!

**Comment by stephanierifai** [comment]
LGTM thank you!!

**Review by stephanierifai — APPROVED** [review]
LGTM!

**Review by jerae-duffin — APPROVED** [review]
LGTM

**Pull request merged**
