### PR TITLE
Add missing stubs for docker builder subcommands

### PR DESCRIPTION
**Pull request by thaJeztah**
Similar to https://github.com/docker/docker.github.io/pull/8078, but for the `docker builder prune` command

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @L-Hudson @tiborvass PTAL

**Comment by L-Hudson** [comment]
LGTM. I'm assuming you want to wait to merge until @tiborvass weighs in?

**Comment by thaJeztah** [comment]
nah, this should be ready to go 🤗

**Comment by ulidtko** [comment]
Hey, can `docker builder prune` also be mentioned on this page https://docs.docker.com/config/pruning/ ?

Sorry if this is not the right place to ask.

**Pull request merged**
