### PR TITLE
TASK: Add codeblocks to code examples

### PR DESCRIPTION
**Pull request by thaJeztah**
carry of https://github.com/docker/docker.github.io/pull/12131; rebased and review comments addressed

### CODE REVIEW

**Comment by crydotsnake** [comment]
I updated also my fork repo :).

**Comment by thaJeztah** [comment]
@usha-mandya PTAL

**Review by usha-mandya — APPROVED** [review]
LGTM

**Comment by crydotsnake** [comment]
Glad it could be merged! :)

**Comment by thaJeztah** [comment]
Thanks for starting the work, @crydotsnake 👍

**Comment by crydotsnake** [comment]
Np! :). I already found the next thing i could do for the Docker docs site :))

**Comment by usha-mandya** [comment]
Thank you @crydotsnake!

**Comment by crydotsnake** [comment]
No Problem 😊

**Pull request merged**
