### PR TITLE
build: add docker driver guide

### PR DESCRIPTION
**Pull request by crazy-max**
follow-up https://github.com/docker/buildx/pull/1241

Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>

### CODE REVIEW

**Review by dockertopia — COMMENTED** [review]
@crazy-max So docker driver content is coming from upstream while the other drivers are going to be in the drivers folder in the docs repo?

**Comment by crazy-max** [comment]
> So docker driver content is coming from upstream while the other drivers are going to be in the drivers folder in the docs repo?

All drivers are from upstream: https://github.com/docker/buildx/tree/master/docs/guides/drivers

drivers folder in docs repo only contains stub files.

**Comment by dockertopia** [comment]
> > So docker driver content is coming from upstream while the other drivers are going to be in the drivers folder in the docs repo?
> 
> All drivers are from upstream: https://github.com/docker/buildx/tree/master/docs/guides/drivers
> 
> drivers folder in docs repo only contains stub files.

I thought the idea was to consolidate build content in this doc set. Any reason we can't have this directly in the docs repo?

**Comment by jedevc** [comment]
Keeping these kind of docs upstream in the buildx repo means that they live right next to the code that we work on, so we can make an effort to keep these up-to-date as we develop new features/work on bug fixes. Having them separated across repos means co-coordinating PRs, and will make it more likely to have out-of-date information.

I think it makes sense to have the high level information and such in the docker docs repo here, but then keep the buildx-specific/buildkit-specific content directly in their corresponding repositories, where users are already used to viewing that content.

**Review by dockertopia — APPROVED** [review]
From the perspective of the main docs base, it seems awkward to have so many exceptions regarding repo provenance for pages. It seems to be an easy answer for API documentation, but not as much for other topics such as this one. I'm new to these nuances, so although I appreciate your answer, I'm not entirely sure this is the way to go for build docs or any similar case. 
Since this PR won't change that (that was establishing by the previous PR for drivers) and just updates that info, I have no additional feedback for the specific scope of these changes. 
cc: @usha-mandya

**Pull request merged**
