### PR TITLE
Fix archive butterbar v17.03

### LINKED ISSUE #4837: Archive bar obscured on 17.03, 17.06
https://docs.docker.com/v17.06/engine/docker-overview/

You can see it peeking out from under the top nav. It might be gnarly to fix this because the top nav bar is set to `position:fixed`; you might have to resort to frames or something.

### PR DESCRIPTION
**Pull request by mstanleyjones**
Fixes #4837 for 17.03

### CODE REVIEW

**Comment by mstanleyjones** [comment]
@johndmulhausen I am not sure why the Jenkins job failed. @seemethere any ideas?

**Comment by seemethere** [comment]
@mstanleyjones Appears like it has to do with this line:

https://github.com/mstanleyjones/docker.github.io/blob/c849a0eff43d17fed6fdc5889c8a8579580a6676/Jenkinsfile#L18

There doesn't appear to be a `Dockerfile` in `tests/` directory

**Comment by seemethere** [comment]
Hmm that's so strange, the base branch doesn't include the `tests/Dockerfile` either. Did this run before?

**Comment by mstanleyjones** [comment]
Looks like something got screwed up in archiving. I am working on finding the root cause now.

**Comment by mstanleyjones** [comment]
Jenkins failed due to upstream changes we are waiting for in `docker/distribution`... Merging.

**Pull request merged**
