### PR TITLE
TCP is not valid option for GELF log driver

### PR DESCRIPTION
**Pull request by adamancini**
### Proposed changes

Remove references to TCP as a valid URI, and remove TCP-specific options

### Related issues (optional)
Solves #6611

### CODE REVIEW

**Comment by joaofnfernandes** [comment]
Thanks for putting in time to address this! Let's ship it 🚀

**Comment by joaofnfernandes** [comment]
Oh.. and you almost got it right, but next time use one of the [keywords supported](https://help.github.com/articles/closing-issues-using-keywords/) by Github to close issues

**Comment by thaJeztah** [comment]
Sorry, but this change is not correct; TCP is supported by the Gelf driver (but is not available in 17.06; were you testing on a 17.06 engine?) see https://github.com/docker/docker.github.io/pull/4536 and https://github.com/moby/moby/pull/34758

**Comment by adamancini** [comment]
Yeah this was on a 17.06 engine

**Pull request merged**
