### PR TITLE
Update envvars.md

### PR DESCRIPTION
**Pull request by NickvdMeij**
### Proposed changes

Update envvars.md to reflect the supported values of COMPOSE_CONVERT_WINDOWS_PATHS

### Related issues

Addition documentation for people using windows. See [link](https://github.com/docker/docker/issues/29753)

### CODE REVIEW

**Comment by shin-** [comment]
Actually as far as the current release is concerned, the only recognized values are whether the variable is set or unset. I intend to fix this in 1.10 but until then this should not be merged.

**Comment by johndmulhausen** [comment]
@shin- Could this be merged if it were opened against vnext-compose?

**Comment by shin-** [comment]
@johndmulhausen Yes, it would be fine (although we will also support `true` and `false` notably)

**Comment by NickvdMeij** [comment]
@shin- i would say `true` and `false` OR `1` and `0` should be supported. That way its always clear what the value is (if its set). I can imagine a situation where you might want to toggle this off for some projects, and toggle it back on for other projects. Doing this now would mean you need to remove the whole environment variable and create it again when you need it, instead of just changing the value

**Comment by mstanleyjones** [comment]
Please rebase your work on `vnext-compose` and resubmit.

**Comment by shin-** [comment]
@NickvdMeij 'false' (i-case), '0', unset and empty values will all be recognized as falsy, with anything else being recognized as true.

**Comment by johndmulhausen** [comment]
Edited to make more accurate according to @shin- 's comment. Now that `vnext-compose` is merged, I'm merging. Thanks, @NickvdMeij for the PR and @thaJeztah and @mstanleyjones for the reviews :)

**Pull request merged**
