### PR TITLE
DESKTOP-1122 Docker Desktop for Win 2.0.4.1 (Edge)

### PR DESCRIPTION
**Pull request by ulrich**
Signed-off-by: Ulrich VACHON <ulrich.vachon@docker.com>

### CODE REVIEW

**Comment by ulrich** [comment]
@usha-mandya we did this PR manually for the new Edge release.

**Comment by usha-mandya** [comment]
Thanks @ulrich. I'll take a look at the PRs today.

**Comment by usha-mandya** [comment]
@ulrich the Windows Edge release notes also link to the Mac issue on GitHub - https://github.com/docker/for-mac/issues/3646

Is this correct? Is there a specific issue created for Windows that we can reference from Release Notes?

**Comment by ulrich** [comment]
> @ulrich the Windows Edge release notes also link to the Mac issue on GitHub - [docker/for-mac#3646](https://github.com/docker/for-mac/issues/3646)
> 
> Is this correct? Is there a specific issue created for Windows that we can reference from Release Notes?

Yes, it is good. This issue concerns the two platforms.

**Comment by ulrich** [comment]
LGTM

**Comment by usha-mandya** [comment]
Thanks @ulrich . Are you happy with the updated text:
" - Upgrade QEMU from 2.8.0 to 3.1.0 to fix an emulation issue when building and running Java applications on Arm64 devices. "

**Pull request merged**
