### PR TITLE
Add note about --all option being the default behavior for `docker-compose rm`

### LINKED ISSUE #2281: Remove -a flag from reference doc
File: [compose/reference/rm.md](https://docs.docker.com/compose/reference/rm/)

Documentation refers to an optional flag `-a`.
> Options:
    -a, --all     Also remove one-off containers created by
                  docker-compose run

But when running latest (docker-compose version 1.11.2, build dfed245) `docker-compose rm` with the mentioned flag a warning is displayed:

```
WARNING: --all flag is obsolete. This is now the default behavior of `docker-compose rm`
```

Documentation should be updated to reflect the new behaviour.

### PR DESCRIPTION
**Pull request by shubheksha**
### Related issues (optional)
Fixes #2281

### CODE REVIEW

**Comment by shubheksha** [comment]
Should the option be removed altogether from the doc?

**Comment by mstanleyjones** [comment]
Yes, I think a better solution is to remove it from the doc. Maybe document instead how to show only a sub-set.

**Comment by joaofnfernandes** [comment]
@shin- I don't see this mentioned in the Compose release notes on github. Can you add it to the relevant release?

**Comment by shin-** [comment]
@joaofnfernandes That was back in 1.8.0:  https://github.com/docker/compose/blob/master/CHANGELOG.md#180-2016-06-14

**Pull request merged**
