### PR TITLE
Add pointer to latest API ref

### PR DESCRIPTION
**Pull request by mstanleyjones**
cc/ @johndmulhausen take 2

### CODE REVIEW

**Comment by mstanleyjones** [comment]
How in the world did this work before? I can't get it to work now. Weird.

cc/ @allejo thoughts?

**Comment by allejo** [comment]
@mstanleyjones So in YAML, `---` has a special meaning, it's how to define the "start" of a document. I did some testing and my guess is that two lines of `---` in a YAML data file is treated as two "documents" within the same file and not as Jekyll's Front Matter (possibly because there shouldn't be any Liquid templates inside the `_data` folder, just data?). As for how it probably worked the first time, something might have been cached in the process and it just seemed to work.

**Comment by mstanleyjones** [comment]
It works now! 💃 

To test, you need to check out the branch, run `docker build -t mytest .`, run the container locally, then look at the TOC.

**Comment by allejo** [comment]
This is what I see

https://deploy-preview-4897--docker-docs.netlify.com/reference/

image

**Comment by mstanleyjones** [comment]
@allejo can you do `jekyll clean` and try again? It is working for me:

screen shot 2017-10-16 at 11 08 24 am

**Comment by mstanleyjones** [comment]
And that screenshot made me see that we are using title case in that TOC entry. I'll update that.

**Comment by mstanleyjones** [comment]
OK, had to tweak the Dockerfile a bit more but all the tests are now running cleanly and we probably won't break things. Merging!

**Comment by mstanleyjones** [comment]
@bfirsh 🙌

**Pull request merged**
