### PR TITLE
Related pages links for docs per suggestion in PR#3903

### PR DESCRIPTION
**Pull request by londoncalling**
Signed-off-by: Victoria Bialas <vicky@thoughtspot.com>

### Proposed changes

* Added some cross-references to related Compose docs per most recent customer comments from @amelvill in PR #3903 on `restart` options (thought this might help)

### Related issues (optional)

* PR #3903

cc: @joaofnfernandes @shin-

### CODE REVIEW

**Comment by shin-** [comment]
@londoncalling 👋

I'd suggest introducing this paragraph with something like "if you're looking to configure a service's restart policy, please refer to [...]" instead, so people know what they're being referred to before clicking ; especially because the command and the policy are separate concepts that don't interact with one another.

**Comment by londoncalling** [comment]
Hi Joffrey ,
That makes sense. I’ll make that change. I also think there are a few more
pages where I could add a similar x-ref. I’ll find those too.

Vicky

**Comment by londoncalling** [comment]
@shin- sorry this took so long .. let me know what you think. Happy Holidays, hope you are well 🎁🎄

**Comment by bermudezmt** [comment]
Thanks, @londoncalling and @shin- . Happy new year to both of you!

**Pull request merged**
