### PR TITLE
Revert "Document order option in update_config"

### PR DESCRIPTION
**Pull request by mstanleyjones**
Reverts docker/docker.github.io#5089

### CODE REVIEW

**Comment by hairyhenderson** [comment]
@mstanleyjones was something wrong with #5089? why does it need to be reverted?

**Comment by hairyhenderson** [comment]
oh, I see the comment https://github.com/docker/docker.github.io/issues/5088#issuecomment-339169200 now...

**Comment by thaJeztah** [comment]
hm, yes, this is getting confusing now, as the specs in the docker/cli repository are considered the source of truth for the format, but the docs are tied to the docker compose release.

/cc @dnephin

**Comment by dnephin** [comment]
The specs in `docker/cli` are the source of truth for v3.x, the specs in `docker/compose` are the source of truth for v1 and v2.x. 

I don't know how the docs should be versioned, it doesn't necessarily fit the release cycle of either product.

**Pull request merged**
