### PR TITLE
Publish updates from master

### PR DESCRIPTION
**Pull request by usha-mandya**
Publish the latest changes from the master branch.

### CODE REVIEW

**Review by thaJeztah — COMMENTED** [review]
do we have a redirect for the m1 page now that it is being removed?

**Review by StefanScherer — APPROVED** [review]
LGTM

**Comment by usha-mandya** [comment]
@thaJeztah Yes, there's a redirect on the Apple silicon page for the M1 page.

**Comment by thaJeztah** [comment]
Ah, great! sorry, was on my phone and it was a bit difficult to check 😌

**Comment by usha-mandya** [comment]
No worries 😄

**Pull request merged**
