### PR TITLE
Add missing mandatory arguments.

### PR DESCRIPTION
**Pull request by JerryChin**
### Proposed changes

**Reason**
The command given herein is incomplete, and it will lead to an erroneous outcome,  which discourages the learners badly.

**Action**
I completed the command with the proper option and argument.

### Unreleased project version (optional)

N/A

### Related issues (optional)

N/A

### CODE REVIEW

**Comment by mstanleyjones** [comment]
@londoncalling PTAL.I think if your compose file is `docker-compose.yml`, you don't have to specify the `-c` option.

**Comment by londoncalling** [comment]
@JerryChin the command is correct, as written. The option `--compose-file` is the same as using `-c`, it indicates the path to your compose file. So you can use one or the other (not both). The example uses the long form of the option:

`docker stack deploy --compose-file docker-stack.yml vote`

In our example, we are in the same directory as the `docker-stack.yml`

Options for `docker stack deploy` command are shown [here](https://docs.docker.com/engine/reference/commandline/stack_deploy/#/options)  , or you can type `docker stack deploy --help` on the command line.

@ManoMarks any other thoughts or do you want to jump in? My sense is we should close out this PR, or mention that you can use either `-c` or `--compose-file`

**Comment by londoncalling** [comment]
@JerryChin I'm going to close this PR when PR #2042 is submitted. That should address your feedback more thoroughly and in line with the way the tutorial is written. Thanks!

**Comment by JerryChin** [comment]
​​Okay, let's do it!




*Regards,Jerry Chin.*
*​下述​​真理​​不证自明：凡​为​人​类，​生而平等，秉造物者之赐，拥​​诸​不可​剥夺​之权利，包含生命权、自由权、​及追​求幸福权​。​​​*

**Comment by londoncalling** [comment]
@JerryChin Cool, thanks. 

The updates from PR #2042  are published. The topics I updated per your feedback are:

[Docker stacks and services](https://docs.docker.com/engine/getstarted-voting-app/#/docker-stacks-and-services)

[Deploy the app](https://docs.docker.com/engine/getstarted-voting-app/deploy-app/#/deploy-the-app)

I'm closing this PR. Please send more comments if needed.

**Pull request closed without merging**
