### PR TITLE
update for 3.0

### PR DESCRIPTION
**Pull request by JimCodified**
### Proposed changes

Updates for 3.0 features, naming, and marketing wording

> Note: some new proposed links have been added but I don't know the actual destination and as discussed some other new features should also have links to their documentation pages.

### Unreleased project version (optional)

For Docker Enterprise 3.0

### CODE REVIEW

**Comment by adrian-plata** [comment]
@JimCodified can you take another crack at this? There are a few conflicts because of the latest release. Feel free to ping me once it's done and ready for review.

**Comment by JimCodified** [comment]
@adrian-plata I fixed all the conflicts and the links that were broken. I'm not quite sure how the system shortens the link in markdown so I put the absolute URLs in.

**Comment by adrian-plata** [comment]
@JimCodified thanks, it LGTM. I'll merge it after we finish some other stuff on the docs side.

**Comment by ollypom** [comment]
@JimCodified @adrian-plata Hey Folks, just fixed the urls in https://github.com/docker/docker.github.io/pull/9158. 

You do not need to embed "https://docs.docker.com" in to docs. Either start from the directory root `/ee/ucp/admin/install/` or the preferred method (which persists archives) navigate from where you are, so if you are in `/ee/` then link is just `./ucp/admin/install/`.

**Pull request merged**
