### PR TITLE
Re-organized Compose install docs into tabs

### PR DESCRIPTION
**Pull request by londoncalling**
### What's changed

- reorganized Compose install topics into tabs

### Related

Follow-up on:
- PR #4130 
- Issue #4126 

### Reviewers

@shin- @dnephin 

Signed-off-by: Victoria Bialas <victoria.bialas@docker.com>

### CODE REVIEW

**Comment by londoncalling** [comment]
@mstanleyjones this is fixed now, ready to publish after review

**Comment by shin-** [comment]
Look slick :+1:

**Comment by mstanleyjones** [comment]
LGTM, it might be cool to have a little bit more visual separation between the tab area and the rest of the article.

**Comment by londoncalling** [comment]
@mstanleyjones added subtle `<hr>` at end of tabbed topics, other ideas re: backgrounds didn't work as well

**Comment by londoncalling** [comment]
Merging, Netlify is failing on several PR's right now.

**Pull request merged**
