### PR TITLE
Replace deprecated MAINTAINER with LABEL

### PR DESCRIPTION
**Pull request by MichaelPereira**
### Proposed changes

Replace MAINTAINER instruction with LABEL as MAINTAINER was deprecated in https://github.com/docker/docker/pull/25466 (docker v1.13)

### Related issues (optional)
- https://github.com/docker/docker/pull/25466

### CODE REVIEW

**Comment by mstanleyjones** [comment]
This also occurs in the following files. Can you take a look and see if any of them need to be updated too?

```bash
$ grep -rl 'MAINTAINER' *
docker-hub/webhooks.md
engine/admin/ambassador_pattern_linking.md
engine/admin/using_supervisord.md
engine/examples/apt-cacher-ng.Dockerfile
engine/examples/apt-cacher-ng.md
engine/examples/mongodb/Dockerfile
engine/examples/mongodb.md
engine/examples/postgresql_service.Dockerfile
engine/examples/postgresql_service.md
engine/examples/running_riak_service.Dockerfile
engine/examples/running_riak_service.md
engine/examples/running_ssh_service.Dockerfile
engine/examples/running_ssh_service.md
engine/reference/commandline/image_history.md
engine/reference/commandline/image_pull.md
engine/understanding-docker.md
opensource/doc-style.md
swarm/scheduler/filter.md
test.md
tests/Dockerfile
```

**Comment by MichaelPereira** [comment]
Good catch, I will take a look and update this PR

**Comment by MichaelPereira** [comment]
@mstanleyjones Should I just remove the useless `MAINTAINER` references like https://github.com/docker/docker.github.io/blame/master/engine/admin/ambassador_pattern_linking.md#L147 or replace them with a random LABEL value?

**Comment by mstanleyjones** [comment]
I think you can remove them. Thanks!

**Comment by mstanleyjones** [comment]
Ping?

**Comment by MichaelPereira** [comment]
I will try to get back to it sorry :)

**Comment by PereiraHugo** [comment]
I was resolving the conflicts. Thank you for taking care of it!

**Comment by mstanleyjones** [comment]
No problem, sorry about that. I knew exactly what it was about. Sorry for the lack of communication.

**Pull request merged**
