### PR TITLE
Document --vmwarevsphere-folder flag

### PR DESCRIPTION
**Pull request by ajfeatherstone**
This change should be merged in when https://github.com/docker/machine/pull/4131 is merged.

### Proposed changes

Document the --vmwarevsphere-folder flag

### Related issues (optional)

This pull request should only be accepted when https://github.com/docker/machine/pull/4131 is accepted.

### CODE REVIEW

**Comment by mistyhacks** [comment]
Upstream PR is still not merged. What is the story here? We can't really hold this PR open indefinitely.

**Comment by ajfeatherstone** [comment]
Hi @mistyhacks,

I'm not sure why the upstream PR hasn't been accepted. I've tagged the Docker Machine maintainers in a comment in the PR to try and get a response. Are you able to reach out to them too, as you're part of the same (GitHub) organization?

**Comment by ajfeatherstone** [comment]
The PR this refers to has now been merged, so I think this PR is good to go. I've also tweaked it slightly to add some more detail.

**Comment by mistyhacks** [comment]
Actually we can't merge this into `master` until there is a `machine` release. I'll merge it into `vnext-machine` in a bit. cc/ @shin- @gbarr01

**Pull request merged**
