### PR TITLE
Update insecure.md

### PR DESCRIPTION
**Pull request by arcosx**
### Proposed changes

Some known issues indicate that this configuration needs to be explained more clearly when using buildkit.

### Related issues (optional)

https://github.com/moby/moby/issues/41059
https://github.com/moby/moby/issues/41080

### CODE REVIEW

**Comment by usha-mandya** [comment]
@tiborvass Could you PTAL?

**Comment by StefanScherer** [comment]
@tonistiigi Could you PTAL? Is there a fix coming or is it good to merge right now?

**Comment by tonistiigi** [comment]
This has been updated in buildkit https://github.com/moby/buildkit/commit/67044875c4169d6663ac42e3b9e1619e232773ba . No sure about timeline when it will reach moby. I don't think this special section is needed for this, I'd rather just update the main example to include a protocol as there should never be a real-world case where tls vs http needs to be detected.

**Comment by arcosx** [comment]
> This has been updated in buildkit [moby/buildkit@6704487](https://github.com/moby/buildkit/commit/67044875c4169d6663ac42e3b9e1619e232773ba) . No sure about timeline when it will reach moby. I don't think this special section is needed for this, I'd rather just update the main example to include a protocol as there should never be a real-world case where tls vs http needs to be detected.

 Yes, I also think this PR can be closed.Thanks everyone.

**Pull request closed without merging**
