### PR TITLE
Adds reference to the virtual machine it's running

### PR DESCRIPTION
**Pull request by JJ**
### Proposed changes

I was wondering what kind of tools were available for hooks, and did [this question in SO](https://stackoverflow.com/questions/65389399/what-tools-are-available-in-docker-hub-hooks). After checking `uname` in a hook, I found out this seemed to be the case.

### Related issues (optional)

I have created #11951 for reference.

### CODE REVIEW

**Comment by thaJeztah** [comment]
@arkodg PTAL

**Review by arkodg — DISMISSED** [review]

**Review by usha-mandya — APPROVED** [review]

**Comment by usha-mandya** [comment]
@arkodg The Amazon Linux AMI has reached end of support as of 31 December 2020. Should we instead point to https://aws.amazon.com/amazon-linux-2/?

**Comment by usha-mandya** [comment]
Discussed with @thaJeztah. Updating the URL to Amazon Linux 2 as the Amazon Linux AMI standard support has reached EOL.

**Review by usha-mandya — APPROVED** [review]

**Comment by JJ** [comment]
Thanks!

**Pull request merged**
