### PR TITLE
This guide used legacy backticks.

### PR DESCRIPTION
**Pull request by IRus**
https://github.com/koalaman/shellcheck/wiki/SC2006
https://github.com/koalaman/shellcheck/wiki/SC2046

### CODE REVIEW

**Comment by johndmulhausen** [comment]
@docker/core-compose-maintainers Is this a canonical way to get Docker Compose?

**Comment by johndmulhausen** [comment]
By "canonical" I mean, is this a sustainable, best-practice way to get Docker Compose that the Compose team would recommend we provide to users?

**Comment by shin-** [comment]
@johndmulhausen Yes, this is the way we have recommended users install Compose for a long time.

**Comment by johndmulhausen** [comment]
@shin- Thanks so much! Merging now. :)

**Pull request merged**
