### PR TITLE
adding new cluster doc for azure

### PR DESCRIPTION
**Pull request by DawnWood-Docker**
### Related issues (optional)
ENGDOCS-82

### CODE REVIEW

**Comment by DawnWood-Docker** [comment]
Hey @ollypom I haven't done any editing, just added the [page](https://deploy-preview-9352--docsdocker.netlify.com/cluster/azure/), updated the toc, and put a link in the "about docker enterprise" topic, here: https://deploy-preview-9352--docsdocker.netlify.com/ee/supported-platforms/. Don't worry about formatting. I'll do that. Just want to make sure I'm covering all of the bases. thanks in advance.

**Comment by david-yu** [comment]
@DawnWood-Docker Would it be possible to have the headers of each section be the same as what's in Cluster for AWS? https://docs.docker.com/cluster/aws/ or perhaps the AWS Cluster docs to match what's here?

**Comment by DawnWood-Docker** [comment]
@david-yu Yes I will take a look at that now. Thank you for the feedback.

**Comment by david-yu** [comment]
Thanks @DawnWood-Docker !

**Pull request merged**
