### PR TITLE
Add known issue to DTR

### PR DESCRIPTION
**Pull request by joaofnfernandes**
/cc @vikstrous for visibility

### CODE REVIEW

**Comment by vikstrous** [comment]
That's not exactly accurate... It's very specifically when you hit next on the users page, then switch tabs and then go back. @kyhy please confirm

**Comment by kyhy** [comment]
Both of you are correct. Simple description might be more useful for the user.

**Comment by joaofnfernandes** [comment]
Does the problem go away if the user refreshes the page?

**Comment by vikstrous** [comment]
yes

**Pull request merged**
