### PR TITLE
fix the install using apt snippet

### PR DESCRIPTION
**Pull request by ziv**
### Proposed changes
Change the install snippet using apt (docs changes)
the original install snippet was wrong, the apt repository don't holds packages named docker-ce

### CODE REVIEW

**Comment by adrian-plata** [comment]
Nice catch and thanks for contributing!

**Comment by pfeerick** [comment]
Since when? I just followed this on a arm64 cluster I was setting up and had to remove `docker` and install `docker-ce` because of this seeminly incorrect change resulting in the wrong version of docker being installed. My `ubuntu-disco` laptop also shows `docker-ce` as present. Maybe the OP didn't add the docker repo?

```
pfeerick@pfeerick-E6430:~$ apt-cache madison docker-ce
 docker-ce | 5:19.03.1~3-0~ubuntu-disco | https://download.docker.com/linux/ubuntu disco/stable amd64 Packages
 docker-ce | 5:19.03.0~3-0~ubuntu-disco | https://download.docker.com/linux/ubuntu disco/stable amd64 Packages
pfeerick@pfeerick-E6430:~$ apt-cache madison docker
    docker |      1.5-2 | http://mirror.aarnet.edu.au/pub/ubuntu/archive disco/universe amd64 Packages
    docker |      1.5-2 | http://mirror.aarnet.edu.au/pub/ubuntu/archive disco/universe i386 Pack
pfeerick@pfeerick-E6430:~$ apt-cache madison docker-ce-cli
docker-ce-cli | 5:19.03.1~3-0~ubuntu-disco | https://download.docker.com/linux/ubuntu disco/stable amd64 Packages
docker-ce-cli | 5:19.03.0~3-0~ubuntu-disco | https://download.docker.com/linux/ubuntu disco/stable amd64 Packages
pfeerick@pfeerick-E6430:~$ apt-cache madison containerd.io
containerd.io |    1.2.6-3 | https://download.docker.com/linux/ubuntu disco/stable amd64 Packages
containerd.io |    1.2.5-1 | https://download.docker.com/linux/ubuntu disco/stable amd64 Packages

```

**Comment by thaJeztah** [comment]
Yes, this change doesn't look correct; the `docker` and `docker-compose` packages are likely coming from the ubuntu package repositories, not from the official docker repositories.

I'll open a PR to revert this change once I'm back at my computer

**Comment by thaJeztah** [comment]
opened https://github.com/docker/docker.github.io/pull/9154 to revert

**Pull request merged**
