### PR TITLE
EOL version refresh

### PR DESCRIPTION
**Pull request by paigehargrave**

### CODE REVIEW

**Comment by bermudezmt** [comment]
Dependent on https://github.com/docker/cli/pull/1607 getting merged.

**Comment by thaJeztah** [comment]
see https://github.com/docker/cli/pull/1607#discussion_r246454992 those markdown files are not used in this repository (only part of their content, but not the meta headers)

**Comment by bermudezmt** [comment]
Got it, @thaJeztah . I incorrectly assumed the meta headers applied for the content that's being pulled from `docker/cli`. We will discuss and circle back to this PR and the related Engine CLI content updates.

**Comment by thaJeztah** [comment]
Also adding to the above; I'm not exactly sure how the original markdown stubs were added to this repository (if that was a one-time manual action, or if there's a script somewhere). We may have to check for that (as some new commands are added, and if those will automatically appear on the docs, or if a manual action is required to add stubs for those before importing/updating the YAML files)

**Comment by bermudezmt** [comment]
@thaJeztah there is a script for Engine CE CLI (https://github.com/docker/docker.github.io/blob/master/_scripts/fetch-upstream-resources.sh) updates, and a README (https://github.com/docker/docker.github.io/blob/master/engine/reference/commandline/README.md) for the YAML files generated from `docker/cli` with your username mentioned in it. :smile: 

Hope that sheds some light.

**Pull request merged**
