### PR TITLE
Improve Cloudfront notes regarding private buckets

### PR DESCRIPTION
**Pull request by spkane**
### Proposed changes

Added some missing details about setting up a Cloudfront distribution for Docker distribution, when leveraging a private S3 bucket.

### CODE REVIEW

**Comment by joaofnfernandes** [comment]
@dmcgowan can you take a look?

**Comment by mistyhacks** [comment]
@ddebroy PTAL

**Comment by ddebroy** [comment]
Looks good but someone from DTR who is more familiar with this should officially approve.

**Comment by mistyhacks** [comment]
@ddebroy can you please nominate someone?

**Comment by ddebroy** [comment]
Hey @vikstrous can you take a look at this or point to the right person?

**Comment by stevvooe** [comment]
LGTM

**Pull request merged**
