### PR TITLE
build: add bake section

### PR DESCRIPTION
**Pull request by crazy-max**
As discussed with @dockertopia and @jedevc, split bake and guides from #14905 as there is more work to do with guides.

Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>

### CODE REVIEW

**Review by jedevc — APPROVED** [review]

**Comment by crazy-max** [comment]
```
#16 156.4 - ./_site/build/bake/compose-file/index.html
#16 156.4   *  linking to internal hash #hcl-definition that does not exist (line 196)
#16 156.4      <a href="file-definition.md#hcl-definition">HCL format</a>
#16 156.4   *  linking to internal hash #target that does not exist (line 114)
#16 156.4      <a href="file-definition.md#target">target</a>
#16 156.4 - ./_site/build/bake/file-definition/index.html
#16 156.4   *  internally linking to compose-file.md, which does not exist (line 412)
#16 156.4      <a href="compose-file.md">Building from Compose file</a>
#16 156.4   *  internally linking to configuring-build.md, which does not exist (line 219)
#16 156.4      <a href="configuring-build.md">Configuring builds</a>
#16 156.4   *  internally linking to hcl-funcs.md, which does not exist (line 259)
#16 156.4      <a href="hcl-funcs.md">User defined HCL functions</a>
#16 156.4   *  linking to internal hash #remote-definition that does not exist (line 266)
#16 156.4      <a href="file-definition.md#remote-definition">imported remotely</a>
#16 156.4 - ./_site/build/bake/hcl-funcs/index.html
#16 156.4   *  linking to internal hash #variable that does not exist (line 113)
#16 156.4      <a href="file-definition.md#variable">File definition</a>
#16 156.4 - ./_site/build/bake/index.html
#16 156.4   *  internally linking to build-contexts.md, which does not exist (line 145)
#16 156.4      <a href="build-contexts.md">Defining additional build contexts and linking targets</a>
#16 156.4   *  internally linking to compose-file.md, which does not exist (line 146)
#16 156.4      <a href="compose-file.md">Building from Compose file</a>
#16 156.4   *  internally linking to configuring-build.md, which does not exist (line 143)
#16 156.4      <a href="configuring-build.md">Configuring builds</a>
#16 156.4   *  internally linking to file-definition.md, which does not exist (line 142)
#16 156.4      <a href="file-definition.md">File definition</a>
#16 156.4   *  internally linking to hcl-funcs.md, which does not exist (line 144)
#16 156.4      <a href="hcl-funcs.md">User defined HCL functions</a>
#16 156.4 
#16 156.4 HTML-Proofer found 12 failures!
```

Looks like the `include_remote` plugin does not resolve markdown files for links :disappointed:. I guess this is because the stub file is already rendered or maybe I miss some parts of the `include` implementation from Jekyll core. Will take a look.

**Comment by crazy-max** [comment]
> Looks like the `include_remote` plugin does not resolve markdown files for links 😞. I guess this is because the stub file is already rendered or maybe I missed some parts of the `include` implementation from Jekyll core. Will take a look.

Worst than I thought.. `include` or `include_remote` does not render links to markdown files. Jekyll limitation :persevere:. Will find a way to solve this. (cc @thaJeztah)

**Comment by crazy-max** [comment]
Ok found a better way to tackle this issue. I removed the `include_remote` plugin and now directly handles includes in our `fetch_remote` plugin. This way there is no post-processing with liquid tags and we don't need to fetch resources in `_includes` folder anymore. Everything is now managed through frontmatter vars. See first commit for more info. (cc @thaJeztah)

**Comment by crazy-max** [comment]
Looks good, PTAL @jedevc @dockertopia

**Review by jedevc — APPROVED** [review]

**Review by dockertopia — APPROVED** [review]
LGTM.
I'll merge this one once #15164 is good to go.

**Pull request merged**
