### PR TITLE
Shorten all (-a) and quite (-q) in recap cheatsheet

### PR DESCRIPTION
**Pull request by renjithspace**
### Proposed changes

Shorten all, `-a` and quite, `-q` params  to `--aq`

### CODE REVIEW

**Comment by renjithspace** [comment]
Screenshot from 2019-03-19 21-30-01
@thaJeztah  Both work the same way. I suggesting it's better to have in shorten way.

**Comment by paigehargrave** [comment]
https://github.com/docker/docker.github.io/pull/8878. @thaJeztah @renjithspace PTAL - thank you!

**Comment by thaJeztah** [comment]
Without an explanation in this part of the docs, I don't think we should make this change (also see my comment above); we should either keep it as-is, or decide if we want to explain that shorthand flags can be concatenated (which could be too much information at this point, and possibly distract from the general flow in this getting started)

**Comment by adrian-plata** [comment]
@renjithspace thanks for contributing! As was stated above, we'll be keeping `-a` and `-q` separate given the nature of the page. I'll be closing this PR as a result.

**Pull request closed without merging**
