### PR TITLE
Add instructions for manual start of Docker daemon

### PR DESCRIPTION
**Pull request by onelovelyname**
Docker daemon did not automatically start for me; running `sudo docker run hello` resulted in the following error message: 
```bash
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
```

After starting the docker daemon manually using `dockerd`, I saw the expected information.

### CODE REVIEW

**Comment by nathanleclaire** [comment]
It seems more likely it should be started via system service manager, no?  So in CentOS I'd expect that it's systemd and probably something like `sudo systemctl start docker`?

**Comment by mstanleyjones** [comment]
I'm more curious to know why it didn't start automatically for you. What version of Docker were you installing and what version of CentOS? I'd like to try to replicate this.

Also, if this really is an issue with CentOS not starting the daemon automatically, we need to just tell people to start it, rather than give them a cautionary thing to do if it doesn't start. I'd prefer to avoid it altogether though, so if you can get me that info, it would be great!

**Comment by nathanleclaire** [comment]
@mstanleyjones FWIW, IIRC some package managers won't start installed daemons / services automatically, so it's not unexpected to have to start them after the fact.

**Comment by nathanleclaire** [comment]
I agree we should verify it's out-of-the-box behavior before covering in docs though 👍

**Comment by mstanleyjones** [comment]
OK, verified that Docker does **not** start automatically on CentOS. Thank you bringing this up. I'm going to do the fix in a slightly different way than you have it, but I'll commit into your PR, if that's OK.

**Pull request merged**
