### PR TITLE
Update ubuntu.md

### PR DESCRIPTION
**Pull request by bkcsfi**
the add-apt-repository command listed in the documentation did not work for me on 16.04

I got this proposed fix from bdmorin's post  on https://github.com/docker/machine/issues/3184 (posted today)

I have tested this only on 16.04

### CODE REVIEW

**Comment by johndmulhausen** [comment]
Looks like this fork needs a force push

**Comment by bkcsfi** [comment]
Do I need to do something? sorry my github/workflow fu is low and I don't really have any time to research what's needed. Based on the conflicts I guess I need to re-merge master and re-submit changes to ubuntu.md and PR template?

**Comment by mstanleyjones** [comment]
Let me see what I can do to fix this.

**Comment by mstanleyjones** [comment]
Fixed by #1229. Thanks for the report!

**Pull request closed without merging**
