### PR TITLE
Add missing code-hints, and minor markdown edits

### PR DESCRIPTION
**Pull request by thaJeztah**
foillow-up to https://github.com/docker/docker.github.io/pull/13299

- Add missing code-hints (console, yaml)
- Consistently add an empty line after code-blocks
- Combine some examples where the output and the command were  put in separate blocks. With the "console" code-hint, this  is no longer nescessary.
- fix indentation in cloud/ecs-integration.md, which caused the  numbered-list to be interrupted.

### CODE REVIEW

**Comment by thaJeztah** [comment]
@usha-mandya @StefanScherer PTAL

**Review by StefanScherer — DISMISSED** [review]
LGTM 🧹

**Comment by thaJeztah** [comment]
FWIW: If we are good with https://github.com/docker/docker.github.io/pull/13353, I think rebasing this _after_ that one will be easier (git should in most cases automatically pick up the renamed files)

**Comment by thaJeztah** [comment]
Rebased, as https://github.com/docker/docker.github.io/pull/13353 was merged 👍

**Review by usha-mandya — APPROVED** [review]
LGTM

**Review by StefanScherer — APPROVED** [review]
LGTM

**Pull request merged**
