### PR TITLE
Updates docs for s390x for latest version

### PR DESCRIPTION
**Pull request by Prabhav-Thali**
Signed-off-by: Prabhav Thali <Prabhav.Thali1@ibm.com>

### Proposed changes
Removed SLES 15-SP2 as it is EOL
Added RHEL 9 in rhel.md
Added Ubuntu 22.04 in rootless.md

### CODE REVIEW

**Review by dockertopia — COMMENTED** [review]
@Prabhav-Thali thanks for this, I'll reach out to clarify this specific change "Removed SLES 15-SP2 as it is EOL".

**Review by StefanScherer — APPROVED** [review]
LGTM
Thank you!

**Comment by usha-mandya** [comment]
Close and reopen PR to trigger build checks

**Review by dockertopia — APPROVED** [review]
Was going to clarify one of the changes but if @StefanScherer approves these, then we're good to go.

**Comment by Prabhav-Thali** [comment]
Hi @dockertopia , Any update?

**Comment by dockertopia** [comment]
> Hi @dockertopia , Any update?
@Prabhav-Thali, thanks for the follow-up, trying to check why it's failing one check, can only merge after that. It's been approved for a while. Apologies for this.

**Comment by thaJeztah** [comment]
carrying this in https://github.com/docker/docker.github.io/pull/15245 (rebased this branch to see if that fixes CI)

**Pull request closed without merging**
