### PR TITLE
Remove references to Docker Stack

### PR DESCRIPTION
**Pull request by lorenrh**
Signed-off-by: Lorena Rangel <lorena.rangel@docker.com>

### Proposed changes

Update the Deploy to Kubernetes page, by removing the reference to deploy to docker Stack, and updating the panel image.

### CODE REVIEW

**Review by usha-mandya — APPROVED** [review]
LGTM. Thank you @lorenrh

**Comment by thaJeztah** [comment]
Did a quick check if the image was optimised, and ImageOptim said it was all good (thanks!!)

**Comment by usha-mandya** [comment]
Yes, that's right. Had asked @lorenrh to optimize the image using ImageOptim :) 

Thanks Lorena!

**Comment by usha-mandya** [comment]
Still checking if this is ready to go live. I've updated the title so we don't accidentally merge the PR.

**Pull request merged**
