### PR TITLE
Rebase vnext-engine on master

### PR DESCRIPTION
**Pull request by mstanleyjones**
### Describe the proposed changes

Merged `master` into `vnext-engine` because I needed to propagate the changes to how
we get `docker/docker` reference docs and so I can finish #583 

### Unreleased project version

engine 1.13

### Please take a look

@thaJeztah there were a few commits here I think you should look at, to make sure I chose the correct side. I'll find them in the list and call them out. I don't expect an exhaustive review.

cc/ @johndmulhausen

### CODE REVIEW

**Comment by mstanleyjones** [comment]
@thaJeztah you will need to use the command line to review this. You can probably skip reviewing everything that is not in `engine` and then it will be faster. This might help (I ran this while I was in the `engine/` subdir:

```bash
$ git log --since=2016-11-04 --oneline .
85e0097 Merge branch 'master' into vnext-engine
2bd57a4 Merge pull request #685 from aanand/deploy-composefile
90819b7 Merge branch 'master' of https://github.com/docker/docker.github.io
526a9b9 Fixing merge conflict
70617e6 Adding Yakkety to opening list
921964a s/sizes/size
0891e12 Merge pull request #408 from yangyuqian/explain_downloaded_image_and_container_size
2e5892e Writerly changes
2f817e4 Fix merge conflicts
a5bf14e Merge pull request #334 from mstanleyjones/run_reference_reorg
a9e535f Merge pull request #610 from fbouliane/add-dns-host-to-instructions
756f4d9 Fix some doubled words
3bcd9b4 Replace 'ls Dockerfile' with 'ls'
da3b4ff First version of stack deployment tutorial
4364535 Merge pull request #640 from mstanleyjones/203_dns_server_ubuntu
d0fb13d Add redirect for /articles/networking/
8dfa987 Merge pull request #531 from mstanleyjones/528_pin_image_by_digest
718296c Rewrites to Ubuntu installation
1cf72c7 Document ability to update a service's image
a4b2357 Clarification about flocker driver (#626)
eeace80 Merge pull request #698 from sanscontext/more-d-id
013d8f0 Merge pull request #631 from mstanleyjones/followup_link_flag
d3155b9 About the docker_gwbridge network (#400)
c23aa3a remove some unneeded text with new Docker ID topic
5c3bc27 Merge pull request #558 from akirakoyasu/patch-logging-fluentd-address
1c8370d Add NATS client as option for publishing container logs (#369)
b9e40eb Updated the link text to "the instructions for installing Docker on Ubuntu"
b356a0b Updated the URL syntax in mark down at line 73
30772c6 Merge pull request #511 from mstanleyjones/pull_docker_refs_from_git
26ce688 Adds a space to correct broken code block
707b035 live-restore unsupported on Windows (#564)
97d8ab1 Add topic about limiting container resources
d27ac5e Add a little more clarification about --link
4725674 Pin notary-server to v0.4.2
2b05451 Merge pull request #584 from thaJeztah/check-docs-sync
00b4a1a Remove the naming digression from the networking tutorial
d2e8ccf Remove engine docs for refs, plugins, deprecated from docs source
6436b0f Create logentries.md (#244)
71368b4 Add DNS SubjectAltName to certificate recipe
9f8db0f Remove redirect that was an error
1e688ad Merge pull request #540 from dhauenstein/patch-1
a0719b1 Merge pull request #597 from guillaumeguerin/patch-1
5a8b802 Merge pull request #579 from scottlaw1/patch-1
2f565d6 Change apt-key keyserver URL
ad491d6 Update step_four.md
089d910 Update understanding-docker.md (#406)
52a6f05 Add engine changes that were lost in syncing
babd3da Change "tho" to "though"
185b5db Provide clarification on status of `--link`
a726bf5 rephrase description of adding GUI to USER instruction
8c2a09e Update ubuntulinux.md
b0e0566 Added command for ssh into swarm manager
cff0907 add unix-sockets support in Fluentd logging driver
b480b75 Merge pull request #433 from docker/revert-175-patch-1
a5e01e1 fix type of keywords entry in frontmatter (in /engine/) (#552)
1cead39 Added GID to USER instruction
65aa473 Merged master into vnext-engine to get metadata updates
57b45d5 fix duplicated page titles (#512)
bc6f46a Add Ubuntu 16.10 Yakkety Yak
db153d8 Revert "remove ubuntu wily 15.10"
4508863 Remove Ubuntu 15.10 Wily Werewolf
ff59423 Merge pull request #440 from rillig/we-you
71ff5c1 Add missing whitespace (#486)
3882cb1 Updated link in step_four.md (#478)
d35d1f7 Stylistic cleanup in usingdocker.md
2c9eff5 Replace "we" with "you", as per the style guide
a0aa3e7 Reword and reformat "Breaking changes" page (#473)
5433809 Update service_create.md
```

**Comment by thaJeztah** [comment]
@mstanleyjones looks like that only shows the commits that were opened against the `vnext-engine` branch, but the merge from "master" shows as a single line

```
85e0097 Merge branch 'master' into vnext-engine
```

**Comment by mstanleyjones** [comment]
@thaJeztah ooh you are right, so you can just do a `git diff HEAD^`?

**Comment by thaJeztah** [comment]
ok, there are some issues; some changes present in vnext-engine are reverted in the merge, it at least spotted [engine/installation/linux/ubuntulinux.md]( https://github.com/mstanleyjones/docker.github.io/blob/85e0097088992108524a2d0fe015fc1981c2ccde/engine/installation/linux/ubuntulinux.md) (adds Ubuntu 15.10 again, which was removed in https://github.com/docker/docker.github.io/pull/503)

also saw [engine/admin/logging/splunk.md](https://github.com/mstanleyjones/docker.github.io/blob/85e0097088992108524a2d0fe015fc1981c2ccde/engine/admin/logging/splunk.md), where https://github.com/docker/docker/commit/603fd0831513257bc26d20ca1f64efcc4965eae6 (https://github.com/docker/docker/pull/25786) and https://github.com/docker/docker/commit/4907cc7793cf469fc2d6fc0f842d08bd045da569 (https://github.com/docker/docker/pull/26207) are reverted

Is the plan to keep this branch alive after it was merged to master? It's a pity we can't just rebase the branch on top of master (for a cleaner history) 😇 

Looks like there's some unrelated whitespace changes as well

```
git --no-pager diff HEAD^ | grep "No newline at end of file" | wc -l
317
```

We should try to be more strict when reviewing to prevent that (https://github.com/docker/docker.github.io/pull/552#pullrequestreview-10741188)

**Comment by mstanleyjones** [comment]
This one is hopeless, opening a new PR.

**Pull request closed without merging**
