### PR TITLE
WIP - Add algorithm label

### PR DESCRIPTION
**Pull request by traci-morrison**
### Proposed changes

- Add `com.docker.lb.algorithm` label to https://docs.docker.com/ee/ucp/interlock/usage/labels-reference/

### Related issues (optional)
https://github.com/docker/docker.github.io/issues/9749

### CODE REVIEW

**Comment by traci-morrison** [comment]
> LGTM, thanks !
> 
> Lets wait till the code merges for this docs change to merge
> 
> cc @euanh

Does this need to be published with the patch release on Tuesday?

**Comment by arkodg** [comment]
@traci-morrison AFAIK we are not releasing a new version of Interlock for Novemeber (@euanh please correct me if I'm wrong) so we don't need to merge this yet

**Comment by euanh** [comment]
> @traci-morrison AFAIK we are not releasing a new version of Interlock for Novemeber (@euanh please correct me if I'm wrong) so we don't need to merge this yet

That's correct.   We are not releasing a new Interlock in November so this documentation does not need to be merged yet.

**Comment by traci-morrison** [comment]
@euanh Are we still waiting to merge this PR? We are migrating content to Mirantis repos this week. All open PRs and issues in this Docker repo may be closed. I want to make sure this gets merged this week if need be. Thanks!

**Comment by euanh** [comment]
@traci-morrison I'm afraid we still haven't shipped an interlock release with this option, so it would be confusing to put it in the docs. :(

**Comment by traci-morrison** [comment]
Closing because the feature will not be released before the repository is migrated.

**Pull request closed without merging**
