### PR TITLE
CI - added test for keywords in markdown frontmatters

### PR DESCRIPTION
**Pull request by aduermael**
### Describe the proposed changes

I added tests to make sure keywords are correctly formatted in markdown frontmatters. 
The `keywords` field should always contain a comma separated string (and not an array).

Otherwise the meta tag for keywords in html is not generated correctly. Example from current https://docs.docker.com/engine/breaking_changes/:

```html
<meta name="keywords" content="docker, documentation, about, technology, breakingincompatibilities">
```

My fix for this file: https://github.com/docker/docker.github.io/pull/805/files#diff-19905fe91a80cf99357f4c7a0d4326dd

### CODE REVIEW

**Comment by johndmulhausen** [comment]
Deploy preview ready!

Built with commit b25a9746bdafc8a1defb7b0976a27dcd2bf70e0a

https://deploy-preview-805--docker-docs.netlify.com

**Comment by aduermael** [comment]
Tests are failing because some keywords still need to be fixed:

```
17:33:09 --- FAIL: TestFrontMatterKeywords (0.06s)
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/apidocs/index.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/apidocs/overview.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/apidocs/v1.3.3/index.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/apidocs/v1.4.0/index.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/apidocs/v2.0.0/index.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/apidocs/v2.0.1/index.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.0/support.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/guides/architecture.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/guides/configure/configure-storage.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/guides/configure/index.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/guides/high-availability/backups-and-disaster-recovery.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/guides/high-availability/index.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/guides/index.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/guides/install/index.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/guides/install/install-offline.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/guides/install/license.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/guides/install/system-requirements.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/guides/install/uninstall.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/guides/install/upgrade.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/guides/monitor-troubleshoot/index.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/guides/monitor-troubleshoot/troubleshoot.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/guides/release-notes.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/guides/repos-and-images/delete-an-image.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/guides/repos-and-images/index.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/guides/repos-and-images/pull-an-image.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/guides/repos-and-images/push-an-image.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/guides/support.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/guides/user-management/create-and-manage-orgs.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/guides/user-management/create-and-manage-teams.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/guides/user-management/create-and-manage-users.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/guides/user-management/index.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/guides/user-management/permission-levels.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/reference/api/index.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/reference/cli/backup.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/reference/cli/dumpcerts.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/reference/cli/images.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/reference/cli/index.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/reference/cli/install.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/reference/cli/join.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/reference/cli/reconfigure.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/reference/cli/remove.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/reference/cli/restore.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/dtr/2.1/reference/cli/upgrade.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/1.1/release_notes.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/1.1/support.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/access-ucp/cli-based-access.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/access-ucp/index.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/applications/deploy-app-cli.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/applications/index.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/architecture.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/configuration/configure-logs.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/configuration/index.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/configuration/integrate-with-dtr.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/configuration/integrate-with-ldap.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/configuration/route-hostnames.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/content-trust/index.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/content-trust/manage-trusted-repositories.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/high-availability/backups-and-disaster-recovery.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/high-availability/index.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/index.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/installation/index.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/installation/install-offline.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/installation/license.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/installation/plan-production-install.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/installation/scale-your-cluster.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/installation/system-requirements.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/installation/uninstall.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/installation/upgrade.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/monitor/index.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/monitor/troubleshoot-configurations.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/monitor/troubleshoot.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/release-notes.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/support.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/user-management/create-and-manage-teams.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/user-management/create-and-manage-users.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/user-management/index.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/guides/user-management/permission-levels.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/reference/cli/backup.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/reference/cli/dump-certs.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/reference/cli/fingerprint.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/reference/cli/id.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/reference/cli/images.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/reference/cli/index.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/reference/cli/install.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/reference/cli/restart.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/reference/cli/restore.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/reference/cli/stop.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/reference/cli/support.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/reference/cli/uninstall-ucp.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/datacenter/ucp/2.0/reference/cli/upgrade.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/notary/reference/client-config.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/notary/reference/common-configs.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/notary/reference/index.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/notary/reference/server-config.md
17:33:09 	markdown_test.go:64: keywords should be a comma separated string - /docs/notary/reference/signer-config.md
```

- 6 files in `/apidocs`
- 84 files in `/datacenter`
- 5 files in `/notary/reference`
 
@johndmulhausen I know some of these files are pulled from different locations and/or generated. I will wait for PRs fixing those issues to be merged, then I'll rebase and merge that one.

**Comment by aduermael** [comment]
@joaofnfernandes I fixed the keywords in `/datacenter` markdowns: 0983cb5

**Comment by aduermael** [comment]
@joaofnfernandes can you fix the ones in `/apidocs`?

```shell
/apidocs/overview.md
/apidocs/v1.3.3/index.md
/apidocs/v1.4.0/index.md
/apidocs/v2.0.0/index.md
/apidocs/v2.0.1/index.md
```

@johndmulhausen can you take care of the ones in `/notary/reference`?

```shell
/notary/reference/client-config.md
/notary/reference/common-configs.md
/notary/reference/index.md
/notary/reference/server-config.md
/notary/reference/signer-config.md
```


Thank you!

**Comment by joaofnfernandes** [comment]
#810 fixes the `/apidocs`

**Comment by joaofnfernandes** [comment]
The changes to `datacenter/` look good to me.

**Comment by johndmulhausen** [comment]
@aduermael Fixed the `/notary/reference` keywords.

**Comment by aduermael** [comment]
@johndmulhausen Thank you so much! 
All checks have passed, feel free to merge that PR! :)

**Comment by johndmulhausen** [comment]
@aduermael And the checks pass! Thanks so much for the PR, and thanks to @joaofnfernandes for the keyword fixes and review. :)

**Pull request merged**
