### PR TITLE
Fix: duplicate paragraph `depends_on`

### PR DESCRIPTION
**Pull request by romik-g**
### Proposed changes
Amend duplicate paragraph `depends_on` in Compose file reference doc.

### CODE REVIEW

**Comment by romik-g** [comment]
Hello team. Is anything else needed for this PR to get reviewed? Thanks!

**Comment by romik-g** [comment]
Hello team. Is anything else needed for this PR to get reviewed? Thanks!

**Comment by paigehargrave** [comment]
@thaJeztah @bermudezmt   Hi Maria/Sebastiaan - I'm not sure who the best person is for this - Chris Crone perhaps?

**Comment by bermudezmt** [comment]
Hey @paigehargrave - I think all of us are in SF now. I'll see if I can find @ulyssessouza and get this resolved while we're here. :wink:

**Pull request merged**
