### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by usha-mandya**
Signed-off-by: Usha Mandya <usha.mandya@docker.com>

Fixes https://github.com/docker/docker.github.io/issues/12193

### CODE REVIEW

**Comment by usha-mandya** [comment]
@StefanScherer PTAL

**Review by StefanScherer — DISMISSED** [review]
LGTM

**Comment by thaJeztah** [comment]
Looks like there's some other locations where we link to `faqs.md` in either "for-mac" or "for-windows"; https://github.com/docker/docker.github.io/search?q=faqs.md

**Comment by thaJeztah** [comment]
oh, those redirect to the `for mac` section, so perhaps they're ok

**Comment by usha-mandya** [comment]
Thanks @thaJeztah. Fixed those too. PTAL

**Review by StefanScherer — APPROVED** [review]
LGTM

**Pull request merged**
