### PR TITLE
Revert "Merge pull request #36 from mrburrito/aws-iam-roles"

### PR DESCRIPTION
**Pull request by londoncalling**
This reverts commit 82d9ab91b26d9d739a7b9db4407c01b4884ac3f1, reversing
changes made to c1188953ba031dade829fa832943479fbed5d7d3.

@nathanleclaire @mrburrito @johndmulhausen please take a look and see if this works for you guys for now. Relates to #36

### CODE REVIEW

**Comment by johndmulhausen** [comment]
Looks fine from a docs perspective. :)

**Comment by londoncalling** [comment]
Okay, I'll merge it, good for now!

**Comment by nathanleclaire** [comment]
cool, maybe we can un-revert on `machinedocs`-type branch we discussed

**Comment by londoncalling** [comment]
Yes , makes sense Nathan, I'll do that ! :-)

**Pull request merged**
