### PR TITLE
Fix archive butterbar margin-top

### LINKED ISSUE #4837: Archive bar obscured on 17.03, 17.06
https://docs.docker.com/v17.06/engine/docker-overview/

You can see it peeking out from under the top nav. It might be gnarly to fix this because the top nav bar is set to `position:fixed`; you might have to resort to frames or something.

### PR DESCRIPTION
**Pull request by mstanleyjones**
Fixes #4837 for 17.06

### CODE REVIEW

**Comment by mstanleyjones** [comment]
cc/ @seemethere any ideas?

**Comment by seemethere** [comment]
Appears to be failing at this line:

https://github.com/mstanleyjones/docker.github.io/blob/88d98ef3a9fa6cd76228baa2021a2cb9c885f3fd/Jenkinsfile#L18

`test` directory does not seem to exist within this revision. Maybe it needs a rebase?

**Comment by seemethere** [comment]
Yeah this `Jenkinsfile` doesn't seem to be built to work with the particular base branch you're trying to push to.

**Comment by mstanleyjones** [comment]
@jsouth this has the JS / CSS fixes we suggested (I think). PTAL

**Comment by mstanleyjones** [comment]
Jenkins failure will be solved by an upstream commit that hasn't hit yet.

**Pull request merged**
