### PR TITLE
Fixing SUSE install from repo instructions to correctly locate gpg key

### PR DESCRIPTION
**Pull request by millerdz**
In the **Install using the repository** section, the GPG implied location was identified as `<DOCKER-EE-URL>/sles/12.3/<ARCHITECTURE>/stable-<VERSION>/sles/gpg` which does not exist. The correct location is `<DOCKER-EE-URL>/sles/gpg`. I introduce a second variable here called `DOCKER_EE_BASE_URL` which will be used to distinguish between the root level of the directory and aid in correctly locating the gpg key for the `rpm --import` command.

### CODE REVIEW

**Comment by ahh-docker** [comment]
@kolyshkin PTAL. Thanks!

**Comment by kolyshkin** [comment]
This needs to be rebased. Otherwise LGTM

**Comment by ahh-docker** [comment]
@seemethere PTAL. Thanks.

**Comment by ahh-docker** [comment]
@L-Hudson this is ready for you, then it can be merged.

**Pull request merged**
