### PR TITLE
Vnext engine rebase

### PR DESCRIPTION
**Pull request by mstanleyjones**
### Describe the proposed changes

Rebase `vnext-engine` on current state of `master`

@thaJeztah @johndmulhausen @bfirsh PTAL

I'll need to force-push this, the PR is here just FYI.

### CODE REVIEW

**Comment by bfirsh** [comment]
Sounds good to me (as in, this will help with #606), but I don't know enough about the changes to be able to do a proper review.

**Comment by mstanleyjones** [comment]
So, to review this, I recommend: `git difftool upstream/vnext-engine -- engine/` with this PR checked out locally.

I think this rebase is OK to do now since at the time 1.13 is released, the `vnext-engine` branch will be merged into `master` and then hard-reset to `master`.

**Comment by mstanleyjones** [comment]
@thaJeztah pointed out that in order to preview the rebase, I needed to be comparing `master` to the rebased `vnext-engine`, instead of comparing the old `vnext-engine` to the rebased one. Again, this PR is just for preview and won't get merged. Instead I'll do a force-push to `vnext-engine` when review is complete.

**Comment by johndmulhausen** [comment]
Deploy preview ready!

Built with commit 420b3330c6cc84a9f6ba46c8de7e97e205c7b391

https://deploy-preview-756--docker-docs.netlify.com

**Comment by mstanleyjones** [comment]
BTW I think we can ignore the conflicts since we are not really going to merge this PR as-is.

**Comment by johndmulhausen** [comment]
Where are we on this? We're holding up #606 which is a pretty critical PR. If you can ignore the conflicts, are we good to go?

**Comment by mstanleyjones** [comment]
The force-push is done! Closing this now.

**Pull request closed without merging**
