### PR TITLE
Add note on Docker Official Images

### PR DESCRIPTION
**Pull request by usha-mandya**
- Add a new note about distributing Docker Official Images.
- Also contains a minor style update

### CODE REVIEW

**Comment by usha-mandya** [comment]
@nebuk89 Could you PTAL?

**Review by nebuk89 — APPROVED** [review]
LGTM ship it.

**Review by sudo-bmitch — COMMENTED** [review]
Does the note on this one mean that usage of an official image as a base image is a ToS violation when I distribute my own images? How about maintaining a local mirror?

> **Note**
>
> Docker Official Images are an intellectual property of Docker. Distributing Docker Official Images without a prior agreement can constitute a violation of [Docker Terms of Service](https://www.docker.com/legal/docker-terms-service){: target="blank" rel="noopener" class=“”}.

**Comment by usha-mandya** [comment]
@sudo-bmitch Discussed this internally and removed the clause on distributing images that are created using a Docker Official Image. Publicly mirroring Docker Official Images without an agreement with Docker would still constitute a violation of Docker ToS. 

Hope that clarifies your question.

**Pull request merged**
