### PR TITLE
Missing ssh tunnel option

### PR DESCRIPTION
**Pull request by lorenzo-pizzari**
### Proposed changes
I've tried to connect with ssh tunnel and i found that the port option is missing.
Added port option to doc.
If no port option is provided the tunnel don't work properly

### CODE REVIEW

**Comment by nathanleclaire** [comment]
👍 

BTW, just noticed this -- the `&` at the end of the command is not needed if the `-f` option for SSH ("fork" into the background) is used.

Also: Obligatory mention to say "don't expose Docker API unencrypted over the network", even on `localhost`.

**Comment by nathanleclaire** [comment]
Well, in Azure we use pubkey, so path to SSH key is not _strictly_ needed like it might be with AWS case...

**Comment by lorenzo-pizzari** [comment]
> BTW, just noticed this -- the & at the end of the command is not needed if the -f option for SSH ("fork" into the background) is used.
You're right! I've just pushed in this way.
> Well, in Azure we use pubkey, so path to SSH key is not strictly needed like it might be with AWS case...
Yes, but in the previous command there is the SSH key path, also the Azure SSH key can be different from the "system default" (~/.ssh/id_rsa)

**Comment by nathanleclaire** [comment]
> Yes, but in the previous command there is the SSH key path, also the Azure SSH key can be different from the "system default" (~/.ssh/id_rsa)

That's true !

**Pull request merged**
