### PR TITLE
modify docs feedback to route support questions properly and encourag…

### PR DESCRIPTION
**Pull request by londoncalling**
### Proposed changes

Strawman update to docs feedback footer. Goal is to re-route issues and questions that are better sent to Support, Forums, and Knowledge Hub and keep this feedback link for docs issues.

### Please take a look

@johndmulhausen @sanscontext @mstanleyjones @joaofnfernandes 

Signed-off-by: Victoria Bialas <victoria.bialas@docker.com>

### CODE REVIEW

**Comment by johndmulhausen** [comment]
Deploy preview ready!

Built with commit 9d354d74fcedf12d447134e9abf6014ab3f8ff82

https://deploy-preview-611--docker-docs.netlify.com

**Comment by sanscontext** [comment]
WDYT about "`Edit this page`, or `request doc changes`, or `contact Support`?"
I would also suggest linking directly to support.docker.com instead of the www site page.

**Comment by londoncalling** [comment]
@sanscontext @mstanleyjones @johndmulhausen please take a look. 

@sanscontext I didn't want to link directly to https://support.docker.com/ for a couple of reasons - a) only commercial customers with paid subscriptions can log in to that site, so for everyone else it will be a little bit of a dead-end and might increase frustration, b) linking to the the higher level page, https://www.docker.com/docker-support-services,  gives users an idea of other ways to get help or log issues (forums, knowledge base)

Also, Misty and I discussed that there are other ways for users to log bugs and get help, depending on the products they are using. For example, if you have Docker for Mac, you can log issues at https://github.com/docker/for-mac/issues, and if  you have Docker for Windows, you can log issues at https://github.com/docker/for-win/issues. Assuming there might be more of these product-specific channels for logging tickets, I'd like to chat with the website team about adding one or more links to https://www.docker.com/docker-support-services so that if we send users there from our docs, they'll get the full palette of choices (commercial Docker support, community forums, knowledge hub, and product-specific github issues boards).

Looping in @FSHA, @hansfrederickbrown  to follow up on this.

**Comment by johndmulhausen** [comment]
+1 to linking to the www support page for the reasons @londoncalling points out. Let's also not forget that there is a FAQ there that clarifies feedback channels even further for certain support levels.

Other than the fact that "Support" should be lowercase, this LGTM

**Comment by sanscontext** [comment]
Hm, my understanding was that even non-paying users can at least file support tickets via that portal. Maybe that was the old system only? @bryceryan-docker can you confirm?

**Comment by londoncalling** [comment]
@sanscontext From the sound of the description, of "Support" on that page, I think they need to have a paid subscription. But even if they can log support requests, you do still have to log in, and I wouldn't want to send them to something that isn't a little more open than that at first landing. Also, it's useful to see the other options.  Merging this for now, and I'm going to follow up with @FSHA on that Support web page. Also, will see what you hear from @bryceryan-docker as a follow up.

**Comment by sanscontext** [comment]
FWIW, they also have to log in to Github to use either of the other links.

**Pull request merged**
