### PR TITLE
compose v1.13 docs

### PR DESCRIPTION
**Pull request by shin-**
### Proposed changes

Documented new features in upcoming Compose 1.13.0

### Unreleased project version (optional)

Compose 1.13.0

### Related issues (optional)

https://github.com/docker/compose/pull/4750

### CODE REVIEW

**Comment by mstanleyjones** [comment]
@shin- do you want these squashed or separate?

**Comment by londoncalling** [comment]
LGTM

**Comment by londoncalling** [comment]
@mstanleyjones @shin- if there is no harm in doing these separate, I think that is nicer. It provides more flexibility if you want to back something out, right?

**Comment by shin-** [comment]
Yeah, I tried to have each independent change = 1 commit because in my experience it's easier to review. But if you'd rather have me squash them before merging into master, just let me know.

**Comment by londoncalling** [comment]
@shin- I'll merge this unsquashed, okay?

**Pull request merged**
