### PR TITLE
Move Compose file ref to the legacy node

### PR DESCRIPTION
**Pull request by usha-mandya**
Signed-off-by: Usha Mandya <usha.mandya@docker.com>

Move Compose file version 2 and 3 to a new legacy node

### CODE REVIEW

**Comment by glours** [comment]
I'm still confused with the Compose file format matrix, does it make sense to keep it for the legacy part only?

**Comment by usha-mandya** [comment]
Yes, that's not required. Also, the I think the page on versioning and upgrading should also move to the Legacy section. WDYT?

**Comment by glours** [comment]
way better 👍  
And the integration of the specification looks nice! Did you made a lot of changes on the specification markdowns?
Thanks @usha-mandya

**Comment by usha-mandya** [comment]
@glours Nothing much. A minor revamp to the overview section, updated the source files in upstream compose-spec and fixed a bunch of broken URLs.

**Review by glours — APPROVED** [review]
LGTM

**Pull request merged**
