### PR TITLE
fix username for tagged image in github actions

### PR DESCRIPTION
**Pull request by markgoho**
the username is hardcoded, but should use the same secret from the first step

### Proposed changes

I was getting an error when trying to push the image to Docker Hub. I'm guessing this was such a trivial thing that original authors assumed everyone would just know to not push to someone else's account name.

### CODE REVIEW

**Review by usha-mandya — APPROVED** [review]
LGTM. Thanks @markgoho :)

**Comment by usha-mandya** [comment]
Hey @markgoho, thanks for updating the docs :) 

Could you also update the following pages as these contain the same info:

- https://docs.docker.com/language/python/configure-ci-cd/
- https://docs.docker.com/ci-cd/github-actions/

**Comment by markgoho** [comment]
@usha-mandya yup! made these separate PRs though because I'm lazy and just using the GitHub editor which spins up a new branch for each edit

#12524 
#12525

**Comment by usha-mandya** [comment]
Haha, no worries. I'll take a look at the new PRs. :)

**Pull request merged**
