### PR TITLE
update dockercloud events api doc with filters

### PR DESCRIPTION
**Pull request by MaximeHeckel**
This updates dockercloud api docs with the filters for events

### CODE REVIEW

**Comment by johndmulhausen** [comment]
Deploy preview ready!

Built with commit ade815dacff22210dcc193b437affe2c1f0ca88c

https://deploy-preview-581--docker-docs.netlify.com

**Comment by sanscontext** [comment]
@fermayo for review - you should be able to see the changes at https://deploy-preview-581--docker-docs.netlify.com/apidocs/docker-cloud/

I can merge when it's been approved and you're ready.

**Comment by sanscontext** [comment]
Cool, just let me know when.

**Comment by fermayo** [comment]
@MaximeHeckel can you make sure this is up to date?

**Comment by MaximeHeckel** [comment]
this is up to date

**Pull request merged**
