### PR TITLE
Remove obsolete CS Engine docs

### PR DESCRIPTION
**Pull request by thaJeztah**
This comment https://github.com/docker/for-linux/issues/597#issuecomment-472336544 put my attention to these pages still being included in the documentation, but CS Engine has reached EOL, so better to remove them (they should still be available in the archived version of the documentation if really needed).

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @L-Hudson @mklamb @trapier PTAL

**Comment by thaJeztah** [comment]
Re-pushed; forgot to remove it from the navigation 😅

**Comment by mklamb** [comment]
LGTM, but will defer to @L-Hudson for archival strategy

**Comment by bermudezmt** [comment]
@shampabh @paigehargrave @JustinINevill Let's have a look at this PR when we meet later this week.

**Pull request merged**
