### PR TITLE
Add Compose v2 reference

### PR DESCRIPTION
**Pull request by usha-mandya**
Signed-off-by: Usha Mandya <usha.mandya@docker.com>

Add docs for Compose v2 Reference files

### CODE REVIEW

**Review by glours — APPROVED** [review]
LGTM

**Review by dockertopia — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Now that compose is part of the `docker` CLI, I think we should also start to consider removing the intermediate `Docker CLI (docker)`, `Docker Compose CLI reference` and `Daemon CLI (dockerd)` sub-headings. 

Screenshot 2022-06-21 at 13 05 47


We could move the "daemon" to a separate section, and put everything that's under `Docker CLI (docker)` directly under "Command-line reference".

definitely for a follow-up though (not part of this PR)

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
