### PR TITLE
Adjusted Service Principal guidance

### PR DESCRIPTION
**Pull request by stevenfollis**
### Proposed changes

Linked to additional Azure guidance on creating SPs, and referenced the brand new Azure Permissions docs page in the upstream Azure Cloud Provider Plugin documentation repo.

### CODE REVIEW

**Comment by stevenfollis** [comment]
cc @ollypom

**Comment by traci-morrison** [comment]
@stevenfollis @ollypom What is the status of this PR? Is it ready to be merged? Thanks.

**Comment by stevenfollis** [comment]
@traci-morrison  I talked to @ollypom this morning about it, he was going to do a bit of testing to make sure the custom role works as advertised then we should be gtg. Thanks!

**Comment by traci-morrison** [comment]
@stevenfollis @ollypom The Infrastructure team is copying our repos over to Mirantis this week. Any open PRs and issues will be lost, so please do what you can to close or merge this PR before Thursday. Thank you!

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

**Pull request closed without merging**
