### PR TITLE
[WIP] Dockerfile: split stages for "dev" and "deploy"

### PR DESCRIPTION
**Pull request by thaJeztah**
~This is a follow-up to https://github.com/docker/docker.github.io/pull/8413 - only the last commit is new~ (rebased)

The current Dockerfile defaults to include all archived documentation. While this
is the right thing to do when _deploying_ the documentation, it is far from optimal
when working on changes in the documentation, and building the documentation locally
(in which case, the archived documentation is likely not interesting).

This patch changes the Dockerfile to only build the current version of the documentation
by default.

> **Note** when building with the "classic" builder (so not using BuildKit), the archived
> documentation will still be built, because the classic builder is not able to skip
> unused build-stages.

This change might require changes in how the documentation is deployed, because in that
case, the documentation _including_ archives should be built.

Alternatively, the default could be changed to include the archives, but people wanting
to build docs without archives could set `--target=dev` when running `docker build`.

Before this change a full rebuild of the docs, including archives, took ~247 seconds
(already optimised if BuildKit is used, which fetches the archived docs in parallel):

```
docker build -t docs --target=deploy .

[+] Building 247.1s (30/30) FINISHED
=> FROM docker.io/docs/docker.github.io:v18.03 151.4s
=> FROM docker.io/docs/docker.github.io:v17.03 75.0s
=> FROM docker.io/docs/docker.github.io:v17.09 96.5s
=> FROM docker.io/docs/docker.github.io:v17.06 134.9s
=> FROM docker.io/docs/docker.github.io:v17.12 105.2s
...
=> [archives 1/5] COPY --from=docs/docker.github.io:v17.03 /usr/share/nginx/html /usr/share/nginx/html 1.7s
=> [archives 2/5] COPY --from=docs/docker.github.io:v17.06 /usr/share/nginx/html /usr/share/nginx/html 2.8s
=> [archives 3/5] COPY --from=docs/docker.github.io:v17.09 /usr/share/nginx/html /usr/share/nginx/html 3.8s
=> [archives 4/5] COPY --from=docs/docker.github.io:v17.12 /usr/share/nginx/html /usr/share/nginx/html 4.6s
=> [archives 5/5] COPY --from=docs/docker.github.io:v18.03 /usr/share/nginx/html /usr/share/nginx/html 2.7s
```

The size of the built image is ~1.6 GB

```
REPOSITORY TAG IMAGE ID CREATED SIZE
docs latest 8fd1a9d31da7 4 minutes ago 1.61GB
```

With this change, the archived docs are not fetched, and a full rebuild of the docs is reduced to ~200 seconds

```
[+] Building 203.1s (20/20) FINISHED
```

Given that the archives are not included by default, the size of the image also reduced considerably,
and is now about 340MB

```
REPOSITORY TAG IMAGE ID CREATED SIZE
docs latest bb7b1b9af649 7 seconds ago 339MB
```

### CODE REVIEW

**Comment by thaJeztah** [comment]
Let me put this one as "WIP" for a moment, to verify if (and what) changes are needed for deploying the docs; who's best to ask?

**Comment by thaJeztah** [comment]
(I'll rebase this one after https://github.com/docker/docker.github.io/pull/8413 is merged, to get rid of the extra commits)

**Comment by bermudezmt** [comment]
@peter-docker can you PTAL at this one? I have merged #8413 but need an extra pair of eyes on this change.

**Comment by bermudezmt** [comment]
@thaJeztah looks like this change breaks the archived versions of our site. Let me know if I missed anything on my end with testing.
Screenshot from 2019-03-08 15-29-38

**Comment by thaJeztah** [comment]
Ah, yes, that's expected if it's using the default `--target`; if for deployment the `deploy` target could be used, it would include the archives

```
docker build -t docs --target=deploy .
```

Not sure if that's easy to do though; so we could swap the defaults, and require people that want to build _without_ archives to use (e.g.) `docker build --target=dev .`

FWIW, the _ideal_ situation would be to deploy each archive as their own container (this is what I was originally was working on in https://github.com/docker/docker.github.io/pull/941)

**Comment by bermudezmt** [comment]
@thaJeztah sorry I was running around in SF so I had missed your comments on how to test this change. Specifying `--target=deploy` does build all the archives and it's much snappier. I have no problem with merging this PR, unless you wanted to swap the defaults on this PR. I would update the README to include that info if we went that way. 

I guess the only additional change I could think of would be to have the dropdown links of the archived versions link to localhost instead of `docs.docker.com`. I suspect that will be a trivial change, but wanted to note that here before I forget.

**Comment by bermudezmt** [comment]
@shampabh Let's also have a look at this one during our team meeting.

**Comment by thaJeztah** [comment]
This was superseded by https://github.com/docker/docker.github.io/pull/10331 and https://github.com/docker/docker.github.io/pull/10342

**Pull request closed without merging**
