### PR TITLE
Sync updates from master

### PR DESCRIPTION
**Pull request by usha-mandya**
PR to publish the Enterprise patch release

### CODE REVIEW

**Comment by Dawn-Wood** [comment]
Hi @usha-mandya and @thaJeztah do you see the error. I don't see what's wrong with the pr so hoping you can point me in the right direction.

**Comment by usha-mandya** [comment]
@StefanScherer @jdrouet. This looks like a Netlify error - https://github.com/docker/docker.github.io/pull/10431/checks?check_run_id=498505246

Could PTAL?

**Comment by StefanScherer** [comment]
Yes, a problem with Netlify
```
- CDN diffing files...
 ›   Warning: TextHTTPError: 502
 ›   Warning: 
 ›   TextHTTPError: Bad Gateway
```
I kicked off a re-run, let's see how it works.

**Comment by Dawn-Wood** [comment]
Looks great thank you @StefanScherer @usha-mandya lmk if you need anything from us.

**Comment by usha-mandya** [comment]
@StefanScherer Looks like all checks have passed. Could you approve this PR ?

**Comment by Dawn-Wood** [comment]
Hi @usha-mandya and @StefanScherer I am still not seeing the updates on docs.docker.com. Do one of you have the ability to clear the cache?

**Comment by Dawn-Wood** [comment]
never mind it's live now. Thank you both for your help today.

**Pull request merged**
