### PR TITLE
Update docker-machine completion link for BASH

### LINKED ISSUE #3700: link to docker completion file returns 404 Not found - needs update
File: [machine/completion.md](https://docs.docker.com/machine/completion/), CC @londoncalling

### PR DESCRIPTION
**Pull request by ShockN745**
This should now fix #3700

### CODE REVIEW

**Comment by mstanleyjones** [comment]
This isn't the correct fix. See discussion in #3717. Good news is that in 17.06 these scripts will be installed for you automatically, even on Linux!

**Comment by mstanleyjones** [comment]
@londoncalling can this be closed now?

**Comment by londoncalling** [comment]
@mstanleyjones  yes I think so

**Comment by londoncalling** [comment]
@ShockN745 Thank you for this PR! We ended up fixing this in some other PR's. It's a bit confusing, but as @mstanleyjones points out^^, things should get better going forward with `17.06` and beyond.

**Pull request closed without merging**
