### PR TITLE
Update macOS system requirements

### PR DESCRIPTION
**Pull request by usha-mandya**
Signed-off-by: Usha Mandya <usha.mandya@docker.com>

Update macOS system requirements to match the support indicated in Docker Desktop Stable 2.4.0.0 release

### CODE REVIEW

**Comment by usha-mandya** [comment]
@StefanScherer @nebuk89 PTAL.

**Review by StefanScherer — APPROVED** [review]
LGTM

**Comment by StefanScherer** [comment]
I've created https://github.com/docker/saas-mega/pull/5694 to update the Docker Hub page as well.

**Comment by usha-mandya** [comment]
That's great. Thanks for the Hub PR @StefanScherer.

**Pull request merged**
