### PR TITLE
Publish updates from master

### PR DESCRIPTION
**Pull request by thaJeztah**
fixes https://github.com/docker/docker.github.io/issues/13257
fixes https://github.com/docker/docker.github.io/issues/13250
fixes https://github.com/docker/docker.github.io/issues/13215
fixes https://github.com/docker/docker.github.io/issues/13202
fixes https://github.com/docker/docker.github.io/issues/13251

### CODE REVIEW

**Comment by thaJeztah** [comment]
@usha-mandya PTAL

**Comment by thaJeztah** [comment]
Oh, let me open a PR to address https://github.com/docker/docker.github.io/issues/13254 first to go with these

**Comment by thaJeztah** [comment]
opened https://github.com/docker/docker.github.io/pull/13259

**Review by usha-mandya — APPROVED** [review]
LGTM

**Pull request merged**
