### PR TITLE
Adding advisory warnings about docker-machine

### PR DESCRIPTION
**Pull request by hamiltont**
### Proposed changes

Adds advisory to docker-machine pages about maintenance - https://github.com/docker/machine/issues/4537. 

While it's reasonable that a project has to be shelved, most of the comments on that thread indicate that it's quite unreasonable there are no warnings about this in the official documentation. This PR aims to resolve that by ensuring anyone reading the docker-machine documentatin is aware of the project status and docker's recommendations 

(Note: I tried to copy @shin- comments exactly in advistory text, if there is a different official docker position please just update the advisory text as needed) 

### Related issues (optional)

https://github.com/docker/machine/issues/4537 
https://github.com/docker/machine/issues/3098 (referenced from examples/aws.md)

### CODE REVIEW

**Comment by hamiltont** [comment]
I think this is ready for merge - not sure if I should be able to pass that jenkins check or if it's just restricted to collabs

**Comment by GPPassos** [comment]
Thanks, I have just noticed that [docker-machine's manual is under superseded products and tools](https://docs.docker.com/machine/overview/), but as opposed to other products in that section, I could not find any information on what superseded docker-machine, nor why it was superseded.

**Comment by pmcneil** [comment]
might be worth a mention or changing getting started too? https://docs.docker.com/get-started/part4/

**Comment by DawnWood-Docker** [comment]
Hi @hamiltont and @GPPassos Thank you for taking the time to request these changes. You are right, the instructions were not inline with current best practices. We just updated the whole guide, including the two parts you're discussing in this pr. 
Love to hear your feedback on the updated guide--https://docs.docker.com/get-started/. 
I'm closing this pr but feel free to open another on the new guide if you find issues.

**Comment by hamiltont** [comment]
@DawnWood-Docker please reopen. If you look at the changes you'll see that the bulk of this PR was focused on the documentation for docker machine, not on the get started guide.

**Comment by DawnWood-Docker** [comment]
Ah, I see. We'll have to remove the get started updates. I'll take a look at the other files. Thanks,
Dawn

**Comment by hamiltont** [comment]
@DawnWood-Docker thanks! BTW, I've just removed the two commits that were editing the (old) getting started guide, so the PR now only targets the Docker Machine documentation

**Comment by hamiltont** [comment]
Thanks!

**Comment by usha-mandya** [comment]
@hamiltont  Apologies, we'll have to revert the PR. 

We just want to finish evaluating the overall changes with Docker's split from Enterprise over the last week before we make any decisions on where Docker Machine is in its lifecycle. We should have an update for you soon. Thanks.

**Comment by DawnWood-Docker** [comment]
Dang I'm sorry I thought that was settled.

**Comment by hamiltont** [comment]
@usha-mandya no problem. Hopefully you'll come back and tell me docker has decided to support machine (since frankly it fits better in the non-enterprise use case where you're working with a very simple system via compose and want to spin up one server not 15 and not a kube)

Please let me know if you need me to reopen the PR, or you are welcome to reopen it yourself it would just be great if someone would copy me on that new thread

**Comment by hamiltont** [comment]
@usha-mandya Please let me know if you need me to reopen a new PR while this topic is still under consideration :-)

**Comment by usha-mandya** [comment]
@hamiltont We don't need a new PR at this stage. Thanks for your patience :)

**Comment by seffyroff** [comment]
It's baffling to me that such a critical piece of tooling has been abandoned for this extended period of time whilst political nonsense plays out.  

Machine is a going concern as long as Docker is.

**Comment by ivanistheone** [comment]
@seffyroff  I was confused too by "deprecation" of docker-machine which is the most useful thing even...  It turns out now docker-machine is not needed anymore because of build-in ssh transport support. See [here](https://github.com/docker/docker.github.io/issues/9262#issuecomment-609439176).

So instead of docker-machine steps, the new procedure is something like:
 - Provision the remote host and `sudo apt-get install docker.io` (assuming Ubuntu 18.04)
 - Enable docker service to run on startup `sudo systemctl enable docker` (to start it run `sudo systemctl start docker`)
 - Add your user to docker group `sudo usermod -aG docker user`
 - On local machine `export DOCKER_HOST=ssh://user@example.com`

From my testing today seems to work just as well as before, with added benefit of not needing to open a special port.

**Pull request merged**
