### PR TITLE
Update troubleshooting guide, index and supported Kubernetes versions

### PR DESCRIPTION
**Pull request by gtardif**
This is basically a rebase of #7103 to get this merge without waiting too much, @LoreenRH being away for a while.

## Proposed changes

changed --> for → (to make them look prettier)
Troubleshooting guide for Mac & Win (mostly diagnosing from terminal)
Make the install requirements clearer for D4W
Updated the smb permission parts (has changed in last stable & edge)
added information for the switching context menu for D4W
Updated images according to latest release (18.06)
Added information for Kubernetes available in stable channel from 18.06 (both mac & windows)

### CODE REVIEW

**Comment by gtardif** [comment]
The build failed because the nginx image was not available from Hub for some time on Wednesday, needs to be restarted. 
@ahh-docker @JustinINevill anything blocking this PR (following exchanges on #7103) ?

**Comment by ahh-docker** [comment]
@gtardif Let me go over this one with @JustinINevill this week and see how we want to move forward with this.

**Comment by ahh-docker** [comment]
@gtardif Can you please refresh your branch? It looks like there's some merge conflicts that need to get resolved before we can merge.

**Comment by LoreenRH** [comment]
@ahh-docker #7103 is now without conflicts :)

**Comment by ahh-docker** [comment]
@JustinINevill Can we merge this? It looks ok to me, but want you to PTAL.

**Comment by LoreenRH** [comment]
This changes were already merged in #7103 so it's safe to close this PR. :)

**Comment by paigehargrave** [comment]
@gtardif - Hey Guillaume - can you verify the following: 1) the name of the Windows installer in docker-for-windows/install.md (has it changed from Docker for Windows Installer.exe?) and 2) in docker-for-mac/troubleshoot.md, it has this: "The diagnostics ID (here B8CF8400-47B3-4068-ADA4-3BBDCE3985D9/20180726143610) is composed of your user ID (D1F48686-F045-4708-85E3-0635B729A596)" - shouldn't the user ID be 'B8CF8400-47B3-4068-ADA4-3BBDCE3985D9'?

**Comment by paigehargrave** [comment]
These changes were already merged in #7103 - closing this PR.

**Pull request closed without merging**
