### PR TITLE
Add doc on certifying content

### PR DESCRIPTION
**Pull request by gbarr01**
- Add and edit github gist: https://github.com/docker/store-product/blob/96d9a91df8d6b3c343e847ad08e8865c93f96481/certification_docs.md

cc: @nandhini915 
cc: @KickingTheTV

### CODE REVIEW

**Comment by gbarr01** [comment]
@gforghetti , when you get a chance, please review.

**Comment by gforghetti** [comment]
@gbarr01 

My comments the documentation:

1. This link is bad -> (Docker EE running on a server you're using to verify your submission. You can get entitled to a specific Docker Enterprise Edition )[https://github.com/docker/store-product/blob/96d9a91df8d6b3c343e847ad08e8865c93f96481/pre-requisites]

2. After download the appropriate Linux inspectDockerImage command you will need to set the file permissions and make the file executable:

  ```bash
  chmod u+x inspectDockerImage
 ```

3. You should mention that if they are using a custom script to deploy a container from their image, then they must make sure that the custom startup "outputs" the container ID or container name as the last or only line of output to stdout.

4. inspectDockerLoggingPlugin - the Syntax for step 1 Download is not formatted correctly.  see screen capture below.

screen shot 2018-04-03 at 1 25 21 pm

5. After download the appropriate Linux inspectDockerLogginPlugin command you will need to set the file permissions and make the file executable:

  ```bash
  chmod u+x inspectDockerLoggingPlugin
 ```

**Comment by gbarr01** [comment]
@gforghetti , please look at my docs, not the gist.

**Comment by gbarr01** [comment]
From your feedback, only 2 and 5 apply (and I"ll make the change). But I wondered about my changes to the part on custom scripts.

**Comment by gforghetti** [comment]
I looked at the files from your pull request.

https://github.com/gbarr01/docker.github.io/blob/867792f9f98b7e634ac582b7ce5dc33647ec4c86/docker-store/certification.md

**Comment by gforghetti** [comment]
@gbarr01 

The formatting for the inspectDockerLogging plugin on this page is wrong:

screen shot 2018-04-03 at 1 55 24 pm

**Comment by gforghetti** [comment]
I don't think you needed to add this bullet below.  They are testing their docker image which they are trying to publish and certify in Docker Store.  They know what their image prefix is.  

To inspect custom Docker images, prefix the image name with the user name: ___username___/.


screen shot 2018-04-03 at 1 59 16 pm

**Comment by gforghetti** [comment]
Same applies to the inspectDockerLogging Plugin.  I don't think you needed to add this bullet below. They are testing their docker image which they are trying to publish and certify in Docker Store. It's not a "custom logging plugin".  It's their plugin that they are providing to customers in Docker Store. They know what their image prefix is.

To inspect custom Docker logging plugins, prefix the plugin name with the user name: ___username___

screen shot 2018-04-03 at 2 04 17 pm

**Comment by gforghetti** [comment]
@gbarr01 

The inspectDockerImage documentation has the same formatting problem as the inspectDockerLoggingPlugin:


screen shot 2018-04-03 at 2 11 07 pm

**Comment by gbarr01** [comment]
Thanks @gforghetti . Question:  With the exception about volumes being terminated, can the section on output be the same for both images and plugins? That is, the output methods are the same, right? stdout, json/html.

**Comment by gforghetti** [comment]
@gbarr01 

The inspectDockerImage command download table is still not formatting correctly.

screen shot 2018-04-03 at 3 16 09 pm

**Comment by gbarr01** [comment]
@gforghetti , I think the table formatting is a GitHub preview issue. All tables render properly in my build. Thanks for all the feedback.

**Comment by gbarr01** [comment]
@KickingTheTV , ready to push?

**Pull request merged**
