### PR TITLE
Login steps for another third party CI platform

### PR DESCRIPTION
**Pull request by ColinChartier**
### Proposed changes

Add link to login docs for a docker-centric CI provider

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks! Change looks good to me, but I noticed that deep-links to anchors on your website don't work (they don't focus/scroll on the right element; tried in Chrome and Safari).

I did a very quick check, and it looks like the cause for that is that not only the anchor _links_ (the links that show up when hovering over headings);

Screenshot 2020-10-08 at 09 24 20

But also the actual anchor _IDs_ are created using JavaScript.

Here's the element with JavaScript turned on:

Screenshot 2020-10-08 at 09 31 18

And with JavaScript turned off:

Screenshot 2020-10-08 at 09 30 49

The script that creates the anchor won't have executed yet when you open the page, and because of that, scrolling doesn't work.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@usha-mandya ptal

/cc @metcalfc

**Comment by thaJeztah** [comment]
@ColinChartier I /cc'd @metcalfc - I know Docker has had conversations with CI providers to design solutions / workflows for these rate limits; I wasn't sure if you / LayerCI have been in contact as well; if not, I'm sure a call can be set up.

**Comment by ColinChartier** [comment]
> Thanks! Change looks good to me, but I noticed that deep-links to anchors on your website don't work (they don't focus/scroll on the right element; tried in Chrome and Safari).
> 
> I did a very quick check, and it looks like the cause for that is that not only the anchor _links_ (the links that show up when hovering over headings);
> 
> Screenshot 2020-10-08 at 09 24 20
> 
> But also the actual anchor _IDs_ are created using JavaScript.
> 
> Here's the element with JavaScript turned on:
> 
> Screenshot 2020-10-08 at 09 31 18
> 
> And with JavaScript turned off:
> 
> Screenshot 2020-10-08 at 09 30 49
> 
> The script that creates the anchor won't have executed yet when you open the page, and because of that, scrolling doesn't work.

Thanks, we fixed SSR for the anchors, good catch.

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
