### PR TITLE
Fixing compose v3 navigation menu

### PR DESCRIPTION
**Pull request by sudo-bmitch**
Signed-off-by: Brandon Mitchell <git@bmitch.net>

### Proposed changes

Adding a menu for the compose v3 page. This appears to have been missed in PR #11744.

### Related issues (optional)

#11935

### CODE REVIEW

**Comment by sudo-bmitch** [comment]
@usha-mandya PTAL

**Review by es50678 — COMMENTED** [review]
Thanks so much for this!!!! It was totally tripping me up tonight lol.

**Comment by jinnko** [comment]
What would it take to get this merged?  It's pretty disruptive being unable to find the latest reference docs.

Looks like the problem was introduced in https://github.com/docker/docker.github.io/commit/d0f70fdbb98791037123fc2fabccf64f19add75a

**Comment by polarathene** [comment]
Just wanted to add that related docs are also having this problem. They link to `compose-file/index.md` instead of `compose-file/compose-file-v3.md`. I added a PR fix for one as an example, which mentions the current (v3) via `index.md` but also mentions v2 reference and links to that.

**Comment by MicahZoltu** [comment]
Is there a workaround while we wait for this to be merged?  The docs for docker-compose v3 being completely missing is quite problematic.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
