### PR TITLE
Update compose matrix to include Compose versions

### PR DESCRIPTION
**Pull request by andrerom**
### Proposed changes

Changes the docker compose matrix to also include the version of Docker compose where support for given file format was introduced. To avoid having to crawl true [release notes](https://github.com/docker/compose/releases) every time you wonder about this for updating your minimum requirements and so on when bumping the file format version.

### CODE REVIEW

**Comment by andrerom** [comment]
Now the only missing piece of info is what changed between the given smaller releases _(3.0 => 3.1 => 3.2 => 3.3)_, this seems complex as some fetaturs seems ot be added afterwards to given versions.

E.g from recent 1.14.0:
```
## Compose file version 2.2:
- Added the following parameters in service definitions: cpu_count,
cpu_percent, cpus
```

**Comment by mstanleyjones** [comment]
@shin- PTAL

**Comment by shin-** [comment]
See previous efforts in this direction: https://github.com/docker/docker.github.io/pull/3580

The concern to me is that people will see it as a tacit endorsement of (sometimes dramatically) older versions of the software which we no longer support.

**Comment by londoncalling** [comment]
Thanks @shin- for finding the previous thread, and clarifying that here. Let's keep this out of the docs then, as we decided before. It's sending the wrong message both per the complexities of small releases that are skated over per the comments above, and for the larger issue re: unsupported older versions.

**Comment by andrerom** [comment]
Ok, but re-phrasing what I said in the description: _As software vendor, when I bump Compose file version and need to update minimum requirements, not having this is painful_

**Comment by andrerom** [comment]
But maybe @shin- is saying what I was saying in the side note above, given certain features of a compose file version is added _(fixed, improved, forgotten)_ later, I can see why adding this can be largely misleading.

It's basically close to impossible unless you test your compose file defintion across all "supported" _(by the given software vendor)_ docker compose versions.

So I'm fine with this being closed if that is the reason.

Question is if the list of Docker versions have the same flaw, aka are there changes/fixes/improvements in a versioned file format behavior in later versions?

**Comment by londoncalling** [comment]
@shin- and/or @dnephin  can you respond to @andrerom 's last question just above ^^ ?

**Comment by dnephin** [comment]
I'm not sure I understand the question.

If there are bugs in a version of docker-compose or docker/cli, the fix could apply to all version of the Compose file supported by that tool, yes.

**Comment by andrerom** [comment]
@dnephin I was referring to these kind of changes to docker compose format support as found in docker compose v1.4.0:
```
Compose file version 2.2

- Added the following parameters in service definitions: cpu_count,
cpu_percent, cpus
```

But I don't think I have seen similar changes in later releases in docker itself, so I guess that answers my question. _(as in: no the same issue does not apply to docker versions listed here in the matrix)_

**Pull request closed without merging**
