### PR TITLE
Updated Secure Kubernetes Defaults to include local storage class

### PR DESCRIPTION
**Pull request by ollypom**
### Proposed changes

Updated Secure Kubernetes Defaults to include local storage class and provided a bit more clarification to the release notes.

### CODE REVIEW

**Comment by ollypom** [comment]
@wsong Do you mind taking a look? Thanks :)

**Comment by wsong** [comment]
Specifically, this change went out in UCP 3.1.3 and 3.0.9

**Comment by ollypom** [comment]
Thanks. I have just pushed a commit to update both the UCP 3.1.3 and 3.0.9 release notes. 

@paigehargrave @bermudezmt PTAL :)

**Comment by paigehargrave** [comment]
LGTM - @ollypom Let me know if I can help with backporting this. Thank you for your help here!

**Comment by paigehargrave** [comment]
@ollypom Thank you!

**Pull request merged**
