### PR TITLE
Fixes Critical Issue Stopping Downloads of Docker (#6910) (#7179)

### PR DESCRIPTION
**Pull request by WriteCodeEveryday**
### Proposed changes

Ensures downloads of Docker are functional for users.

### Related issues (optional)

Refer to related issue (closed by mistake, obviously)
https://github.com/docker/docker.github.io/issues/6910
https://github.com/docker/docker.github.io/issues/7179

### CODE REVIEW

**Comment by Nicnl** [comment]
LGTM.

No need to create an account to download Docker.

**Comment by WriteCodeEveryday** [comment]
There's a small issue with the CSS for primary-btn, so I'm just going to revert back to outline-btn.

**Comment by joydashy** [comment]
A very welcome feature indeed, should be merged ASAP!

**Comment by rvoortman** [comment]
Any news on when this will be merged?

**Comment by WriteCodeEveryday** [comment]
@rvoortman Not sure, ask @vieux and @#2jmorganca.

It does seem to have a lot of approvals so it shouldn't have an issue being merged.

**Comment by ahh-docker** [comment]
> It would be stylistically proper to add a space between the period and Alternatively. 😃

Please fix this and I'll merge it. Thanks!

**Comment by peterbraden** [comment]
This was reverted here: https://github.com/docker/docker.github.io/pull/7446

**Comment by MichaelSp** [comment]
Please reopen. Problem persists!

**Comment by WriteCodeEveryday** [comment]
@JustinINevill @peterbraden Why was this reverted?

**Comment by rvoortman** [comment]
This seems like a big problem to me. I've already secured a local backup in
the case my users don't want a docker login.

Op vr 5 okt. 2018 17:30 schreef Lazaro Herrera <notifications@github.com>:

**Pull request merged**
