### PR TITLE
Include CLI instructions in scale-your-cluster.md

### LINKED ISSUE #1371: Add CLI instructions for scaling UCP cluster
https://docs.docker.com/datacenter/ucp/2.0/guides/installation/scale-your-cluster/ has instructions, but doesn't tell that you can leverage the Docker CLI command for this tool.

### PR DESCRIPTION
**Pull request by wsong**
Fixes #1371

### CODE REVIEW

**Comment by joaofnfernandes** [comment]
Ups this seems to be duplicate work with #1792.

**Comment by wsong** [comment]
Should I just close this PR?

**Comment by joaofnfernandes** [comment]
Leave it be. I'll compare it against what's already merged and we can have the best of both worlds.

**Comment by joaofnfernandes** [comment]
Looks like I was wrong and the changes on this PR were not covered by #1792.
I've rebased and will merge once the tests pass.

**Pull request merged**
