### PR TITLE
Rewrites to the 'Working with Networks' topic

### PR DESCRIPTION
**Pull request by mstanleyjones**
### Describe the proposed changes

Update 'Working with networks' topic

This was because some confusion was revealed in #96, but it goes beyond the scope of that issue.
- Verify all the steps, make modifications where necessary
- Rewrite for grammar and clarity
- Add explanation for unclear sections
- Adapt some sections to a stepped tutorial style

Signed-off-by: Misty Stanley-Jones misty@docker.com
### Project version

n/a
### Related issue
#96
### Related issue or PR in another project

n/a
### Please take a look

@mrjana @stevvooe

### CODE REVIEW

**Comment by johndmulhausen** [comment]
@mstanleyjones This is a pretty old PR; can you rebase this to fix merge conflicts and so we get a Netlify preview? I can be of better use as a reviewer then. Also, ping a tech reviewer when you get a chance!

**Comment by mstanleyjones** [comment]
@thaJeztah PTAL, I think you might have looked already (did this start in `docker/docker`?) This is probably impacted by some of the other rewriting we are working on, but it would be nice to get this one in soon. I think it's a big improvement.

@johndmulhausen rebased and conflicts resolved. Netlify preview should finish shortly.

**Comment by johndmulhausen** [comment]
Deploy preview ready!

Built with commit 0fb5e646a6ece9281cef5a389d99e6c89b7d6e9b

https://deploy-preview-235--docker-docs.netlify.com

**Comment by mstanleyjones** [comment]
I've had another look at this topic and I feel pretty good merging it in. I didn't change any facts in the topic, just rewriting / restructuring, and expanding the examples that were there.

**Pull request merged**
