### PR TITLE
Remove Kitematic docs, as it's deprecated

### PR DESCRIPTION
**Pull request by thaJeztah**
Screenshot 2021-08-09 at 12 57 24

### CODE REVIEW

**Comment by usha-mandya** [comment]
Thanks @thaJeztah. Should we add the Kitematic deprecation notice in the Desktop release notes?

**Comment by thaJeztah** [comment]
> Thanks @thaJeztah. Should we add the Kitematic deprecation notice in the Desktop release notes?

Hmm... good one; I think it's been removed for some time now (would have to check which release removed it?) I see [DESKTOP-1736] was related to removing it from the menu, but not sure which release that was, and if there's other bits removing it in later releases. @mat007 do you know?

**Comment by mat007** [comment]
Kitematic was removed from Desktop ages ago, I think it’s too late to release note it 😁

**Review by usha-mandya — APPROVED** [review]
LGTM

**Pull request merged**
