### PR TITLE
WIP: Test netlify

### PR DESCRIPTION
**Pull request by StefanScherer**
This PR is only to test netlify integration to have preview builds for each pull request.

### CODE REVIEW

**Comment by usha-mandya** [comment]
@StefanScherer Looks like the Netlify commit message is working. The recent PRs have a specific commit message from the Netlify bot. Could you check?

**Comment by StefanScherer** [comment]
@usha I've added another two notifications, now the `netlify/docsdocker/deploy-preview` build is green and no longer pending.
I'll close this test PR now.

**Comment by usha-mandya** [comment]
@StefanScherer The build check for Netlify Preview still shows that the deploy is pending even after a successful deploy. Not sure if it's just me?

image

**Comment by StefanScherer** [comment]
@usha which PR is that? It doesn't automatically fix all pending states in existing PR's. After I added two further notifications in Netlify configuration, I also rebased this PR and pushed it again. And after that it went to green for this PR.

**Comment by usha-mandya** [comment]
Aah OK. I see the `Pending — Deploy preview processing` status in the existing PRs.

**Pull request closed without merging**
