### PR TITLE
update dotnet data

### PR DESCRIPTION
**Pull request by MohamedLEGH**
aspnet core image is depreciated
need to use dotnet:2.1-sdk image to build aspnet app
and dotnet:2.1-aspnetcore-runtime to run them

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks for contributing; looks like this PR will conflict with https://github.com/docker/docker.github.io/pull/7033 (once that's merged); let's resolve merge-conflicts after that one goes in 👍

**Comment by MohamedLEGH** [comment]
I don't see the conflict. #7033 modifies the file

>  engine/examples/dotnetcore.md 

not the file 

> compose/aspnet-mssql-compose.md

**Comment by bermudezmt** [comment]
@MohamedLEGH @thaJeztah can we safely update this to the latest tag, `3.0-sdk`?

**Comment by TravisEz13** [comment]
This needs to be fixed in MCR and the repo is private.  I'm at dockerCon but ping me Monday and I'll forward this to the correct place.

**Comment by bermudezmt** [comment]
@TravisEz13 very nice meeting you at DockerCon! I guess my follow-up questions on this PR are: 

1. Did Microsoft move `dotnet:2.1-sdk` to https://hub.docker.com/_/microsoft-dotnet-core? 
2. Is https://hub.docker.com/_/microsoft-dotnet-core-sdk/ now the right Hub repository and can we safely update the instructions here to use the `2.2` tag? I see `2.1` has LTS.

Thanks in advance for your help!

**Comment by TravisEz13** [comment]
cc @michaelsimons from the DotNet team to verify.

I believe `hub.docker.com/_/microsoft-dotnet-core-sdk` is the current location for the SDK images.

**Comment by bermudezmt** [comment]
Thank you so much for your input, @TravisEz13 and @MichaelSimons . I've added this to my backlog for tech review and hope to get this merged soon.

**Comment by bermudezmt** [comment]
@DawnWood-Docker or @adrian-plata can one of you do a tech review of this PR? I've updated it to reflect the new Microsoft URLs. Unfortunately, this PR has been in purgatory for too long.

**Comment by adrian-plata** [comment]
I just ran through the preview and everything worked.

**Comment by adrian-plata** [comment]
Actually, I had to change the docker-compose.yml version to "2.0", so we may want to indicate that if they receive an error as to which yml file is supported, they may have to change it.

**Comment by bermudezmt** [comment]
You are awesome, @adrian-plata. Please go ahead and merge after you've added that note. Thank you!

**Comment by DawnWood-Docker** [comment]
Hey @adrian-plata You probably saw this already but there is a merge conflict that needs to be resolved before you can merge.

**Comment by thaJeztah** [comment]
> Actually, I had to change the docker-compose.yml version to "2.0", so we may want to indicate that if they receive an error as to which yml file is supported, they may have to change it.

@adrian-plata do you recall what error you received? The `3.0` compose format should be compatible with current versions of Docker, so wondering about that error.

**Comment by adrian-plata** [comment]
@thaJeztah here's the error

`$ docker-compose build
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
`

**Pull request merged**
