### PR TITLE
add sctp docs

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

### Proposed changes

part of https://github.com/docker/docker.github.io/issues/6039

@thaJeztah @ishidawataru 

### Unreleased project version (optional)

18.03

### Related issues (optional)

https://github.com/docker/docker.github.io/issues/6039
https://github.com/docker/cli/pull/900

### CODE REVIEW

**Comment by thaJeztah** [comment]
oh, can you open this against the `vnext-engine` branch? https://github.com/docker/docker.github.io/tree/vnext-engine That way it'll go out when 18.03 is released, and not before that 🤗

**Comment by AkihiroSuda** [comment]
done

**Comment by gbarr01** [comment]
Thanks for all the work here @AkihiroSuda  .... but I have some concerns. @thaJeztah @joaofnfernandes, questions:

- The changes to `_config.yml` are already out of date. I think only Docs should edit this file?
- Should't the YAML be edited on the docker-ce or docker-cli side? Because next Tuesday, I am going to clobber all the YAML files with those from docker-ce. So all of these changes will be clobbered. 

Thoughts?

**Comment by joaofnfernandes** [comment]
Oh... I think @AkihiroSuda updated the PR to be against `vnext-engine` but didn't rebase. That's why there are so many commits in this PR. Rebasing your branch to `vnext-engine` and pushing should solve all the conflicts and there are no changes to `_config.yml`.

**Comment by AkihiroSuda** [comment]
rebased

**Pull request merged**
