### PR TITLE
added Toolbox, Windows 7/8 to node setup

### PR DESCRIPTION
**Pull request by londoncalling**
### What changed

- added Docker Toolbox links and info to "Got Docker" topics on sample app overview, and to Node Setup to cover Windows 7, 8 users

- added a new section on creating machines using `virtualbox` driver for Windows 7, 8 users

### Related PR

#2301  (the current PR will supersede this one)

### Reviewers, fyi

@fredyagomez @friism @mstanleyjones 

Signed-off-by: Victoria Bialas <victoria.bialas@docker.com>

### CODE REVIEW

**Comment by londoncalling** [comment]
LGTM

**Comment by fredyagomez** [comment]
Looks pretty cool. This is my first pull request ever and got accepted 👍

**Comment by londoncalling** [comment]
Well you did a great service to Windows users! :-) Thanks! 🏆

**Comment by fredyagomez** [comment]
Wait wait wait. I am now a Mac User :)  I just happened to test it in a Windows machine.

**Comment by fredyagomez** [comment]
I sorry I misread your comment. Yes, hopefully this save some time for Windows users in the future.

**Comment by londoncalling** [comment]
@freddyagomez well your feedback helped both Mac and Windows users because it made the whole workflow clearer. For your next PR, if you create a separate branch on your GitHub fork for it, we will have an easier time contributing/collaborating on it if we need to, and then we can just merge your PR. Regarding the sample app workflow, I know the install / setup for the different OS's is a pain. I work on both Mac and Windows to test, and I get it.  Our goal is to create new or add to this sample a demo of creating the nodes in Docker Cloud or your Cloud provider as an alternative to using local nodes. But anyway, you really improved the documentation. Look forward to more feedback and hearing about your experience with Mac or Windows.

**Pull request merged**
