### PR TITLE
[17.12] Added documentation for fluentd plugin sub-second-precision flag.

### LINKED ISSUE #5425: Add documentation for fluentd-sub-second-precision flag in fluentd plugin docs.
**Description**
Recently I have added fluentd-sub-second-precision to fluentd plugin through this [PR](https://github.com/moby/moby/pull/35529). Also I have autocomplete cammand for the same through this (PR)[https://github.com/docker/cli/pull/724]. 

**Solution**
So the  https://github.com/docker/docker.github.i/blob/8896e88867202a2dda926adadb6a4a350fd10165/engine/admin/logging/fluentd.md#options page needs to be updated with support for fluentd-sub-second-precision flag description.

**Team**
area/engine

**P.S**
I have my [PR](https://github.com/docker/docker.github.io/pull/5428) ready for this just need a confirmation from docker documentation team.

### PR DESCRIPTION
**Pull request by dungeonmaster18**
### Proposed changes
Add documentaion for fluentd-sub-second-precision flag in fluentd plugin.

Added a short description for fluentd-sub-second-precision flag in fluentd.md.

### Unreleased project version (optional)
Not sure.

**Team**
area/engine

### Related issues (optional)
Closes #5425

### CODE REVIEW

**Comment by anusha-ragunathan** [comment]
LGTM

**Comment by anusha-ragunathan** [comment]
cc @thaJeztah

**Comment by joaofnfernandes** [comment]
LGTM, we just need moby/moby#35529 to get merged before merging the docs.

**Comment by dungeonmaster18** [comment]
[moby/moby#35529](https://github.com/moby/moby/pull/35529) was merged, so we can merge this 👍

cc @joaofnfernandes @thaJeztah

**Comment by thaJeztah** [comment]
@joaofnfernandes I noticed this is against `master`, but will be in the upcoming 17.12 release, so we should merge after release (or reopen against `vnext-engine` - let me know what you prefer

**Comment by joaofnfernandes** [comment]
I think `vnext-engine` makes more sense. @dungeonmaster18 can you update this PR to be against the `vnext-engine` branch instead of `master`?

**Comment by dungeonmaster18** [comment]
Yup sure.

**Comment by dungeonmaster18** [comment]
@joaofnfernandes I have update

**Comment by joaofnfernandes** [comment]
@dungeonmaster18 it seems that you have some conflicts in your PR. Can you rebase your branch on `vnext-engine`? If that's too much work, you can start a new branch from `vnext-engine` and submit a new PR instead.

**Comment by dungeonmaster18** [comment]
closing this and opening new pr #5471 

cc @joaofnfernandes

**Pull request closed without merging**
