### PR TITLE
Update create-pr.md

### PR DESCRIPTION
**Pull request by scjane**

### CODE REVIEW

**Comment by johndmulhausen** [comment]
Actually, it's correct as-is in this case!

**Comment by scjane** [comment]
@johndmulhausen Thank you for reviewing it. I searched the topic about this, the Grammar Girl tells me the answer:
quotationmark

Get it!

**Comment by johndmulhausen** [comment]
@scjane Learn something every day, huh? Thanks for the PR!

**Comment by scjane** [comment]
@johndmulhausen Try to make progress every day🐾

**Pull request closed without merging**
