### PR TITLE
Update ucp-configuration-file.md

### PR DESCRIPTION
**Pull request by traci-morrison**
This update is per ENGDOCS-15:  https://docker.atlassian.net/browse/ENGDOCS-15

@DawnWood-Docker Dawn, can you please review this PR? Thanks. Also, can you help me determine which labels (if any) that I need to add?

### CODE REVIEW

**Comment by traci-morrison** [comment]
@goksu PTAL.

**Comment by ollypom** [comment]
@traci-morrison @DawnWood-Docker Worth noting that this one is not a GA feature yet. Might be worth moving to docs-private?

**Comment by DawnWood-Docker** [comment]
@ollypom we were just discussing workflow. :)

**Comment by traci-morrison** [comment]
> @traci-morrison @DawnWood-Docker Worth noting that this one is not a GA feature yet. Might be worth moving to docs-private?

Great point. I will work with Dawn to get this moved to the right repo.

**Comment by goksu** [comment]
Yes, as I've mentioned this work will be part of the August patch.

**Pull request closed without merging**
