### PR TITLE
Fixes #6772

### LINKED ISSUE #6772: I found a broken link
At the bottom of https://docs.docker.com/install/linux/docker-ce/debian/ under "Next steps" there is a link to the "user guide" which leads to this page: https://docs.docker.com/engine/userguide/index.md which apparently does not exist.

### PR DESCRIPTION
**Pull request by moreal**
Edit User Guide url from /config/daemon to /get-started

### CODE REVIEW

**Comment by ahh-docker** [comment]
@moreal When checking the changes, I get a 404. I cannot merge it. Please fix and resubmit.

**Comment by moreal** [comment]
@ahh-docker
I am waiting for your help

**Comment by moreal** [comment]
@ahh-docker 

Please check this pr

**Comment by paigehargrave** [comment]
@moreal - Thank you for bringing this to our attention. We apologize for the delay on getting this fixed. We believe that this has been fixed in https://github.com/docker/docker.github.io/pull/8106. Please review the updates and let us know if this has been resolved to your satisfaction. Thank you!

**Comment by moreal** [comment]
Thank you for letting me know that
I checked the changes and the links are working as well
It looks like good! Also I think it was better to specify the filename like (`/get-started/index.md`).
Anyway, thank you @paigehargrave

**Comment by paigehargrave** [comment]
@moreal - Thank you for checking and for your patience with this!

**Pull request closed without merging**
