### PR TITLE
Doc update to support standard AWS credential loading.

### PR DESCRIPTION
**Pull request by mrburrito**
Docs changes from machine PR https://github.com/docker/machine/pull/3799

Signed-off-by: Gordon Shankman <gshankman@gmail.com>

### CODE REVIEW

**Comment by londoncalling** [comment]
@nathanleclaire @mrburrito LGTM! merging

**Comment by londoncalling** [comment]
@mrburrito @nathanleclaire these AWS docs changes are live now: https://docs.docker.com/machine/drivers/aws/

(Let me know if they should not be! i.e., if they aren't valid yet for currently available binaries .. we need to figure out a process for this .. hopefully it was ok to publish these particular changes)

**Comment by mrburrito** [comment]
@londoncalling the PRs on the machine project haven't been merged yet. Might be better to back these out until those are closed. I think the AWS credentials are closer to being merged than the userdata update.

**Comment by londoncalling** [comment]
Thanks! Sorry about that .  We talked about  creating a v-next milestone on
the docs side for these situations . I'll work it out with Nathan and John
today .

**Comment by nathanleclaire** [comment]
@londoncalling They are for new features which won't be included until 0.9.0 :( They should not be live

**Comment by nathanleclaire** [comment]
I think it needs to be opened as PR to `vnext-machine` branch

**Pull request merged**
