### PR TITLE
Update README.md

### LINKED ISSUE #6247: docs.docker.com pages are missing "edit" and "file an issue" links.
### Problem description

The readme for this documentation repo states "We really want your feedback, and we've made it easy. You can edit, rate, or file an issue at the bottom of every page on https://docs.docker.com/."  However, all pages I looked at only had the ability to rate, not edit nor file an issue.  (See attachment)

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/reference/builder/#dockerfile-examples

### Project version(s) affected

Docker version 17.12 docs.  

### Suggestions for a fix

Either add the Edit and File An Issue buttons to the doc pages (preferred), or remove the statement from the readme.  

### Attachments

doc

### PR DESCRIPTION
**Pull request by cowlinator**
### Proposed changes

Fixed Readme's description of where to edit documentation

### Related issues (optional)

Fixes #6247

### CODE REVIEW

**Comment by gbarr01** [comment]
Hi, @cowlinator , what was wrong with the original?

**Comment by thaJeztah** [comment]
@gbarr01 the edit links were moved from the bottom to the right hand side :blush:

**Comment by gbarr01** [comment]
Ah. Okay, thatnks, @thaJeztah

**Comment by joaofnfernandes** [comment]
Then let's ship it!

**Pull request merged**
