### PR TITLE
Update bundles.md

### PR DESCRIPTION
**Pull request by scjane**

### CODE REVIEW

**Comment by mstanleyjones** [comment]
Are you on the community slack? I'd love to chat with you some time and show you how to bundle a bunch of these PRs together into fewer, larger ones. We really appreciate all of the help you are giving us. Multiple PRs kick off multiple Netlify builds, and when they are merged, they each set off builds on Docker Cloud, which need to be run serially. It would be a lot more efficient if you could bundle up a TYPE of change (such as adding commas or fixing heading titles) into a single larger commit that could be reviewed and merged as one unit of work. It is not difficult but will involve cloning the repo and using a local Git client (command line or GUI).

**Comment by scjane** [comment]
@mstanleyjones Wow, I'd love to learn it.

**Comment by mstanleyjones** [comment]
Let me know when and how you'd like to meet / chat, and I can walk you through it.

**Comment by scjane** [comment]
@mstanleyjones What about the next week? I'm a little busy these days. I"ll be free the next week, from 8:30 AM to 19:00 PM (Beijing time) each day. And, can we arrange a Webex meeting for it? Thanks.

**Comment by mstanleyjones** [comment]
Sure, Webex or if you can jump on the Docker Community slack (dockercommunity.slack.com), that would be fine. Just ping me (`@misty`) when you are available.

**Pull request closed without merging**
