### PR TITLE
Doc change to support custom userdata option for docker-machine AWS driver

### PR DESCRIPTION
**Pull request by mrburrito**
Migrating docs changes from machine PR https://github.com/docker/machine/pull/3779

Signed-off-by: Gordon Shankman <gshankman@gmail.com>

### CODE REVIEW

**Comment by londoncalling** [comment]
LGTM!

**Comment by nathanleclaire** [comment]
Hey @londoncalling, it seems this should actually be on the `vnext-machine` branch.

**Comment by nathanleclaire** [comment]
It will need to be reverted as this feature does not exist in machine release yet.

**Comment by londoncalling** [comment]
Hey Nathan, I've been gone for a week, I'm back in tomorrow - will have a
look and change it. Thanks !

**Comment by londoncalling** [comment]
👍

**Comment by nathanleclaire** [comment]
Thanks!

**Pull request merged**
