### PR TITLE
Pull docker refs from git

### PR DESCRIPTION
**Pull request by mstanleyjones**
### Describe the proposed changes

Remove `docker/docker` ref docs, plugin docs, and `deprecated.md` from docker.github.io source
Modify Dockerfile to pull these files/folders from the `docker/docker` repo instead
Modify the NOT_EDITED_HERE manifest to stop referring to these files / folders

### Unreleased project version

n/a

### Related issue

n/a

### Related issue or PR in another project

n/a

### Please take a look

@johndmulhausen I'm not sure exactly how to test this Can you sanity-check it?
cc/  @thaJeztah  @dnephin

### CODE REVIEW

**Comment by johndmulhausen** [comment]
Deploy preview processing.

Built with commit ef59853fab59666af75a4e4d8b6f89628b1ef880

https://app.netlify.com/sites/docker-docs/deploys/5823abc4668674692d54d8eb

**Comment by mstanleyjones** [comment]
@johndmulhausen @thaJeztah this is ready to go. We did some testing locally and verified that it works.

This is just for `engine`, and will need to be done separately for the others.

**Comment by mstanleyjones** [comment]
cc/ @dnephin

**Comment by johndmulhausen** [comment]
@dnephin @thaJeztah I just want to be really sure that this is necessary before we pull the trigger. You have said that after a version ships, that the reference docs for that engine version are "dead" and that nobody is editing the v1.12 docs over in docker/docker at this point, correct?

**Comment by thaJeztah** [comment]
> You have said that after a version ships, the reference docs for that engine version are "dead" and that nobody is editing the v1.12 docs over in docker/docker at this point, correct?

Changes are made by cherry-picking fixes from the master branch into the 1.12.x branch. That way, we don't  "maintain" two separate versions, but can incorporate changes in to the "current" docs (so are able to update documentation between releases).

**Comment by mstanleyjones** [comment]
Rebased to address conflicts. I think this is ready to go. Agree, @johndmulhausen ?

**Comment by mstanleyjones** [comment]
Argh let me rebase again.

**Comment by mstanleyjones** [comment]
@johndmulhausen I think this is ready (again)...

**Comment by johndmulhausen** [comment]
Alright, pulling this in after discussion w/ @mstanleyjones. Thanks, all!

**Pull request merged**
