### PR TITLE
Add examples to CLI generation templates

### PR DESCRIPTION
**Pull request by mstanleyjones**
### Proposed changes

Add the examples for the CLI commands into the CLI-generation templates until they can be included as part of the YAML. Workaround as discussed with @johndmulhausen until the examples can be shipped to us in the YAML. cc/ @FrenchBen @dnephin 

### Unreleased project version (optional)

Engine 1.13

### CODE REVIEW

**Comment by dnephin** [comment]
Where can I find the code that generates the the yaml for the cli reference?

**Comment by mstanleyjones** [comment]
cc @FrenchBen

**Comment by FrenchBen** [comment]
@dnephin Code is currently here:
https://github.com/FrenchBen/docker/blob/generate-cli-reference/docs/gen/generate.go#L48

Now that your changes have been merged, I can make a PR against docker/docker, but need to possibly add `dockerd` CLI beforehand.

**Comment by mstanleyjones** [comment]
Fixed all the problems and the netlify preview looks great. See https://deploy-preview-1069--docker-docs-vnext-engine.netlify.com/engine/reference/commandline/run/. I'll merge this for now and we can revert it later when the examples are part of the YAML.

**Pull request merged**
