### PR TITLE
Automatically generate Engine API documentation

### PR DESCRIPTION
**Pull request by bfirsh**
I have replaced the Engine API docs with a version that is automatically generated from a Swagger definition, using [ReDoc](https://github.com/Rebilly/ReDoc). It looks a bit like this:

screenshot 2016-11-16 18 11 40

I have also reorganised the menu for the Engine API to make it simpler and clearer:

screenshot 2016-11-16 21 29 18

Before, it was under "reference", even though some of it wasn't reference material, and it also seemed quite hidden that deep in the menu tree.

I've done a few other things, too:

- Tidied up some URLs (removed superfluous words, `s/_/-/`, etc)
- Moved the accounts API documentation the Docker Hub section. It makes more sense here than the Engine reference, I think – the Hub _serves_ the API, the Engine _consumes_ it.
- Rename Remote API to Engine API. See https://github.com/docker/docker/issues/28319 for details.

### Known issues

- ReDoc is a client-side app that takes a bit of time to load. [The author is working on a fix](https://github.com/Rebilly/ReDoc/issues/62) and I think the downside of this outweighs the benefit of _much_ better documentation.

### Related issues

- This vendors swagger.yaml from this Engine change: https://github.com/docker/docker/pull/28506. It would probably be worth waiting until that is merged so we can be sure we're vendoring the correct thing.
- This is a subset of #210. Just the API docs, and none of the additional SDK docs. As discussed with @johndmulhausen, this seemed like a much less controversial subset that we could get in to start with.
- Background on Swagger definition: https://github.com/docker/docker/issues/27919
- Closes https://github.com/docker/docker/issues/22931

/cc @dnephin @johndmulhausen

### CODE REVIEW

**Comment by johndmulhausen** [comment]
Deploy preview ready!

Built with commit 508001e085f10457f919ef14cadddbd4c1f633fe

https://deploy-preview-606--docker-docs.netlify.com

**Comment by sanscontext** [comment]
Noting an offline discussion: the `accounts` apis touch more than Hub, currently in discussion about where they ought to go. :)

**Comment by johndmulhausen** [comment]
@sanscontext @mstanleyjones @londoncalling @joaofnfernandes 

The most relevant staging URL is here: 
https://deploy-preview-606--docker-docs.netlify.com/engine/api/v1.25/

Be aware that this PR also changes "Remote API" to "Engine API" so make sure any find/replaces were done right

**Comment by johndmulhausen** [comment]
@bfirsh Can you make the links to API versions relative instead of https://docs.docker.com ? That way they'll show the version that is shipping with that branch/fork/clone of the docs

https://deploy-preview-606--docker-docs.netlify.com/engine/api/v1.25/#section/Versioning

Clicking on these now, you can see that they 404

**Comment by johndmulhausen** [comment]
Other than that, this LGTM!

**Comment by sanscontext** [comment]
Can we hold off on merge until I've got a Docker ID stub in place to rehome the Hub docs?

**Comment by sanscontext** [comment]
Please hold off until #634 has merged.

**Comment by bfirsh** [comment]
@johndmulhausen Okay. That was intentional so the swagger.yaml would work standalone, but I guess it's not the end of the world making the intro description just work inside the documentation.

**Comment by johndmulhausen** [comment]
@bfirsh Belay my comment then; I get it.

**Comment by johndmulhausen** [comment]
@sanscontext I think the correct order is that we merge this PR first and your PR adapts. You only have one link in your PR that is affected here; I left a comment with the URL that will need to change.

**Comment by johndmulhausen** [comment]
@bfirsh PR #634 has been merged and it makes sense to have the Accounts API reference live under `/docker-id/` -- can you update this PR?

**Comment by bfirsh** [comment]
Due to #511, we're now going to have to wait for docker/docker#28506 to make its way into the 1.12 branch. I will push this along. :)

**Comment by bfirsh** [comment]
docker/docker#28506 is now merged. :tada:

I'll wait for #674 before updating this PR.

**Comment by bfirsh** [comment]
@mstanleyjones @johndmulhausen This is also just for Docker 1.13, so presumably I should open it against the branch `vnext-engine`? Will #674 be cherry-picked into that branch?

**Comment by bfirsh** [comment]
Okay, I have now implemented this PR on top of #511 and #674. The implementation is ready for review, apart from the hacks in `Dockerfile` to pull from the correct Docker version.

Once #511 and #674 have made their way into the `vnext-engine` branch, I can switch this PR to that branch and it should be ready to merge.

**Comment by johndmulhausen** [comment]
@bfirsh Everything in `master` will be merged into `vnext-engine` so yes, #511 and every other fix that's happened here will be pulled in. :) As for which branch to open *this* PR against, yes -- if it's for v1.13 only, you want to do that against `vnext-engine`. Which means you *might* have to create a new PR for this.

**Comment by bfirsh** [comment]
Looks like #734 includes #511 and #674, so I will wait for that before switching branches.

And yes – this is v1.13 only.

**Comment by mstanleyjones** [comment]
You'll now want to look at #756, though that's only there for audit purposes. If @thaJeztah approves it I will force-push `vnext-engine` to that state, which is the 21 patches in `vnext-engine` rebased on `master`. It's ugly, but trying to do a merge was too complicated.

**Comment by johndmulhausen** [comment]
@bfirsh Where are we on this? Do you plan to shut this PR down and make a new one pointed at `vnext-engine`? According to the Netlify staging, ReDoc isn't getting a swagger spec anymore

**Comment by bfirsh** [comment]
@johndmulhausen Yep! Just waiting for `vnext-engine` to be rebased and I'll sort it out.

**Comment by mstanleyjones** [comment]
@bfirsh this should be good to go after you rebase on current `vnext-engine` to resolve the conflict. I did the force-push this morning.

**Comment by johndmulhausen** [comment]
@bfirsh Have at it! Exciting times. :) Right now I'm seeing this error in your PR though: 

https://deploy-preview-606--docker-docs.netlify.com/engine/api/v1.25/

**Comment by johndmulhausen** [comment]
bitmoji

**Comment by bfirsh** [comment]
Oh nice - thanks! Glad that just worked. 💃

**Pull request merged**
