### PR TITLE
add Linode to AVAILABLE_DRIVER_PLUGINS.md

### PR DESCRIPTION
**Pull request by displague**
### Proposed changes

I am a developer at Linode responsible for the **https://github.com/linode/docker-machine-driver-linode** driver. 

I would like to get this driver listed in `AVAILABLE_DRIVER_PLUGINS.md` and the [machine/drivers](https://docs.docker.com/machine/drivers/) index, for more visibility.

### Related issues (optional)

- https://github.com/docker/machine/pull/268

### CODE REVIEW

**Comment by al45tair** [comment]
This pull request needs updating, as the code has been moved to 
https://github.com/linode already.

**Comment by displague** [comment]
Rebased and added the Linode driver to https://docs.docker.com/machine/drivers/

**Comment by displague** [comment]
Is there still a way to get listed on the Volume Plugins page? https://docs.docker.com/engine/extend/legacy_plugins/#volume-plugins

**Comment by bermudezmt** [comment]
Hey @displague - sorry this took a while. Let me follow up on the Engine plugins question, but this PR is good to go. Thank you for your contribution! cc: @usha-mandya

**Pull request merged**
