### PR TITLE
Various cleanup in template, and improvements to 404 page

### PR DESCRIPTION
**Pull request by thaJeztah**
See individual commits for details

### CODE REVIEW

**Comment by thaJeztah** [comment]
@usha-mandya @StefanScherer ptal

**Review by usha-mandya — APPROVED** [review]
SGTM. Thanks

**Review by StefanScherer — APPROVED** [review]
LGTM
The improved 404 issue creation link is very useful!

**Comment by thaJeztah** [comment]
> The improved 404 issue creation link is very useful!

Yes, I initially just wanted to move the script, then thought about what me bothered all the time "I found a broken link" issues; well, they basically reported _"I (somehow) arrived on an URL that doesn't exist"_.

Nothing we can do about those unless we know why they arrived there (did it ever exist? did they make a typo when entering the URL? did someone write a blog-post and made a typo? did we forget to update a link or add a redirect?)

**Pull request merged**
