### PR TITLE
Add release notes for Docker Desktop 4.1.1

### PR DESCRIPTION
**Pull request by mat007**
### Proposed changes

Adds release notes for Docker Desktop 4.1.1

### CODE REVIEW

**Comment by thaJeztah** [comment]
@mat007 this needs a rebase, because we moved the `release-notes.md` to `release-notes/index.md` (as part of https://github.com/docker/docker.github.io/pull/13450); let me know if you want me to do so for you

**Comment by mat007** [comment]
@usha-mandya @thaJeztah we discussed adding the checksums for the installers, do you have any suggestion as to how we would want to display them?

**Comment by mat007** [comment]
I was thinking something simple, such as writing the md5 hash underneath or next to the download link. 😄

**Comment by usha-mandya** [comment]
Yea, I was thinking of a simple table with the filename, download URL and Sha256

**Pull request merged**
