### PR TITLE
Update Desktop FAQ, remove info on Service accounts

### PR DESCRIPTION
**Pull request by usha-mandya**
Update Desktop FAQ, remove info on Service accounts

### CODE REVIEW

**Review by jerae-duffin — DISMISSED** [review]
LGTM!

**Comment by thaJeztah** [comment]
do we need a redirect for the URL?

**Comment by usha-mandya** [comment]
Good point. Added a redirect :)

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
