### PR TITLE
Adds style for warnings and notes

### PR DESCRIPTION
**Pull request by joaofnfernandes**
This PR adds a way for us to have warnings and notes.

screen shot 2017-04-11 at 14 41 23

It also maintains backwards compatibility with the older note style so that we can start migrating slowly (the first note in the screenshot).

### CODE REVIEW

**Comment by johndmulhausen** [comment]
This is great! Can you do a gold/caution variant for "Be Careful" messages?

**Comment by joaofnfernandes** [comment]
I'd prefer to have just two colors, for the reasons pointed in #2563, but we can create 3 colors and. @jsouth what hex colors should we use for these banners? We need colors for:

* info
* caution
* warning

Right now I'm using the colors of the bootstrap docs but I'd prefer if we had our own colors.

**Comment by joaofnfernandes** [comment]
Now we have 3 colors. You can use regular blockquotes for the default blue, or add the class `warning` for yellow/brown, or `danger` for red.

**Comment by jsouth** [comment]
@joaofnfernandes - I'll collect these intent colors today and post here :)

**Comment by joaofnfernandes** [comment]
Merging. We can iterate the colors of a new PR.

**Pull request merged**
