### PR TITLE
Update screenshots to 3.2

### PR DESCRIPTION
**Pull request by traci-morrison**
### Proposed changes

Updating the screenshots to UCP 3.2

### Related issues (optional)
https://docker.atlassian.net/browse/ENGDOCS-104

### CODE REVIEW

**Comment by thaJeztah** [comment]
If we can _replace_ the old images instead of adding new ones, that would indeed be great.

I can do a quick check if these images can be losslessly optimised to bring down the size (and prevent the repository size from ballooning)

**Comment by thaJeztah** [comment]
Optimized images are ~40% smaller (lossless, so no quality change);


Screenshot 2019-09-05 at 19 20 58

Attached; 

[optimized.zip](https://github.com/docker/docker.github.io/files/3580476/optimized.zip)


If you could replace the images in your PR (make sure to squash changes in a single commit, otherwise they still end up in git's history and take up space)

**Comment by traci-morrison** [comment]
> If we can _replace_ the old images instead of adding new ones, that would indeed be great.
> 
> I can do a quick check if these images can be losslessly optimised to bring down the size (and prevent the repository size from ballooning)

@thaJeztah The old images are used in the 2.1, 2.2, and 3.1 guides. The images I am replacing are specific for 3.2. What is the best action in this scenario? Thanks.

**Comment by ollypom** [comment]
Hey @traci-morrison , that one is not correct, as part of the archiving process the images get copied and moved with the corresponding guides into the relevant releases folder. https://github.com/docker/docker.github.io/blob/master/ee/ucp/images/monitor-ucp-0.png is only used by UCP 3.2 documentation :) 

UCP 3.1 - https://github.com/docker/docker.github.io/blob/master/datacenter/ucp/3.1/guides/images/monitor-ucp-0.png 
UCP 3.0 - https://github.com/docker/docker.github.io/blob/master/datacenter/ucp/3.0/guides/images/monitor-ucp-0.png
UCP 2.2 - https://github.com/docker/docker.github.io/blob/master/datacenter/ucp/2.2/guides/images/monitor-ucp-0.png
UCP 2.1 - https://github.com/docker/docker.github.io/blob/master/datacenter/ucp/2.1/guides/images/monitor-ucp-0.png

**Comment by traci-morrison** [comment]
@ollypom Thanks for that information. I replaced the images with the ones from @thaJeztah. Do you want to take another look before I merge this PR?

**Comment by ollypom** [comment]
Greats Thanks! Final nit :D Do you mind cleaning up the old images, or renaming your new images to the same name as the older images?

**Comment by traci-morrison** [comment]
> Greats Thanks! Final nit :D Do you mind cleaning up the old images, or renaming your new images to the same name as the older images?

@ollypom  Sure. Can you review to make sure things are correct? Thanks.

**Pull request merged**
