### PR TITLE
add desc for system events [Fix #2025]

### LINKED ISSUE #2025: Missing Extended Description for system events
Extended description of the command for `docker system events` is not copied over from https://docs.docker.com/engine/reference/commandline/events/ to https://docs.docker.com/engine/reference/commandline/system_events/.

This is very useful information and should be copied over.

### PR DESCRIPTION
**Pull request by michaelspets**
### Proposed changes

Add extended description for system events

### Related issues (optional)
Fixes #2025

### CODE REVIEW

**Comment by mstanleyjones** [comment]
Hi there! This is a bit tricky. Your fix is great, but these files are actually generated by a command run against the https://github.com/moby/moby repository. To update this, you need to raise a pull request there to change the strings in the actual code. Here is the file you would need to edit: https://github.com/moby/moby/blob/master/cli/command/system/inspect.go

Be sure you read the contribution guidelines in that repository before submitting the pull request. Of particular note is that you need to sign your changes in that repository (by using `git commit -s -m 
 "commit message"`.

**Comment by mstanleyjones** [comment]
@michaelspets do you think you can submit this change to the upstream code repo? It would be really great! I can replicate it there if you would prefer.

**Comment by jmaitrehenry** [comment]
I could make the PR in moby repository, and keep the point to @michaelspets :)

**Comment by michaelspets** [comment]
I don't know what to do exaclty... I understand that this code has to be in moby/moby repo but I can't understand whether I have to generate the doc from source code or to edit the corresponding md file.

@mstanleyjones please help...

**Comment by jmaitrehenry** [comment]
I think it's this file: https://github.com/moby/moby/blob/master/docs/reference/commandline/system.md

**Comment by michaelspets** [comment]
ok @jmaitrehenry thank you. I 'll give it a try...

**Comment by jmaitrehenry** [comment]
If you need any help, you can ping us on Slack #docs channel

**Comment by jmaitrehenry** [comment]
@mstanleyjones As the PR was now created in moby/moby, we can close this one.

**Pull request closed without merging**
