### PR TITLE
Removing additional steps not needed for UCP 3.1 on Azure

### PR DESCRIPTION
**Pull request by david-yu**
Removing for Azure on UCP 3.1

### CODE REVIEW

**Comment by yongshin** [comment]
cc @abhi let me know if this looks good

**Comment by abhi** [comment]
@yongshin we need to add some more details on whats happening behind the scenes so people can understand and tweak as they want.

**Comment by yongshin** [comment]
@abhi I can modify but I don't I will be validate any changes, if you send me the correct information I can update the doc

**Comment by yongshin** [comment]
Also ccing @stevenfollis here so he can provide input

**Comment by ahh-docker** [comment]
@david-yu any updates on this?

**Comment by david-yu** [comment]
@mark-church Do you know if this looks good? Abhi had proposed removing these lines from our docs since he has stated we no longer need to perform those commands.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Pull request closed without merging**
