### PR TITLE
Updates allpagelinks.md to use full paths

### PR DESCRIPTION
**Pull request by joaofnfernandes**
@aduermael I think this will fix the last broken link reported by #1068.
Can you run your tests on top of this PR?

### CODE REVIEW

**Comment by johndmulhausen** [comment]
@joaofnfernandes It's a harmless fix; I think if we merge this that his check will work. Let's do it!

**Comment by aduermael** [comment]
@joaofnfernandes I rebased #1052, but I don't understand how that is going to fix the last broken link.

**Comment by joaofnfernandes** [comment]
It seems that for most urls in `allpages.md` it doesn't make a difference. But for the 404 it does.

```
before /404/
after /404.html
```

That should address the broken link (and hopefully not introduce new ones)

**Comment by aduermael** [comment]
@joaofnfernandes great! :)

**Pull request merged**
