### PR TITLE
Updated two in-document anchors on Install Docker for Ubuntu page.

### PR DESCRIPTION
**Pull request by MWeesenaar**
### Describe the proposed changes
I edited two in-document anchors, since they seemed to be incorrectly linked.
https://docs.docker.com/engine/installation/linux/ubuntulinux

The links had #install in stead of #install-the-latest-version (my assumption)

### Unreleased project version
N/a 

### Related issue
Not sure if there's a related issue.

### Related issue or PR in another project
N/a

### Please take a look
N/a

### CODE REVIEW

**Comment by johndmulhausen** [comment]
Deploy preview ready!

Built with commit 3258d0cef5add846a95560da70732af9e54d6ee3

https://deploy-preview-804--docker-docs.netlify.com

**Comment by MWeesenaar** [comment]
Quickly manually tested the fix by going to:
https://deploy-preview-804--docker-docs.netlify.com/engine/installation/linux/ubuntulinux/#/prerequisites-by-ubuntu-version
And clicking on *Go ahead and **install Docker***.

Ditto for *After your system reboots, go ahead and **install Docker***.

**Comment by johndmulhausen** [comment]
Thanks @MWeesenaar :)

**Comment by MWeesenaar** [comment]
You're welcome! I love it how easily I could fix it myself! Keep up the good work, guys! You're doing great! ^.^

**Pull request merged**
