### PR TITLE
fix type of keywords entry in frontmatter (in /docker-cloud/ dir)

### PR DESCRIPTION
**Pull request by gdevillele**
### Describe the proposed changes

in /docker-cloud/ :
change keywords's type from array to string.

### Project version

current stable

### Related issue

contributes to #435 

Signed-off-by: Gaetan de Villele <gdevillele@gmail.com>

### CODE REVIEW

**Comment by johndmulhausen** [comment]
Deploy preview processing.

Built with commit bcec1ddcb2366faf4067af322ba46f17f382acd5

https://app.netlify.com/sites/docker-docs/deploys/58218ab8668674753a544cfd

**Comment by sanscontext** [comment]
LGTM, though I'm not sure if I should be seeing any different behavior here. (Google results?)

Also, @gdevillele, does your editor do something interesting with the final line? It looks like there's a spurious end of file change in all these diffs, which is confusing.

**Comment by gdevillele** [comment]
@sanscontext Thank you.

Behavior is expected to be exactly the same.

About the last line, I have just removed trailing LF (line feed) characters.
It can be confusing in the Github UI as they are non-printable characters.

**Comment by sanscontext** [comment]
Ah, interesting. I wonder if Atom is/was adding those.

**Comment by gdevillele** [comment]
@sanscontext I cannot know for sure, but I suppose it is just the writer who pressed the ENTER key at the end of the file. It isn't more than that 🙂

**Comment by sanscontext** [comment]
Merged! Sorry for the delay, little distracted with updates yesterday :)

**Comment by gdevillele** [comment]
Thx. No problem.

**Pull request merged**
