### PR TITLE
Add cloud.ca to the list of 3rd-party docker machine drivers.

### PR DESCRIPTION
**Pull request by simongodard**
### Proposed changes

Added [cloud.ca](https://cloud.ca) to the list of 3rd-party docker machine drivers.

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @nathanleclaire ptal

**Comment by nathanleclaire** [comment]
LGTM

I wish this file was in Markdown though 😿

**Comment by johndmulhausen** [comment]
Thanks, @simongodard :)

**Comment by nathanleclaire** [comment]
👍

**Pull request merged**
