### PR TITLE
Fix formatting for Markdown files containing `{{`

### PR DESCRIPTION
**Pull request by benizi**
They're usually examples of Go-style text templates.  But, Liquid templating is treating them as variable substitutions.  E.g., in `engine/reference/commandline/ps.md`:

```bash
$ docker ps --filter volume=remote-volume --format "table {{.ID}}\t{{.Mounts}}"
```

is rendered as:

```bash
$ docker ps --filter volume=remote-volume --format "table \t"
```

Solution is to wrap entire files in `{% raw %} ... {% endraw %}` blocks.

### CODE REVIEW

**Comment by benizi** [comment]
I think this fixes docker/docker.github.io#44.

Not sure whether the (much-)simpler option of changing `{{ content }}` to `{{ content | markdownify }}` in `_layouts/docs.html` would work, since there are some Markdown files that contain legitimate usage of templating directives.

**Comment by johndmulhausen** [comment]
I'd prefer that we put {% raw %} and {% endraw %} around every instance of a {{ bracketed }} string, like so:

`{% raw %}{{ foobar }} {% endraw %}`

Or at least, just the affected code blocks. The scope should be narrower, is what I mean.

If you wrap raw/endraw around the entire page like this, that will prevent any Liquid templating language from processing. So if anyone touches these 35 pages in the future and tries to include a file, add some logic, print a variable, etc., they're going to see the raw code instead of the interpreted/processed code.

**Comment by iBobik** [comment]
> Not sure whether the (much-)simpler option of changing {{ content }} to {{ content | markdownify }} in _layouts/docs.html would work, since there are some Markdown files that contain legitimate usage of templating directives.

This if very nice solution, because docs contributors should not need to thing about Jekyll. How about to improve it by adding condition to _layouts/docs.html to turn on Luquid optionally?

Like this:
```
{% if page.use_liquid %}
  {{ content }}
{% else %}
  {{ content | markdownify }}
{% endif %}
```

And in all content files where Liquid is needed just include this on top:
```
---
use_liquid: True
---
```

**Comment by johndmulhausen** [comment]
@benizi @iBobik 

Tried the markdownify at the layout level; that doesn't work, and it; also SUBSTANTIALLY increases build time. Accepting this fix for now; we'll adjust the scope of the RAW tags in the future if we have problems w/liquid.

**Pull request merged**
