### PR TITLE
update engine reference docs

### PR DESCRIPTION
**Pull request by thaJeztah**
updating to the latest changes from the 20.10 branch

also includes the changes from https://github.com/docker/cli/pull/3174 and https://github.com/docker/cli/pull/3175 (soon to be merged)

### CODE REVIEW

**Comment by thaJeztah** [comment]
@usha-mandya @mat007 PTAL

**Review by mat007 — APPROVED** [review]
Looks good to me!

image

**Comment by mat007** [comment]
Actually clicking on the tooltip tries to open https://deploy-preview-13106--docsdocker.netlify.app/engine/deprecated/ which is a 404.
But maybe it’s because it’s a docs preview?

**Comment by thaJeztah** [comment]
Yes, that's expected on the Netlify preview 👍

**Review by usha-mandya — APPROVED** [review]
LGTM

**Pull request merged**
