### PR TITLE
open source contributors TOC update

### LINKED ISSUE #5412: "Open source at docker"'s all sub menus are redirected to "Contribute to documentation"
### Problem description

- https://docs.docker.com/opensource/code/
- https://docs.docker.com/opensource/FAQ/
- https://docs.docker.com/opensource/doc-style/
- https://docs.docker.com/opensource/get-help/
- https://docs.docker.com/opensource/project/who-written-for/ 

...
are redirected to

- https://docs.docker.com/opensource/
This url did not have many contents to cover the above menus.

### Problem location

- I saw a problem on the following URL: 
https://docs.docker.com/ -> Guide menu -> in left side "Open Source at docker" 

- I couldn't find the information I wanted. I expected to find it near the following URL: 
"Open Source at docker"'s all sub menus are have href source, but all redirected to https://docs.docker.com/opensource/

- Other: Is this redirection is error or right?

### PR DESCRIPTION
**Pull request by londoncalling**
### What's changed

- Updated TOC for [Open source at Docker](https://docs.docker.com/opensource/) topics to reflect current content. (The Open source guide was pared down per PR #5246 but I forgot to finalize the relevant TOC updates.)

### Related
- PR #5246
- Fixes #5412 

### Reviewers

@Myeongjoon @johndmulhausen @mistyhacks @JimGalasyn 

Signed-off-by: Victoria Bialas <vicky.bialas@gmail.com>

### CODE REVIEW

**Comment by londoncalling** [comment]
@johndmulhausen @mistyhacks 

These commits seem to build and display fine in Netlify but starting with the changes in the second commit, I was not able to build locally. I kept getting an error upon running `bundle exec jekyll serve` which is similar to the errors discussed here. 

The thing is, it doesn't seem it's anything I did, because I got the same errors even when I tried to build from local `master` (which doesn't have the changes associated with this PR of course). The build command was working originally. I assumed it was something to do with `toc.yml` and tinkered with everything I could that I thought would affect it. 

I did find what looked like an error in ordering `path` and `title` on the `docsarchive` entries (in master at lines 539-544), where they look like this:

```
- sectiontitle:
  section:
  - path: /docsarchive/
    title: View the docs archives
  - title: Docs hackathon results
    path: /hackathon/
```
I corrected for that on this PR, but it didn't help the local build problem.

I have the exact errors I got on home laptop, along with the Ruby issues point to the exact same error output and related to `.yaml` file syntax problems. Can send if needed, but can you see if you get errors when you try to build locally from this branch?

**Comment by johndmulhausen** [comment]
Didn't see any jekyll build errors but I did see that `sectiontitle:` was blank for Docs Archives which has been fixed.

**Comment by londoncalling** [comment]
@johndmulhausen Another line in `toc.yaml` right after the Docs Archive stuff looks off also. See 546-548 on the current master version of [toc.yaml]( https://github.com/docker/docker.github.io/blob/master/_data/toc.yaml):

```
reference:
- title: Dockerfile reference
  path: /engine/reference/builder/
```

Would that also cause problems?

See line https://github.com/docker/docker.github.io/blob/master/_data/toc.yaml

**Comment by londoncalling** [comment]
@thaJeztah Hi Seb! Care to take a look at this and merge if you think it's good? ;-) Much appreciate it.

**Comment by johndmulhausen** [comment]
Think I fixed the toc.yaml weirdness and merge conflict so we're probably good here.

**Comment by johndmulhausen** [comment]
Thanks again, @londoncalling -- don't be a stranger!

**Comment by thaJeztah** [comment]
Should we copy the content of the kitematic contributing guide back to the kitematic repository? /cc @frenchben

**Comment by londoncalling** [comment]
@thaJeztah you could add it to Kitematic repository if @jeffdm and @FrenchBen have no objections. It pained me to remove that here, but I couldn't justify leaving it even to myself, and @johndmulhausen and @mistyhacks would have finally seen it and said "why are we talking about Kitematic here?" :-) But look how cute it is: https://docs.docker.com/v17.06/opensource/kitematic/get_started/

**Pull request merged**
