### PR TITLE
Document the user for Docker for AWS instances

### LINKED ISSUE #3713: Document EC2 User as "docker@<ec2-instance>"
### Problem description
There is no information about how to log in to the EC2 instance that is the Swarm manager. Typical users are: root, ubuntu, ec2-user. No where in the documentation (unless you look in the CloudFormation Template) is it documented that this has changed to user "docker"

Ergo, ssh-ing to EC2 with:

```
ssh -i <key>.pem ec2-user@<swarm-manager>
```

to _test the installation_ will always return Permission Denied

### Problem location

- I saw a problem on the following URL: <URL>
https://docs.docker.com/docker-for-aws/

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>
https://docs.docker.com/docker-for-aws/

- Other: <DETAILS>

### Suggestions for a fix

Make sure that it is outlined that the user for AWS has been changed to "docker" instead of root/ec2-user/ubuntu.

### PR DESCRIPTION
**Pull request by mstanleyjones**
Fixes #3713 

@friism @FrenchBen @kencochrane PTAL

### CODE REVIEW

**Comment by friism** [comment]
I'm not sure the premise of the but report is correct since the user to use is documented: https://github.com/mstanleyjones/docker.github.io/blob/4c57b5f1e35521a41e7555f8e97c1c63a3af4ee3/docker-for-aws/deploy.md#manager-nodes

... but sure.

**Comment by mstanleyjones** [comment]
To be fair, I think they only used the quickstart, and didn't carefully read the deployment topic you linked to. :)

**Comment by mstanleyjones** [comment]
Amazing idea!

**Comment by londoncalling** [comment]
@mstanleyjones I'm smart.

**Pull request merged**
