### PR TITLE
Update Deactivate Accounts

### PR DESCRIPTION
**Pull request by jerae-duffin**
Updated steps for account or organization

### CODE REVIEW

**Review by craig-osterhout — DISMISSED** [review]
LGTM

**Comment by amaderic** [comment]
For deactivating an Organization, we want to say:
"If you have an active subscription, downgrade it to the Docker Free Team subscription"

**Comment by amaderic** [comment]
For deactivating an Account we want to say:
"If you have an active subscription, downgrade it to the Docker Personal subscription."

**Comment by amaderic** [comment]
I also think this has been removed from Hub so we should omit it in docs: 
"If you have an enterprise license, download the key.
In Docker Hub, navigate to Your Account > Accounts Settings > Licenses. The download link will no longer be available after your account is disabled."

**Pull request closed without merging**
