### PR TITLE
Update resource_constraints.md

### PR DESCRIPTION
**Pull request by pareshdkc**
### Proposed changes

--memory-swap=""   :	Total memory limit (memory + swap, format: <number>[<unit>])
So here if we do not want to allow any swap, we have to keep swap value in above to 0 which means --memory-swap value becomes --memory value.

### CODE REVIEW

**Comment by mstanleyjones** [comment]
Does this relate to a specific GitHub issue?

**Comment by johndmulhausen** [comment]
@mstanleyjones Could be addressing #2801

**Comment by pareshdkc** [comment]
yes..!! it is for issue #2851

**Comment by mstanleyjones** [comment]
Closing for now. Please reopen if you can provide more context.

**Pull request closed without merging**
