### PR TITLE
logging/gelf: recommend to disable compression

### PR DESCRIPTION
**Pull request by kolyshkin**
It was discovered that compression in gelf logging driver
is highly inefficient in terms of CPU. IOW, lots of CPU
is used when compression is enabled.

The natural solution would be to change the default
to `none`, i.e. no compression, but that would break
some setups (in particular, using Logstash < 7.4).

The only option left is to warn the user about the
consequences of leaving the compression enabled.

For more background details, please see
https://github.com/moby/moby/pull/40101

PS it makes sense to backport this to older engine version docs, too.

### CODE REVIEW

**Comment by kolyshkin** [comment]
@adrian-plata @lena-larionova PTAL

**Comment by kolyshkin** [comment]
Looks ok but maybe there's a way to somehow emphasize this warning?
https://deploy-preview-9881--docsdocker.netlify.com//config/containers/logging/gelf/

**Comment by adrian-plata** [comment]
We could bold it or possibly put it in a note carrot. That might get funky. I’ll try some alternatives tomorrow.

**Comment by adrian-plata** [comment]
Unfortunately, tables tend to break most formatting so we can't use the caret. To draw more attention, I'll make it bold in another PR.

**Comment by adrian-plata** [comment]
PR in  question: https://github.com/docker/docker.github.io/pull/9885

**Pull request merged**
