### PR TITLE
Prepare Docker Desktop Edge 2.3.5.1 patch release

### PR DESCRIPTION
**Pull request by simonferquel**
### Proposed changes

This PR prepares for releasing Docker Desktop Edge 2.3.5.1 patch release for Windows user (with 1 single bugfix)

### CODE REVIEW

**Review by mat007 — APPROVED** [review]
Looks good to me!

**Comment by simonferquel** [comment]
Hold for final build url though :)

**Comment by usha-mandya** [comment]
Thanks @simonferquel. LGTM. I'll approve after we've added the download url as any subsequent commits will dismiss previous approvals.

**Comment by simonferquel** [comment]
Just updated the PR with the correct link. cc @usha-mandya

**Review by usha-mandya — APPROVED** [review]
LGTM

**Pull request merged**
