### PR TITLE
CPU must be SLAT-capable for Hyper-V

### PR DESCRIPTION
**Pull request by docbenton**
### Unreleased project version (optional)

good to know before you install that SLAT-Capable cpu is needed for Hyper-V

### Related issues (optional)
#6381

### CODE REVIEW

**Comment by gbarr01** [comment]
cc: @akimd

**Comment by gbarr01** [comment]
@akimd ... you sure about the mac similarity? After all, Hyper-V is really _Microsoft Hyper-V_. 

Also, I wonder about this definitive statement about the BIOS and SLAT.  Do all systems need SLAT support, or only some? From what I can tell, only some ...

**Comment by gbarr01** [comment]
I take back my 2nd point per this doc (to which we actually link) :https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/reference/hyper-v-requirements

> Hyper-V requires Second Level Address Translation (SLAT) -- present in the current generation of 64-bit processors by Intel and AMD.

**Comment by gbarr01** [comment]
Thanks, @docbenton

**Comment by akimd** [comment]
@gbarr01 Honestly, I have no idea.  A quick search gave nothing, but I expect that the requirements of Hyper-V of MS match those of the Hypervisor framework of Apple.  And after all, these are the same chips.  But given that Apple has full control on the hardware, maybe all the processors of Mac that support virtualization also support SLAT.

Anyway, let's not bother, future will tell.

**Pull request merged**
