### PR TITLE
DTR release notes for March 2020 Amberjack patch release

### PR DESCRIPTION
**Pull request by Dawn-Wood**
### Proposed changes

Added release notes for DTR for the March 2020 patch release.

### CODE REVIEW

**Comment by Dawn-Wood** [comment]
@traci-morrison @rgardziel this is the pr to merge to master and then to published tomorrow after the patch release goes live between 10 am and 12 pm. Related pr for UCP is here: https://github.com/docker/docker.github.io/pull/10424

**Comment by Dawn-Wood** [comment]
@usha-mandya I think it's ok to merge this to master now if everything looks ok to you.

**Comment by Dawn-Wood** [comment]
right good call on the version bump. Will do that asap

**Comment by usha-mandya** [comment]
Let me know if you want to create a separate PR for config yaml updates. If so, I'll merge this PR.

**Comment by Dawn-Wood** [comment]
thanks @usha-mandya I'll update the versions and links to the tarballs in this pr. Hope to have that ready in a few minutes.

**Comment by Dawn-Wood** [comment]
@usha-mandya do you see the error I'm making? I broke the build. :(

**Pull request merged**
