### PR TITLE
remove Docker for AWS/Azure content

### PR DESCRIPTION
**Pull request by tfoxnc**

### CODE REVIEW

**Comment by mixja** [comment]
Does this mean Docker for AWS/Azure is deprecated?

**Comment by hairyhenderson** [comment]
See also https://github.com/docker/for-aws/issues/163 - it would be great if someone from Docker could make a statement about this. Some of us are running D4AWS, and this is... _worrying_...

**Comment by hairyhenderson** [comment]
@gary-cowell to be fair, it's only 7:30am at Docker HQ - hopefully there'll be updates when they all start waking up though!

**Comment by tfoxnc** [comment]
Apologies - we inadvertently removed this section while updating the docs for Docker CE to note the new release channels. We have fixed it, and the docs are back. We still need to update the Docker for AWS/Azure docs now that Edge is now the nightly channel.

**Comment by BretFisher** [comment]
See https://twitter.com/hairyhenderson/status/1019959573854203905

Basically, Docker for AWS/Azure are no longer supported, but no public announcement AFAIK. [DCI](https://success.docker.com/article/certified-infrastructures-aws) is the replacement solution for EE cluster deployments.  You'll see the [main site marketing pages](https://www.docker.com/docker-aws) lead you to DCI docs.

**Comment by hairyhenderson** [comment]
I replied on Twitter, but just to increase the chances of being heard - I wish Docker would just open-source the D4AWS components! The writing is on the wall for D4AWS-CE, and I'd hate to see it just abandoned along with its users, no matter how few.

**Pull request merged**
