### PR TITLE
4098 devicemapper bullet appears twice

### LINKED ISSUE #4098: 'devicemapper storage driver in practice' appears twice
File: [engine/userguide/storagedriver/selectadriver.md](https://docs.docker.com/engine/userguide/storagedriver/selectadriver/), CC @mstanleyjones

In section `Related information` at the bottom of the page item _devicemapper storage driver in practice_ appears twice with two different styles:
- `devicemapper ` storage driver in practice
- Device Mapper storage driver in practice

### PR DESCRIPTION
**Pull request by cthomas15**
File: engine/userguide/storagedriver/selectadriver.md

In section Related information at the bottom of the page item devicemapper storage driver in practice appears twice with two different styles. The one is correct so I deleted the second one. Fixes #4098.

### CODE REVIEW

**Comment by mstanleyjones** [comment]
In the future, please don't mention a Github issue or pull request number in a commit message, as it will continue to ping that Github issue or pull request whenever the commit is integrated into a different branch.

**Comment by cthomas15** [comment]
Sorry about that. This my first time contributing to open source and I'm still getting used to how it all works. Are referring to the message when I submitted the pull request?

**Comment by mstanleyjones** [comment]
Aha, I see that you just referenced the issue ID in the pull request title itself. You didn't do it in the commit message, which is good. In the future, you can use Github magic to automatically close an issue when its pull request is closed by adding text into the summary (not the title) of the pull request like `Fixes #12345`.

**Comment by cthomas15** [comment]
Ok, I'll make sure to do that next time. Thanks!

**Pull request merged**
