### PR TITLE
fix type of keywords entry in frontmatter (in /datacenter/)

### PR DESCRIPTION
**Pull request by gdevillele**
### Proposed changes

in `/datacenter/` :
change `keywords`'s type from array to string.

### Project version

current stable

### Related issue

contributes to #435 

Signed-off-by: Gaetan de Villele <gdevillele@gmail.com>

### CODE REVIEW

**Comment by johndmulhausen** [comment]
Deploy preview processing.

Built with commit 2804bb4cd190ce1eab4b5b75aaf35c4ab87bb2e1

https://app.netlify.com/sites/docker-docs/deploys/5826495dd6865d1ae6eef34c

**Comment by gdevillele** [comment]
Rebased against master. Thanks.

cc @joaofnfernandes

**Comment by joaofnfernandes** [comment]
Sorry for having caused conflicts and forcing you to rebase 😅 LGTM.

**Comment by johndmulhausen** [comment]
Thanks @gdevillele and @joaofnfernandes :)

**Pull request merged**
