### PR TITLE
Add docker-machine-driver-yandex

### PR DESCRIPTION
**Pull request by GennadySpb**
### Proposed changes

Add 3rd party Docker Machine driver reference for Yandex.Cloud

### CODE REVIEW

**Comment by GennadySpb** [comment]
tiny ping

**Comment by GennadySpb** [comment]
Hi @stephen-turner @usha-mandya !
Could I request your review for this PR? :)

**Comment by craig-osterhout** [comment]
Thank you for contributing. Closing as no longer applicable.

**Comment by usha-mandya** [comment]
@GennadySpb Docker Machine is deprecated. Please use Docker Desktop instead. Here's the link to Docker Desktop docs - https://docs.docker.com/desktop/

**Pull request closed without merging**
