### PR TITLE
Update trust_sandbox.md

### PR DESCRIPTION
**Pull request by scjane**
Should it be "Now, you xxx" or "Now that you xxx"?

### CODE REVIEW

**Comment by johndmulhausen** [comment]
This works, thanks, @scjane :)

**Comment by johndmulhausen** [comment]
@scjane Congratulations on being our 2,000th pull request! :1st_place_medal:

**Comment by scjane** [comment]
@johndmulhausen Cheers🙌

**Comment by johndmulhausen** [comment]
@scjane Can you ping me your email address? We wanted to send you a little something. :)

**Comment by scjane** [comment]
@johndmulhausen Hi, my email address is wangjie5@chinaskycloud.com. I guess the "little something" is a grammar or style reference guide?😄

**Pull request merged**
