### PR TITLE
Fix syntax for passing options to `volume create`

### LINKED ISSUE #325: "docker volume create" accepts no argument(s)"
### Problem description

When following https://docs.docker.com/engine/tutorials/dockervolumes/, section [Mount a shared-storage volume as a data volume](https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-shared-storage-volume-as-a-data-volume), specifically issuing this command there:

``` sh
$ docker volume create -d flocker -o size=20GB my-named-volume
```

After issuing the command, this was the docker's full output:

```
"docker volume create" accepts no argument(s).
See 'docker volume create --help'.

Usage:  docker volume create [OPTIONS]

Create a volume
```
### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/tutorials/dockervolumes/
### Project version(s) affected

Running on macOS with:

```
$ docker --version
Docker version 1.12.2, build bb80604, experimental
```

### PR DESCRIPTION
**Pull request by mstanleyjones**
### Describe the proposed changes

Fix syntax mistake when passing options to `volume create`.

### Related issue

Fixes #325

### Please take a look

@dusek @lybrus

### CODE REVIEW

**Comment by johndmulhausen** [comment]
Deploy preview ready!

Built with commit 13dc8451cff93b81b4ae9cdc2b01ecf1fdcc6be9

https://deploy-preview-627--docker-docs.netlify.com

**Comment by johndmulhausen** [comment]
@mstanleyjones Are you sure it's supposed to have two equals signs like that? 

```
$ docker volume create --help

Usage:	docker volume create [OPTIONS]

Create a volume

Options:
  -d, --driver string   Specify volume driver name (default "local")
      --help            Print usage
      --label value     Set metadata for a volume (default [])
      --name string     Specify volume name
  -o, --opt value       Set driver specific options (default map[])
```

**Comment by mstanleyjones** [comment]
Yep, we have a few like that. @thaJeztah may have some history on it.

**Comment by thaJeztah** [comment]
I think it depends if it's a plugin option, or a mount option. Ping @cpuguy83 for a quick look, because I may be confused

**Comment by cpuguy83** [comment]
LGTM

**Comment by johndmulhausen** [comment]
Thanks, all :)

**Pull request merged**
