### PR TITLE
How to upgrade a vendor package

### PR DESCRIPTION
**Pull request by krasi-georgiev**
I couldn't find any info how to upgrade a vendor package so after a short chat in the slack channel posting the official way

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
Who is responsible to approve this merge ?

**Comment by londoncalling** [comment]
@thaJeztah @johndmulhausen can you guys look at this? It isn't my area, needs review and merge if it's correct.

**Comment by thaJeztah** [comment]
Sorry for the late reply, looks like I missed this ping. Generally this is correct, but it's likely the user doesn't have `vndr` installed, so we should either explain how to install it, or show how to use the development container (https://github.com/docker/docker.github.io/blob/master/opensource/project/set-up-dev-env.md) to run `vndr`. `vndr` is installed inside the development container, so if you bind-mount the source it will update the dependencies on your host.

**Comment by krasi-georgiev** [comment]
all good!

**Pull request merged**
