### PR TITLE
change pre-build to pre_build to remove confusion

### LINKED ISSUE #2535: Eliminate confusion of pre_build file name in the docs
File: [docker-cloud/builds/advanced.md](https://docs.docker.com/docker-cloud/builds/advanced/), CC @londoncalling 

In two-phase builds the pre-build is spelled correctly (as in English) but marked as it is a keyword.

This made me waste an hour of wondering why the pre-build is not being executed.

Maybe drop the Englush spelling in favor of the actual file name (pre_build, with underscore instead of dash)?

Thank you for documentation!

### PR DESCRIPTION
**Pull request by shubheksha**
### Related issues (optional)
Fixes #2535

### CODE REVIEW

**Comment by shubheksha** [comment]
@londoncalling, do I need to remove the formatting too to ensure it's not mistaken as a command? Or should I explicitly mention that it's the name of a file?

**Comment by londoncalling** [comment]
@shubheksha I think that would be good but I'm going to merge this and then make that minor fix. Looks great!

**Comment by londoncalling** [comment]
LGTM 👍

**Comment by teodorescuserban** [comment]
Awesome, guys!
Thank you!

**Pull request merged**
