### PR TITLE
practical solution for network overlapping

### PR DESCRIPTION
**Pull request by funkydorian**

### CODE REVIEW

**Comment by thaJeztah** [comment]
I'm not sure these hints give a ,out of information on _how_ to do this; also @aboch is working on a pull request in docker to override the predefined pools, which seems like a sane solution

**Comment by aboch** [comment]
@funkydorian If this section is about controlling the IP address chosen for the `docker0` bridge, we should probably mention that there is also an ad-hoc daemon option for that `--bip 192.168.0.1/16` as an example.

**Comment by mstanleyjones** [comment]
Ping?

**Comment by funkydorian** [comment]
Hello, it is bridge and also overlay, do that cover thay as well?

**Comment by mstanleyjones** [comment]
@funkydorian I don't understand your question, sorry. Please address feedback from @thaJeztah and @aboch if you still want to try to get this change in, otherwise please close the PR. Thanks!

**Comment by mstanleyjones** [comment]
If you want to get this merged, please address the feedback and resolve the merge conflict. It's been waiting for more than a month. :)

**Comment by mstanleyjones** [comment]
Out of date and no communication.

**Pull request closed without merging**
