### PR TITLE
Add doc for firewall auto-detection

### PR DESCRIPTION
**Pull request by mstanleyjones**
### Describe the proposed changes

Added docs about firewall auto-detection on D4W

### Project version

Beta 29

### Related issue

n/a

### Related issue or PR in another project

https://github.com/docker/pinata/issues/5593

### Please take a look

@simonferquel @londoncalling

### CODE REVIEW

**Comment by mstanleyjones** [comment]
@simonferquel the URL will be https://docs.docker.com/docker-for-windows/#/#firewall-rules-for-shared-drives/

**Comment by simonferquel** [comment]
The popup will look a bit more like this: 
image

**Comment by mstanleyjones** [comment]
I updated the image with the one you provided, @simonferquel

**Comment by simonferquel** [comment]
Lgtm

**Comment by mstanleyjones** [comment]
Waiting until beta29 release to merge.

**Comment by mstanleyjones** [comment]
I took the screenshot from Windows. Has the artwork changed since I took
the screenshot? Is this one final enough that I can use it?

On Oct 24, 2016, at 1:58 AM, Simon Ferquel <notifications@github.com> wrote:

The popup will look a bit more like this:
[image: image]
<https://cloud.githubusercontent.com/assets/1677333/19639426/b93c9f24-99d8-11e6-86e2-6a989d08794c.png>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/docker/docker.github.io/pull/307#issuecomment-255684918>,
or mute the thread

**Pull request merged**
