### PR TITLE
Add TCP documentation for GELF logging driver

### PR DESCRIPTION
**Pull request by ghislainbourgeois**
Signed-off-by: Ghislain Bourgeois <ghislain.bourgeois@gmail.com>

### Proposed changes

I updated the GELF log driver documentation to reflect the new TCP support and related options. I also added a required column for the options to clarify that only the `gelf-address` parameter is required.

### Unreleased project version (optional)

This will apply only on the version containing the changes in the Moby pull request linked below.

### Related issues (optional)

[Moby PR 34758](https://github.com/moby/moby/pull/34758)

### CODE REVIEW

**Comment by thaJeztah** [comment]
@mstanleyjones @londoncalling upstream PR is now merged

**Comment by Hermain** [comment]
Tcp support for Gelf is already mentioned in the documentation under version 17.09 although this is not supported by 17.09 (correct me if I'm wrong) or even 17.10.
https://docs.docker.com/engine/admin/logging/gelf/
This should be rolled back until Moby PR 34758 is in the latest release version.

**Comment by mistyhacks** [comment]
Hi @Hermain, you are right that it wasn't in 17.10 and the docs got updated due to confusion. However, it will be in 17.11 (https://github.com/docker/docker-ce/commit/9fb93d3c849bb8ff48bf8f61e475ade292f503b4) so I think it's OK for us to leave it alone since that release is coming soon.

**Comment by Hermain** [comment]
Hi @mistyhacks, that's alright depending on how soon soon is :). At least anyone else who read about tcp gelf support will end up here and see that its not ready yet but soon.

**Pull request merged**
