### PR TITLE
Remove irrelevant MacOS install section

### PR DESCRIPTION
**Pull request by JL2210**
Remove MacOS install section from Linux install page

### Proposed changes

This removes the irrelevant MacOS install section on the Linux install page.

### CODE REVIEW

**Comment by thaJeztah** [comment]
I think this content may still be relevant for users that only want to install the docker cli on macos without installing Docker Desktop.

I agree that it's a bit confusing that this pages is listed in the Linux section though

**Comment by L-Hudson** [comment]
@paigehargrave, would you PTAL, and move this content over into the MacOS docs? This info isn't over there at all, and I think it should be.

**Comment by paigehargrave** [comment]
@thaJeztah @JL2210 Hi - This is definitely confusing. I've restructured the topic - please review #8386 and see if this works.  Thank you @JL2210 for bringing this to our attention!

**Comment by bermudezmt** [comment]
@JL2210 @thaJeztah please see https://github.com/docker/docker.github.io/pull/8386#issuecomment-468853348. Closing this PR in favor of #8386 .

**Pull request closed without merging**
