### PR TITLE
Stash computed data in a Liquid variable

### PR DESCRIPTION
**Pull request by ashmaroli**
### Proposed changes

Stash computed data in a Liquid variable (`controller_data`) to avoid computing `site.data[include.datafolder][include.datafile]` multiple times for the same context.

### CODE REVIEW

**Comment by usha-mandya** [comment]
Thank you @thaJeztah. I'll check this out locally and build docs.

**Comment by usha-mandya** [comment]
Thank you @ashmarol!

**Comment by ashmaroli** [comment]
Thank you for reviewing @thaJeztah and @usha-mandya :smiley:

**Pull request merged**
