### PR TITLE
Engdocs 490

### PR DESCRIPTION
**Pull request by jerae-duffin**
Updated step 4 on PAT topic

### CODE REVIEW

**Comment by jerae-duffin** [comment]
@usha-mandya @thaJeztah When I remove the #5 the table doesn't render correctly. Is there a tag to use to keep the table format?

**Comment by thaJeztah** [comment]
Hmm, it shows there's a merge conflict; perhaps that's what causing it.

But I'd have to look from my computer (could also be some indentation issue somewhere, but those are hard to spot on mobile 🤔🙃😅)

**Comment by jerae-duffin** [comment]
@thaJeztah Ahh ok, I accidentally used this branch for this new update & it was already merged into Master.

**Comment by thaJeztah** [comment]
I tried rebasing your PR to get rid of the extra commits, and I think it looks OK after that.

What I did:

To rebase this PR and get rid of the commits from the other PR, you can check out your branch, then start an interactive rebase;

```
git rebase -i upstream/master
```

That should open your default editor showing the commits in this PR, looking something like;

```
pick 58e12d6efb updated downgrade and add seats
pick e9eaa9648d removed header
pick 7d1351f783 revised step 4

# Rebase 401c940a80..7d1351f783 onto 401c940a80 (3 commands)
```

If you remove the first two lines, your're removing those commits from the PR:

```
pick 7d1351f783 revised step 4

# Rebase 401c940a80..7d1351f783 onto 401c940a80 (3 commands)
```

Save the file to complete the rebase, which should show something like:

```
Successfully rebased and updated refs/heads/ENGDOCS-490.
```

Then force-push your changes to github (make sure you push to the right remote :D);

```
git push -f -u origin
```

**Comment by thaJeztah** [comment]
While at it, I made some changes (in the last commit);

access-tokens: markdown touch-ups, and some copy edits

- wrap lines to ~80 characters
- indent second lines for bullets to make them look slightly more as bullet-lists (also when looking at the source)
- Split the "Modify existing tokens" into three steps. Doing so, we could include the "You can also view the number of tokens that are activated and deactivated in the toolbar." note as regular text. The bullet already had 2 images _and_ a note, which made it a bit "cluttered"
- Added a step to "save" the changes. It's trivial, but felt like it made the topic "finished".
- Changed the mention of the "Docker Hub CLI and API" to a note, so that it's standing out a bit more, and somewhat clearer that it's not really part of the instructions.

**Comment by thaJeztah** [comment]
Let me add a screenshot of that last section

Screenshot 2021-09-23 at 13 20 39

**Comment by thaJeztah** [comment]
@usha-mandya @jerae-duffin PTAL (let me know if you like those last changes I made 😅 )

**Comment by usha-mandya** [comment]
@thaJeztah Looks good. Thanks

**Review by usha-mandya — APPROVED** [review]

**Pull request merged**
