### PR TITLE
Install on azure reqs update 081419

### PR DESCRIPTION
**Pull request by ivansharamok**
### Proposed changes

Added line under `Azure Prerequisites` section
- Internal IP addresses for all nodes should be [set to Static](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-static-private-ip-arm-pportal), rather than the default of Dynamic.

Added details to the first sentence under `Azure Configuration File` section
- For Docker UCP to integrate with Microsoft Azure, each Linux UCP node in your cluster that runs `kubelet` component needs an Azure configuration file, `azure.json`.

### Related issues (optional)
this is a revision of PR #9117

### CODE REVIEW

**Comment by ivansharamok** [comment]
@ollypom could you please review and either approve or kick back and let me know what changes are required.

**Comment by ollypom** [comment]
@ivansharamok Thanks Ivan :) I have just reworded the paragraph slightly. Does this work for you?

**Comment by ivansharamok** [comment]
@ollypom looks great. thanks!

**Comment by ollypom** [comment]
Thanks @ivansharamok .

@DawnWood-Docker PTAL :)

**Pull request merged**
