### PR TITLE
Add labels-regex logging opt

### PR DESCRIPTION
**Pull request by robin-thoni**
### Proposed changes

Added documentation for new logging option called `labels-regex`.

I made these changes to the documentation in support of pull-request moby/moby#38586

That pull request embodies an enhancement to match environment variables by a regular expression instead of a just a literal match. Now there is a log-opt called 'labels-regex' in addition to 'labels'.

### CODE REVIEW

**Comment by L-Hudson** [comment]
@mavenugo @gforghetti can one of you take a look and let me know who should approve this? Thanks much!

**Comment by gforghetti** [comment]
@L-Hudson Not sure.  Definitely not me.

**Comment by thaJeztah** [comment]
Labeled this `WIP` (work in progress), because the feature wasn't merged yet 👍

**Comment by robin-thoni** [comment]
Feature has now been merged on moby master branch. I guess this one can now be merged too? Thanks

**Comment by robin-thoni** [comment]
ping?

**Pull request merged**
