### PR TITLE
docker-compose: change overview from /compose/overview to /compose/

### PR DESCRIPTION
**Pull request by thaJeztah**
the /compose/ (index page) didn't contain any useful information, and wasn't included in the navigation, so we might as well use "overview" as the landing page, which makes the URL also a bit more logical.

### CODE REVIEW

**Comment by thaJeztah** [comment]
@chris-crone

**Comment by chris-crone** [comment]
SGTM, thanks @thaJeztah

**Comment by thaJeztah** [comment]
@usha-mandya ptal

**Comment by usha-mandya** [comment]
That makes sense. Thanks for looking into this @thaJeztah.

**Pull request merged**
