### PR TITLE
D4win FAQs, troublehshooting for permissions on shared volumes

### PR DESCRIPTION
**Pull request by londoncalling**
### What's changed

- Added troubleshooting, FAQ, and a note in the topic on Shared Volumes. More soon, just wanted to get this work-in-progress (WIP) PR submitted and going first.

### Related

 #3298

### Reviewers

@friism @ShaunCurrier

Signed-off-by: Victoria Bialas <victoria.bialas@docker.com>

### CODE REVIEW

**Comment by londoncalling** [comment]
LGTM

**Comment by ShaunCurrier** [comment]
The permissions are constrained to `0755`, not `0770` as the new docs changes currently show.

**Comment by londoncalling** [comment]
Thanks @ShaunCurrier , I've submitted a new PR ^^ for this change

**Comment by Toilal** [comment]
Chmod from inside the container as some effect. You can try to chmod 440 any file, it will become read-only on the host, and mofications from inside the container will give a Permission denied error.

```bash
root@2847c37d4433:/var/www/html# echo "test">test
root@2847c37d4433:/var/www/html# ls -l test
-rwxr-xr-x 1 root root 11 Aug 23 07:33 test>>test
root@2847c37d4433:/var/www/html# echo "test2"
root@2847c37d4433:/var/www/html# cat test
test
test2
root@2847c37d4433:/var/www/html# chmod 440 test
root@2847c37d4433:/var/www/html# echo "test3">>test
bash: test: Permission denied
root@2847c37d4433:/var/www/html# ls -l test
-r-xr-xr-x 1 root root 11 Aug 23 07:33 test
root@2847c37d4433:/var/www/html
```

**Pull request merged**
