### PR TITLE
bump api to 1.27

### PR DESCRIPTION
**Pull request by vieux**
ping @johndmulhausen to be merged after 17.03.1 is released

### CODE REVIEW

**Comment by mstanleyjones** [comment]
@vieux can you clarify if this change is for 17.03 or 17.04?

**Comment by mstanleyjones** [comment]
Answered offline 👍

**Comment by vieux** [comment]
@mstanleyjones should I make a PR for the `vnext-engine` branch ? I'm not sure how it works.

**Comment by mstanleyjones** [comment]
Yes please! Be careful with the links in the `toc.yml` file. :)

**Pull request merged**
