### PR TITLE
Added missing release notes from D4AWS 17.03.0 release

### PR DESCRIPTION
**Pull request by kencochrane**
Signed-off-by: Ken Cochrane <KenCochrane@gmail.com>

### Proposed changes

Added missing release notes from Docker for AWS 17.03.0 release

### CODE REVIEW

**Comment by johndmulhausen** [comment]
CC @FrenchBen

**Comment by FrenchBen** [comment]
cc @kencochrane

**Comment by kencochrane** [comment]
@FrenchBen is there something I need to change?

**Comment by hairyhenderson** [comment]
@kencochrane it seems the release notes for `1.13.1-beta19` never made it - was there any intention to add those?

**Comment by kencochrane** [comment]
@hairyhenderson some of the betas are internal only, the internal ones that don't make it public don't have external release notes. The changes in those are usually reflected in later public betas. I'm not 100% that was the case with beta-19, but I'm pretty sure.

Is there something that you see missing?

**Comment by hairyhenderson** [comment]
@kencochrane - oh, I just noticed that there was an upgrade to beta19 at one point and I never saw release notes for it. It's more historical interest at this point. I didn't think it was an internal-only beta because the CFN template was labeled beta19 at the time.

Anyway, as long as nothing's missing, that's fine! 🙂

**Comment by kencochrane** [comment]
@johndmulhausen is there any changes you would like to this PR?

**Pull request merged**
