### PR TITLE
Remove obsolete products

### PR DESCRIPTION
**Pull request by justincormack**
These have not been available for some time.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Could you add redirects for the pages we removed?

```patch
diff --git a/index.md b/index.md
index 5bac67fa15..66295cd749 100644
--- a/index.md
+++ b/index.md
@@ -6,6 +6,26 @@ title: Docker Documentation
 notoc: true
 notags: true
 skip_read_time: true
+redirect_from:
+  - /docker-for-aws/
+  - /docker-for-aws/archive/
+  - /docker-for-aws/deploy/
+  - /docker-for-aws/faqs/
+  - /docker-for-aws/iam-permissions/
+  - /docker-for-aws/load-balancer/
+  - /docker-for-aws/opensource/
+  - /docker-for-aws/persistent-data-volumes/
+  - /docker-for-aws/scaling/
+  - /docker-for-aws/upgrade/
+  - /docker-for-aws/why/
+  - /docker-for-azure/
+  - /docker-for-azure/archive/
+  - /docker-for-azure/deploy/
+  - /docker-for-azure/faqs/
+  - /docker-for-azure/opensource/
+  - /docker-for-azure/persistent-data-volumes/
+  - /docker-for-azure/upgrade/
+  - /docker-for-azure/why/
 ---
 {% assign page.title = site.name %}

diff --git a/release-notes/index.md b/release-notes/index.md
index 362fc4013e..38a8cb3928 100644
--- a/release-notes/index.md
+++ b/release-notes/index.md
@@ -2,6 +2,9 @@
 description: Release notes for Docker
 keywords: docker, documentation, about, technology, understanding,  release
 title: Docker release notes
+redirect_from:
+  - /docker-for-aws/release-notes/
+  - /docker-for-azure/release-notes/
 ---

 Find out what's new in Docker! Release notes contain information about new
```

**Comment by justincormack** [comment]
These are not surfaced in the navigation anywhere, so I think its better if they just 404 at this point. Redirect to index is semantically wrong.

**Comment by thaJeztah** [comment]
99%-ish users will arrive through Google, not the navigation, so there will still be many links pointing to those pages; perhaps a "deprecated" landing page under "Superseded products and tools" to catch those?

**Comment by usha-mandya** [comment]
Our 404 page currently has the following text. We can add a link to the homepage to help them navigate to main docs site:

"There might be a mistake in the URL or you might’ve clicked a link to content that no longer exists.

If you think it’s the latter, please file an issue at https://github.com/docker/docker.github.io and let us know what happened. Please also include a link to where the error occurred, if applicable."

**Pull request merged**
