### PR TITLE
Admin password update when in debug mode

### PR DESCRIPTION
**Pull request by paigehargrave**

### CODE REVIEW

**Comment by paigehargrave** [comment]
#7815

**Comment by david-yu** [comment]
Hi @bermudezmt the engineering team has stated that the following is the correct way to reset your password: https://success.docker.com/article/recovering-the-admin-password-for-docker-ee-standard-and-advanced#createanotheradminaccount

**Comment by david-yu** [comment]
Actually I was told this is the way to change the password upon further asking: 

```
docker exec -it ucp-auth-api enzi \
  "$(docker inspect --format '{{ index .Args 0 }}' ucp-auth-api)" \
  passwd -i
```

**Comment by bermudezmt** [comment]
@david-yu thank you for doing additional research on your end! @prashshr do the updates look good to you? Let us know so we can get this PR merged. Thanks!

**Comment by bermudezmt** [comment]
@david-yu I tested your suggested command and got an error:
```docker exec -it ucp-auth-api enzi \
>   "$(docker inspect --format '{{ index .Args 0 }}' ucp-auth-api)" \
>   passwd -i
Template parsing error: template: :1:9: executing "" at <.Args>: map has no entry for key "Args"
Error: No such container: ucp-auth-api
```
What has worked instead was @prashshr's original suggestion:
```
docker run --net=host -v ucp-auth-api-certs:/tls -it "$(docker inspect --format '{{ .Spec.TaskTemplate.ContainerSpec.Image }}' ucp-auth-api)" "$(docker inspect --format '{{ index .Spec.TaskTemplate.ContainerSpec.Args 1 }}' ucp-auth-api)" passwd -i
Admin Username: 
```
Are we ok to recommend the above based on my testing?

**Comment by david-yu** [comment]
Yes @bermudezmt please go ahead

**Comment by paigehargrave** [comment]
@bermudezmt - PTAL - I think this is good to go now.

**Pull request merged**
