### PR TITLE
Added Docker for AWS Test channel and release notes

### PR DESCRIPTION
**Pull request by kencochrane**
### Proposed changes
I added a test channel to the Docker for AWS release notes page, and some buttons to use to download the latest test template.

Signed-off-by: Ken Cochrane <KenCochrane@gmail.com>

/cc @FrenchBen

### CODE REVIEW

**Comment by kencochrane** [comment]
Not sure why it failed to deploy to netlify, I click on the link and I don't have access. If someone can let me know what is broken, I can try and fixed.

**Comment by FrenchBen** [comment]
@johndmulhausen ☝️  Can you provide @kencochrane and I with access to this Netlify repo please?

@kencochrane You should be able to do a `docker-compose up` to see what's broken

**Comment by kencochrane** [comment]
@frenchben when I built locally, it worked fine

**Comment by kencochrane** [comment]
@johndmulhausen @mstanleyjones Does this look ok to merge?

**Pull request merged**
