### PR TITLE
landing-page: center navbar on desktop

### PR DESCRIPTION
**Pull request by jdrouet**
### Proposed changes

When the screen is big enough, the navbar is now centered

Screenshot 2020-05-15 at 11 34 02

### CODE REVIEW

**Comment by thaJeztah** [comment]
Hmmm.. unable to get this working on the Netlify preview

I was curious what it looked like as a whole (given that the site itself is left-aligned, so wondering if it feels "natural" to have the navigation centered, but the "TOC" and content left-aligned

**Comment by thaJeztah** [comment]
Oh! or this only on the landing page?

**Comment by thaJeztah** [comment]
Ah, yes, it is: before and after:

Screenshot 2020-05-15 at 12 12 06
Screenshot 2020-05-15 at 12 12 14

**Comment by usha-mandya** [comment]
@thaJeztah Yes, it's the alignment on the landing page.

**Pull request merged**
