### PR TITLE
remove dates from section titles per issue #661

### PR DESCRIPTION
**Pull request by tfoxnc**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Can you link to the issue? Think the issue number is incorrect 😅 (doesn't look related https://github.com/docker/docker.github.io/issues/661)

**Comment by tfoxnc** [comment]
Oops. Sorry about that @thaJeztah. I was waiting for the preview to verify that it rendered properly before merging, and now I don't have merge access since I'm no longer with Docker. I can't find the issue anymore, but it was somewhat urgent so links could be automatically created from within the product. The Netlify preview isn't working for me now.

**Comment by thaJeztah** [comment]
Looks like it needs a rebase 🤔. I can try to have a look tomorrow

**Comment by ahh-docker** [comment]
@ thaJeztah I'm taknig over this PR. Can you let me know if you need the date taken off all the headers, or just previous ones? I don't have a description of what this actually is other than the title. Thanks!

**Pull request closed without merging**
