### PR TITLE
Fix typo in titles

### PR DESCRIPTION
**Pull request by pengsrc**
### Proposed changes

- Fix typo in toc link titles

### CODE REVIEW

**Comment by pengsrc** [comment]
I force pushed my branch to remove the previous commit.

**Comment by akimd** [comment]
I don't have any opinion about this, I am not a native :)

A quick search on Google seem to show that "deploy to Kubernetes" is 6x more frequent than "on".

**Comment by gbarr01** [comment]
Hmmm ... I just saw your comment. I need to think about this some more.

**Comment by gbarr01** [comment]
I am pretty sure that it's deploy _on_ in this case.  I'll make the fix if I am proven wrong.

**Pull request merged**
