### PR TITLE
Update Compose file reference for version 3

### PR DESCRIPTION
**Pull request by dnephin**
Re-doing #716 against vnext-engine

cc @londoncalling

### CODE REVIEW

**Comment by londoncalling** [comment]
LGTM @dnephin @aanand , merging

**Comment by thaJeztah** [comment]
This is going to be confusing if vnext-engine is making changes to the _compose_ documentation (given that there's also a vnext-compose branch https://github.com/docker/docker.github.io/tree/vnext-compose)

Which branch is going to be leading?

**Comment by londoncalling** [comment]
@thaJeztah you are right, this should have been merged into `vnext-compose` , we will fix it

**Comment by londoncalling** [comment]
Reverting this PR and cherry-picking the original changes into `vnext-compose` instead.

**Pull request merged**
