### PR TITLE
Replacing Docker with Moby in several places.

### PR DESCRIPTION
**Pull request by joeabbey**
Next step is to recapture some of the screenshots and issue a PR for them.

### Proposed changes

Several string replacements of Docker to Moby.  The intent is to help out newcomers following the setup instructions to reduce confusion around the naming change.

### CODE REVIEW

**Comment by thaJeztah** [comment]
I'd like to hold off for a bit with these changes until all the components and repositories are in their final location. Most likely, a big part of this contributing guide will have to be moved to the mobyproject.org website (also see https://github.com/moby/moby/issues/32863, and https://forums.mobyproject.org/t/topic-find-a-good-and-non-confusing-home-for-the-remaining-monolith/37/14)

**Comment by mstanleyjones** [comment]
Added a tag just so we won't accidentally merge this. @thaJeztah can you let us know when you will be ready for the  change to go in?

**Comment by mstanleyjones** [comment]
Ping @thaJeztah

**Comment by mistyhacks** [comment]
Hi @joeabbey, this  content has completely changed now and a lot of the contributor's guide now lives in the Moby repo! See https://github.com/moby/moby/tree/master/docs/contributing. With that in mind, I'm going to close this PR. Sorry it took so long!

**Pull request closed without merging**
