### PR TITLE
Update Windows install instructions to support multiple channels

### PR DESCRIPTION
**Pull request by carlfischer1**
add instructions for working with the newly supported multiple version channels

### CODE REVIEW

**Comment by tfoxnc** [comment]
@carlfischer1 Are you still working on this or can I merge it?

**Comment by carlfischer1** [comment]
@tfoxnc we are waiting on MSFT to deploy related changes

**Comment by carlfischer1** [comment]
@tfoxnc this is almost done - can you help me with what's required to use the {win_latest_build} macro?

**Comment by carlfischer1** [comment]
@tfoxnc disregard my request. i need to do one last bit of testing and then this is ready for merge

**Comment by carlfischer1** [comment]
WIP removed from title, ready to merge

**Comment by carlfischer1** [comment]
@tfoxnc can we get this one through?

**Pull request merged**
