### PR TITLE
Add link to vuln scanning cheat sheet

### PR DESCRIPTION
**Pull request by usha-mandya**
Add a URL to the vulnerability scanning cheat sheet

### CODE REVIEW

**Comment by usha-mandya** [comment]
@mkvitnitsky PTAL

**Comment by mkvitnitsky** [comment]
@usha-mandya , looks good

**Comment by usha-mandya** [comment]
Thanks @mkvitnitsky.

**Review by StefanScherer — APPROVED** [review]
LGTM

**Pull request merged**
