### PR TITLE
add in a reboot

### PR DESCRIPTION
**Pull request by bladster**

### CODE REVIEW

**Comment by joaofnfernandes** [comment]
@thaJeztah can you confirm that you need to reboot when installing Docker on CentOS?

**Comment by thaJeztah** [comment]
I don't think a reboot should be needed; @bladster what issue did you have without doing a reboot?

**Comment by johndmulhausen** [comment]
This is not necessary for any distro, and there formatting problems with this PR. At most you may need to reload your equivalent of `~/.bash_profile` so that new aliases etc get picked up. Suggest we close.

**Comment by mstanleyjones** [comment]
Closed due to the concerns of SMEs.

**Pull request closed without merging**
