### PR TITLE
Update Variables to UCP 3.0.3

### PR DESCRIPTION
**Pull request by ollypom**
### Proposed changes

Updated the variables to the latest UCP / DTR releases.

### CODE REVIEW

**Comment by yongshin** [comment]
LGTM

**Comment by yongshin** [comment]
LGTM

**Comment by trapier** [comment]
@ollypom: add UCP 2.0.4? https://github.com/docker/docker.github.io/blob/9d731e7d814eee903a2f6924a6551a6898a8d576/_config.yml#L171

Otherwise, LGTM.  Thanks!

**Comment by ollypom** [comment]
@trapier Thanks :) Added UCP 2.0.4 in last commit.

**Pull request merged**
