### PR TITLE
changed into > in to where applicable

### PR DESCRIPTION
**Pull request by craig-osterhout**
Signed-off-by: craig-osterhout <craig.osterhout@docker.com>

### Proposed changes
Updated all applicable occurrences of "into" to "in to" in the /single-sign-on/index.md topic (Administration > Single Sign-on > Configure).

### Related issues (optional)
ENGDOCS-649

### CODE REVIEW

**Comment by craig-osterhout** [comment]
@jerae-duffin Please help review based on ENGDOCS-649

**Review by jerae-duffin — APPROVED** [review]
LGTM!

**Review by karnatisrinivas — COMMENTED** [review]
/Looks good to me

**Comment by thaJeztah** [comment]
Off-topic, but just noticed: you may want to update your git configuration to use your real name for sign-offs (instead of `craig-osterhout`); it's not enforced in this repository, but I know some repositories may ask you to change it☺️

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
