### PR TITLE
interlock install: hrm->l7 routing

### LINKED ISSUE #7339: interlock ucp screenshot incorrect
location: https://docs.docker.com/ee/ucp/interlock/deploy/

issue: screenshot on this page says `Routing Mesh`.  UCP 3.0.4 UI says `Layer 7 Routing`:

2018-09-07-175925_1526x1088_scrot

### PR DESCRIPTION
**Pull request by trapier**
fixes #7339

### CODE REVIEW

**Comment by trapier** [comment]
shrunk png 120k -> ~50k.

**Comment by ahh-docker** [comment]
@trapier I think this is fixed with a prior merge. Let's take a look next week.

**Comment by trapier** [comment]
> I think this is fixed with a prior merge.

Indeed.  https://github.com/docker/docker.github.io/pull/7301: `Update guide to enabling interlock in the UCP Admin Settings`.

Screenshot here is half the file size of the one on that PR though, so might still be worth merging (part) of this one.

**Comment by trapier** [comment]
nevermind.  would like to change the branch name to reflect reduced scope.  opening a new pr for just image shrinking.

**Pull request closed without merging**
