### PR TITLE
Update resources.md

### PR DESCRIPTION
**Pull request by alfredocambera**
This course isn't receiving new participants.

### Proposed changes

I'm requesting to remove a now invalid link from the list of suggested courses.

### CODE REVIEW

**Comment by thaJeztah** [comment]
@mmorejon PTAL

**Comment by mmorejon** [comment]
Hi @thaJeztah !
The course is not available at this time, I plan to make several updates as soon as possible, but while it is better to be offline to avoid bad experiences.
Thank you for notify me, can be removed from this list for now. I'll let you know as soon as back online.

**Comment by thaJeztah** [comment]
Clear! Thanks for looking @mmorejon, let me merge this PR

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
