### PR TITLE
Adds details about new non-blocking logging mode

### PR DESCRIPTION
**Pull request by cpuguy83**
This functionality was added in docker/docker#28762.
It allows a user to specify what to do in cases when a log message can't
be sent, block the container's stdio or drop messages.

Also removes an erroneous entry about a `nats` log driver, which does
not exist.

### CODE REVIEW

**Comment by cpuguy83** [comment]
ping @thaJeztah

**Comment by mstanleyjones** [comment]
LGTM pending tech review. Where in the world did the `nats` driver content come from??

**Comment by cpuguy83** [comment]
Not sure but it looks like it got cherry-picked in somehow in #1187

**Comment by mstanleyjones** [comment]
The NATS stuff was added in #369. Should I just revert that change? It is my fault because I merged it without realizing that the feature was rejected.

**Comment by mstanleyjones** [comment]
I can't revert #369 cleanly so I'll just merge this one, which effectively does the same thing.

**Pull request merged**
