### PR TITLE
Add markdown lint json file

### PR DESCRIPTION
**Pull request by usha-mandya**
Adding markdown lint json to flag numbered lists
Updated numbered lists to fix copy/paste issues

### CODE REVIEW

**Comment by thaJeztah** [comment]
Is this file only used locally (in your editor), or can we run it in CI?

**Comment by thaJeztah** [comment]
Looks like there's some instructions in this blog to run it with GitHub actions; https://medium.com/@christinavhastenrath/github-actions-markdown-lint-setup-86d7f6ec934d

**Comment by usha-mandya** [comment]
I've installed David Anson's `markdownlint` extension. Currently, the file flags ordered list entries that do not have two spaces.

The blog looks interesting. I'll take a look. Thanks.

**Comment by StefanScherer** [comment]
Good idea, we could add a markdownlint step into the GitHub actions pipeline in #10262 or in a later PR.

**Comment by usha-mandya** [comment]
Added a comment on adding markdown link to GH actions in the Refactor build PR. Let us close this PR and continue any discussions in 10262. Thanks.

**Pull request merged**
