### PR TITLE
Relnotes for Desktop Edge 2110 release

### PR DESCRIPTION
**Pull request by usha-mandya**
- Added Desktop Edge relnotes for 2.1.1.0 release
- Updated the release date for Desktop stable 2.1.0.1 release

### CODE REVIEW

**Comment by usha-mandya** [comment]
Skipped adding the note on restricting the cluster-admin role for kube clusters in Mac Edge release notes as it was already mentioned in 2.1.0.0 - https://docs.docker.com/docker-for-mac/edge-release-notes/#docker-desktop-community-2100

**Comment by khs1994** [comment]
already release? I can't download.

**Comment by usha-mandya** [comment]
> already release? I can't download.

@khs1994 - The Desktop Edge release is available to download. Check out the release notes for more information:

- https://docs.docker.com/docker-for-windows/edge-release-notes/
- https://docs.docker.com/docker-for-mac/edge-release-notes/

**Comment by ulrich** [comment]
Thank @usha-mandya

**Pull request merged**
