### PR TITLE
add go redirect for command-line

### PR DESCRIPTION
**Pull request by thaJeztah**
draft PR to test redirect

### CODE REVIEW

**Comment by thaJeztah** [comment]
Redirect can be tested on https://deploy-preview-11812--docsdocker.netlify.app/go/guides/

**Review by chris-crone — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@nebuk89 is `guides` the most fitting name for this? Where do we want to redirect to ultimately? e.g.

- https://docs.docker.com/get-started/overview/
- https://docs.docker.com/get-started/
- https://docs.docker.com/develop/

**Comment by chris-crone** [comment]
Got the OK from Ben on this

**Comment by thaJeztah** [comment]
moved out of draft

**Review by tiborvass — APPROVED** [review]

**Pull request merged**
