### PR TITLE
Add dirty COW security event

### PR DESCRIPTION
**Pull request by riyazdf**
Adds dirty COW as a security event to docker.

cc @NathanMcCauley @justincormack  @vikstrous 

Signed-off-by: Riyaz Faizullabhoy <riyaz.faizullabhoy@docker.com>

### CODE REVIEW

**Comment by NathanMcCauley** [comment]
Seems most appropriate to add a section here on "Partial Mitigations". On some operating system's this vuln is mitigated by the combination of seccomp filtering of `ptrace` and the fact that /proc/self/mem is RO.

**Comment by justincormack** [comment]
Yes, I think either a partial mitigation section, or at least a note on some reduction in ease/outcome.

**Comment by riyazdf** [comment]
@NathanMcCauley @justincormack: great idea, added a section but left it pretty general.  Please let me know if you'd like me to specifically list OSes or go into more detail

**Comment by justincormack** [comment]
LGTM

**Comment by thaJeztah** [comment]
can you squash your commits?

**Comment by riyazdf** [comment]
@thaJeztah: definitely!  Done

**Pull request merged**
