### PR TITLE
Add missing dollar-sign / consistent shell style

### PR DESCRIPTION
**Pull request by frdmn**
This PR adds a missing `$` in front of one of the installation instructions

### CODE REVIEW

**Comment by johndmulhausen** [comment]
I think our style should be: single commands with no output are not prefaced by a `$`, but snippets that show a mix of both commands and output use `$` to denote the shell prompt.

**Comment by frdmn** [comment]
@johndmulhausen Then it's still not consistent. Check out the next command in the document (`chown`) as well as `rm` at the very bottom. Also single commands with no output but they have indeed a dollar sign prefixed.

**Comment by johndmulhausen** [comment]
@frdmn Agreed that mixing both styles is off; if we are converging on one style for single commands, it should be no `$` prefix. I would gladly accept a PR that enforces that. :)

**Comment by frdmn** [comment]
@johndmulhausen I just pushed my changes into the existing `patch-1` branch:

https://github.com/frdmn/docker.github.io/commit/6ba5d16ea56fd666ce89399d25d75c341afaea2e

I think because the PR is closed the commits are not tracked in here. Let me know if you can reopen it, otherwise I'll raise a new one :)

**Comment by frdmn** [comment]
@joaofnfernandes Let me know what you think or If I did miss anything :)

**Comment by joaofnfernandes** [comment]
Let me try opening the PR again, and see if Github refreshes those changes.
Gotta love some ＄💸🤑

**Comment by johndmulhausen** [comment]
Deploy preview processing.

Built with commit 6ba5d16ea56fd666ce89399d25d75c341afaea2e

https://app.netlify.com/sites/docker-docs/deploys/5824bb2da7e2d24edcd91a2f

**Comment by joaofnfernandes** [comment]
Yup, Github picked those changes, but looks like you need to rebase now 😞

**Comment by frdmn** [comment]
Let me rebase real quick.

**Comment by johndmulhausen** [comment]
Thanks to @joaofnfernandes for stepping in while I was out and to @frdmn for this work. Sorry for all the churn, normally simple fixes like this go much more smoothly. Hope it doesn't discourage you from contributing in the future. :)

**Comment by frdmn** [comment]
No worries and thanks for the merge 👌

Von meinem iPhone gesendet

**Pull request merged**
