### PR TITLE
ENGDOCS-2300

### PR DESCRIPTION
**Pull request by aevesdocker**
## Description

Final PR to improve the DD IA. 

Validate test failing due to link that needs fixing in an upstream repo 

## Reviews

- [ ] Technical review
- [ ] Editorial review
- [ ] Product review

### CODE REVIEW

**Review by sarahsanders-docker — DISMISSED** [review]
LGTM

**Review by dvdksn — CHANGES_REQUESTED** [review]
Please update the broken link upstream before merging this

**Comment by dvdksn** [comment]
We also need the upstream fix to be merged first, backported to the release branch, and then vendor the updates before we can merge this. Otherwise all CI tests will fail.

**Comment by dvdksn** [comment]
@aevesdocker for sure, let's just get the upstream merged first. I can open the backport too

**Review by dvdksn — APPROVED** [review]
LGTM

**Pull request merged**
