### PR TITLE
[WIP] Update use-nfs-volumes.md

### PR DESCRIPTION
**Pull request by kavikat**
Adding instructions for using NFS volumes with Swarm. (Work in progress)

### CODE REVIEW

**Comment by ahh-docker** [comment]
@kavikat Please let us know if this is a WIP or ready for editorial review. Thanks!

**Comment by bermudezmt** [comment]
Still a WIP as of 01/17/2019. cc: @kavikat

**Comment by adrian-plata** [comment]
@kavikat is this information still relevant? The original page appears to have been deleted so it may be simplest to create another PR adding a new page.

**Comment by usha-mandya** [comment]
Closing the PR as it relates to UCP

**Pull request closed without merging**
