### PR TITLE
Move open source registry to top-level side-bar navigation

### PR DESCRIPTION
**Pull request by thaJeztah**
This topic was moved under 'open source' because it confused users looking for the Enterprise products (DTR). This should no longer be a problem, so we should be able to move it back for easier discovery.

Also rephrased some TOC titles, and changed a page-title.

### CODE REVIEW

**Comment by thaJeztah** [comment]
@usha-mandya @justincormack ptal

**Comment by usha-mandya** [comment]
@thaJeztah The overview page states Docker Registry is open source. Wondering if it makes sense to retain it under Open source?

**Comment by thaJeztah** [comment]
engine and cli are also open source, so not sure we need to make the distinction. Open to suggestions though: perhaps @justincormack has thoughts on this

**Comment by justincormack** [comment]
Please do not do this.

**Pull request closed without merging**
