### PR TITLE
fixed absolute links

### PR DESCRIPTION
**Pull request by aduermael**
### Proposed changes

Fixed absolute links in current version's content for new tests in #849  to pass.

### CODE REVIEW

**Comment by sanscontext** [comment]
Does this actually work without breaking these links in the Docker Cloud docs? I wasn't aware that HTML would allow relative links on `target="_blank"` anchors.  

(For reference, I'm making a specific design decision in the Cloud docs to open a new tab so that the reader isn't distracted from a tutorial flow. This modifier isn't supported by markdown, which is why it's in HTML.)

**Comment by aduermael** [comment]
@sanscontext 
>  I wasn't aware that HTML would allow relative links on target="_blank" anchors.

I assume it works... Can you point me to a page that could bring that kind of issue?

**Comment by aduermael** [comment]
@sanscontext 
I just tried this link in `/docker-cloud/builds/push-images/`:
screen shot 2016-12-14 at 12 20 15 pm

It opens a new tab, even with a relative link.

**Comment by sanscontext** [comment]
Sorry, I'd been waiting for the Netlify preview to show up - forgot it's now hidden three clicks deep. :P  All my specific links appear to be working!

**Comment by aduermael** [comment]
ping @johndmulhausen

**Comment by johndmulhausen** [comment]
Thanks, @aduermael :)

**Comment by aduermael** [comment]
thanks @johndmulhausen!

**Pull request merged**
