### PR TITLE
Clarification on removing nodes from Cluster

### PR DESCRIPTION
**Pull request by david-yu**
Adding confirmation to show that node is shut down or left the swarm.

### CODE REVIEW

**Comment by ahh-docker** [comment]
@yongshin Thanks. Do we need a screenshot for this? I think that would be a big help. Thanks.

**Comment by yongshin** [comment]
screen shot 2018-09-24 at 9 12 12 pm

**Comment by yongshin** [comment]
image

**Comment by ahh-docker** [comment]
Approving with @bermudezmt

**Pull request merged**
