### PR TITLE
Shorten the templates a bit

### PR DESCRIPTION
**Pull request by mstanleyjones**
### Describe the proposed changes

Shrank the templates a bit

### Project version

n/a

### Related issue

n/a

### Related issue or PR in another project

n/a

### Please take a look
@docker/docs-maintainers

### CODE REVIEW

**Comment by sanscontext** [comment]
Maybe some grammar nits, but the reduction in wall-o-text LGTM. :)

**Comment by mstanleyjones** [comment]
@sanscontext nit away! Always open to suggestions.

**Comment by sanscontext** [comment]
Tiny ones, I'll just add a GH-side edit. :)

**Comment by mstanleyjones** [comment]
Looks fine to me.

**Comment by johndmulhausen** [comment]
LGTM; shorter is better. 👍

**Pull request merged**
