### PR TITLE
Updated Billing events

### PR DESCRIPTION
**Pull request by jerae-duffin**
Added a table for Event description

### CODE REVIEW

**Review by leslielylee — CHANGES_REQUESTED** [review]
I like Amanda's suggestion to change "Seat Downgrade Cancelled" to "Seat Removal Cancelled".

Could we also change the descriptions for some of the events to be more consistent with the event names that contain "added" or "removed"? Specifically:

- Change description for Seat Added to "Billing seat added events"
- Change description for Seat Removed to "Billing seat removed events"
- Change description for Seat Removal Cancelled to "Billing cancel seat removal events"

**Review by leslielylee — CHANGES_REQUESTED** [review]
Event name changes:
- Change from "Seat Downgrade Cancelled" to "Seat Removal Cancelled"

Description changes:
- Change from "Billing seats upgrade events" to "Billing seat added events"
- Change from "Billing seat downgrage events" to "Billing seat removed events"
- Change description for "Billing seat cancel downgrade events" to "Billing cancel seat removal events"

I've updated these in the [Audit Log List page in Notion](https://www.notion.so/dockerinc/Audit-Log-List-8d1b669c158d49528f3931cf4f64c4f5#492eb55238e64919a0ba169029a2dc81) too, hope that helps!

**Comment by jerae-duffin** [comment]
Thank you! @leslielylee Good catch! We use American standard for spelling =)

**Review by leslielylee — APPROVED** [review]
LGTM, thank you!

**Review by craig-osterhout — APPROVED** [review]
LGTM

**Pull request merged**
