### PR TITLE
add warning class and a linebreake to the warning blogquote

### PR DESCRIPTION
**Pull request by tippexs**

### CODE REVIEW

**Comment by joaofnfernandes** [comment]
Relates to #2781

**Comment by johndmulhausen** [comment]
@tippexs You need to revert these four commits; the YAML files are automatically generated from the source at moby/moby:

```
 @tippexs	Update dockerd.yaml  …			3a98eb8
 @tippexs	Update docker_secret_rm.yaml  …			4c454b8
 @tippexs	Update docker_service_rm.yaml  …			a983380
 @tippexs	Update docker_secret_rm.yaml  …			5dc1e75
```

**Comment by joaofnfernandes** [comment]
I've reverted the changes to `_data/*` and rebased. Once the tests pass, I'll squash and merge. #ShipIt

**Comment by joaofnfernandes** [comment]
I've rebased again

**Pull request merged**
