### PR TITLE
Patch UCP Azure instructions 

### PR DESCRIPTION
**Pull request by ollypom**
### Proposed changes

I have moved the warning to ensure a pod-cidr is within an Azure Subnet more obvious.

### CODE REVIEW

**Comment by ollypom** [comment]
@dockerpac WDYT?

**Comment by ollypom** [comment]
Ahhh I've just seen you made https://github.com/docker/docker.github.io/pull/8484. 

I kept the note within the installation instructions, however now made it bold in a markdown note. The reason I've kept it in the `Install UCP` section, is because the Pod-Cidr is not defined until down at the top of the page, only within the install section :)

**Comment by dockerpac** [comment]
Ok that makes sense.
Still I think it should be also noted in the "Prerequisites paragraph" because basically, if i'm not aware of this restriction, i could want to install my nodes in a small vnet, and use the default 192.168.0.0/16 overlay network for pods cidr as in all other docker ee installations.
So for my point of view, with this information in mind, you would know at the design phase (not at the installation phase) that you need to provision a vnet large enough to have your nodes but also all of your pods.
This is explained in details in the paragraph "Considerations for IPAM Configuration", but I think it should be also explicitly put in the "Prerequisites" paragraph

**Comment by ollypom** [comment]
@dockerpac Ok that makes sense, I've added a section specifically calling out the vnet/subnet sizes in the Pre-reqs, and referencing the "Considerations for IPAM Configuration".

WDYT?

**Comment by dockerpac** [comment]
👍

**Pull request merged**
