### PR TITLE
WIP: experiments with glyphicons in admonitions (notes)

### PR DESCRIPTION
**Pull request by londoncalling**
### What's changed

- Per today's Docs meeting, experimenting with replacing admonitions prefixed text with Bootstrap Glyphicons

- Pros, cons, examples, and implementation details of first try are all in`test.md` file at this Netlify link: https://deploy-preview-3231--docker-docs.netlify.com/test/#admonitions-notes

- **_This is a work-in-progress, please but do not merge yet, but please review and let me know what you think._**

### Reviewers

@johndmulhausen @mstanleyjones @joaofnfernandes @jsouth 

### Related 

Tangentially related, PR #3225 will need to use the new admonition formats once we settle this.

Signed-off-by: Victoria Bialas <victoria.bialas@docker.com>

### CODE REVIEW

**Comment by mstanleyjones** [comment]
Hi @londoncalling, I think you can use the `:before` to attach the whole glyphicon string (from `<i>` to `</i>` to a class, by setting `content:`. @johndmulhausen is more of an expert than I am.

**Comment by londoncalling** [comment]
I can try it. Everything I've tried and read up on so far says there is not
a way to do it.

**Comment by mstanleyjones** [comment]
There are a few other approaches. You can look in the bootstrap CSS and see what their CSS looks like for the glyphicon you like, and just copy that into the note CSS. Or you can use Javascript to add the class (like `glyphicon glyphicon-exclamation-sign`) on page load. https://api.jquery.com/addclass/

**Comment by londoncalling** [comment]
@johndmulhausen well, I guess it's halfway there. Check out the test with the includes and Liquid at https://deploy-preview-3231--docker-docs.netlify.com/test/#test-liquid-admonitions (after it's rebuilt). I'll finish this up tomorrow. I can't get the first title to format in proper font size and colour, but the rest looks good. If we get this working, I will remove all the extra stuff from the CSS.

**Comment by londoncalling** [comment]
LGTM

**Pull request merged**
