### PR TITLE
UCP 3.2.6 release notes

### PR DESCRIPTION
**Pull request by traci-morrison**
### Proposed changes
- https://docs.docker.com/ee/ucp/release-notes/
- Add information for UCP 3.2.6, 3.1.13, and 3.0.17

### Related issues (optional)
- https://mirantis.jira.com/browse/ENGDOCS-366

### CODE REVIEW

**Comment by traci-morrison** [comment]
@Dawn-Wood @ry4nz @usha-mandya PTAL.

**Comment by usha-mandya** [comment]
@traci-morrison Do you want to update the config yaml to bump the UCP version number?

**Comment by traci-morrison** [comment]
> @traci-morrison Do you want to update the config yaml to bump the UCP version number?

Hi @usha-mandya  I don't recall doing that for past release notes. Can you show me where that needs to be updated? Thanks.

**Comment by usha-mandya** [comment]
> > @traci-morrison Do you want to update the config yaml to bump the UCP version number?
> 
> Hi @usha-mandya I don't recall doing that for past release notes. Can you show me where that needs to be updated? Thanks.

Here's an example - https://github.com/docker/docker.github.io/pull/10234

**Comment by traci-morrison** [comment]
> > > @traci-morrison Do you want to update the config yaml to bump the UCP version number?
> > 
> > 
> > Hi @usha-mandya I don't recall doing that for past release notes. Can you show me where that needs to be updated? Thanks.
> 
> Here's an example - #10234

Thanks @usha-mandya. @ry4nz Are the links for the tar-files available?

**Pull request merged**
