### PR TITLE
Update seccomp.md

### LINKED ISSUE #6854: Update `name_to_handle_at` syscall capability gate to `CAP_DAC_READ_SEARCH`
As mentioned by @justincormack  in issue moby/moby#37242:
`name_to_handle_at` syscall capability needed to be updated to "Already gated by `CAP_DAC_READ_SEARCH`."

File: [engine/security/seccomp.md](https://docs.docker.com/engine/security/seccomp/)

### PR DESCRIPTION
**Pull request by nvcastet**
Fix #6854
Signed-off-by: Nicolas V Castet nvcastet@us.ibm.com

### CODE REVIEW

**Comment by nvcastet** [comment]
ping @justincormack

**Comment by nvcastet** [comment]
@thaJeztah @justincormack Here is the fix for the CAP_SYS_NICE documentation.

**Comment by thaJeztah** [comment]
@tfoxnc note that the associated change in moby was merged to master, but is not currently staged for 18.06

**Comment by nvcastet** [comment]
@thaJeztah @tfoxnc The current documentation is currently incorrect independently of the moby change. 
If we wanted to have the documentation matching the current docker version, we will need this doc change + another change removing the references to "CAP_SYS_NICE gating system call" because before the moby fix, it is not the case.

**Comment by nvcastet** [comment]
@justincormack Could we merge this PR to fix this typo in the documentation?

**Comment by ahh-docker** [comment]
Merging with @bermudezmt

**Pull request merged**
