### PR TITLE
Add migration V1 -> V2 info

### PR DESCRIPTION
**Pull request by ulyssessouza**
### Proposed changes
Add V1 -> V2 migration notes

### CODE REVIEW

**Review by StefanScherer — APPROVED** [review]
LGTM

**Review by mat007 — COMMENTED** [review]
Nothing about environment variables, or variable substitution?
Are we assuming V2 should have the same behaviour us V1 now?

**Comment by ulyssessouza** [comment]
@mat007 The differences I had on my list are already fixed. I'm maybe missing something, but from what I remember that's conceptually the same now. If there are differences they should be considered as bugs

**Review by mat007 — APPROVED** [review]

**Comment by ulyssessouza** [comment]
@mat007 And also, we can do that incrementally with followup PRs like this one

**Pull request merged**
