### PR TITLE
Publish updates from master

### PR DESCRIPTION
**Pull request by usha-mandya**
Publish updates from master

### CODE REVIEW

**Comment by thaJeztah** [comment]
We should probably include https://github.com/docker/docker.github.io/pull/15243 as well

**Comment by thaJeztah** [comment]
https://github.com/docker/docker.github.io/pull/15243 was merged 👍

**Review by thaJeztah — APPROVED** [review]
LGTM

checked some of the redirects, and they worked

**Review by jerae-duffin — APPROVED** [review]
LGTM!

**Pull request merged**
