### PR TITLE
Add username and password in 'Build and push' of configure-ci-cd.md

### PR DESCRIPTION
**Pull request by Sammeeey**
### Proposed changes

I've added the username and password references in the 'Build and push' step of ['Set up the GitHub Actions workflow'](https://docs.docker.com/language/python/configure-ci-cd/#set-up-the-github-actions-workflow) in the Python language guide.
The 'CI to Docker Hub' action didn't  work for me without it.

The changes are inspired by ['GitHub Actions Tutorial - Basic Concepts and CI/CD Pipeline with Docker (YouTube)'](https://youtu.be/R8_veQiYBjI?t=1860)

### Related issues (optional)

Fixes parts of #13157 (description still not intuitively clear, but functionality is solved - as long as people understand what to do)

### CODE REVIEW

**Comment by usha-mandya** [comment]
@crazy-max Could you PTAL?

**Comment by thaJeztah** [comment]
Isn't that what the `docker/login-action@v1` is for? 🤔 https://github.com/docker/docker.github.io/blame/d179ba05f96eb87f1924bc7d68622395ddd8b2f5/language/python/configure-ci-cd.md#L143-L147

**Comment by crazy-max** [comment]
It's done through the `docker/login-action@v1` yes. `username` and `password` inputs don't exist in `docker/build-push-action@v2`.

**Comment by Sammeeey** [comment]
@crazy-max 
Thank you.
But can you then explain why the login seems to work with the changes I made but not with the original approach from the language guide?

I've described the Error in #13157 (below EDIT)

**Comment by crazy-max** [comment]
@Sammeeey 

> But can you then explain why the login seems to work with the changes I made but not with the original approach from the language guide?

I don't see how it could work. Do you have a link to your repo?

**Comment by thaJeztah** [comment]
> I don't see how it could work. Do you have a link to your repo?

Perhaps the repo is public, and removing the credentials from one step (therefore authentication not failing), and moving it to the other one (which ignores the username/password) makes it "work" because it's no longer authenticating, and just doing an anonymous pull?

**Comment by thaJeztah** [comment]
Actually, that wouldn't work, because this is for pushing 🤔 ?

**Comment by Sammeeey** [comment]
> 
> 
> @Sammeeey
> 
> > But can you then explain why the login seems to work with the changes I made but not with the original approach from the language guide?
> 
> I don't see how it could work. Do you have a link to your repo?

Yes, of course:
[Here is the repo](https://github.com/Sammeeey/SimpleWhaleDemo) with the changes in the [github_registry.yml](https://github.com/Sammeeey/SimpleWhaleDemo/commit/44f4160045e30faac21a43231ccc040ceae1c2de)

**Comment by crazy-max** [comment]
@Sammeeey Looking at [your workflow](https://github.com/Sammeeey/SimpleWhaleDemo/blob/44f4160045e30faac21a43231ccc040ceae1c2de/.github/workflows/github_registry.yml) you're using the [login-action](https://github.com/Sammeeey/SimpleWhaleDemo/blob/44f4160045e30faac21a43231ccc040ceae1c2de/.github/workflows/github_registry.yml#L17-L21) and [Login succeeded](https://github.com/Sammeeey/SimpleWhaleDemo/runs/3131397638?check_suite_focus=true#step:3:7) with it:

image

Also as I said https://github.com/docker/docker.github.io/pull/13214#issuecomment-885530655,  `username` and `password` inputs don't exist in `docker/build-push-action@v2` and it's [clearly shown](https://github.com/Sammeeey/SimpleWhaleDemo/runs/3131397638?check_suite_focus=true#step:5:1) in the build output:

image

So I guess in the [previous build that failed](https://github.com/Sammeeey/SimpleWhaleDemo/runs/3028349773?check_suite_focus=true) your credentials were incorrect.

**Comment by Sammeeey** [comment]
@crazy-max 
Okay, you are completely right - thank you!
I've removed the lines again and it works now.
I can't remember that I changed the credentials within the process before.

Hence this problem seems to be solved - since it's actually no problem.

However parts of the description in that part of the docs still seem not completely clear from my point of view.
Anyway they may not be meant to be discussed here - but rather in #13157

**Comment by thaJeztah** [comment]
Thanks both, for getting to the root of this. Let me close this PR, and we can continue on https://github.com/docker/docker.github.io/issues/13157

**Pull request closed without merging**
