### PR TITLE
Fix URL for design proposal PRs

### LINKED ISSUE #205: Open source workflow: bring up-to-date, design proposal not a `docker/docker` label anymore
At https://docs.docker.com/opensource/workflow/advanced-contributing/#/design-proposal, the design proposal PR link is broken (extra `%20`s) and no label `kind/proposal` exists in [docker/docker](https://github.com/docker/docker). This text is out-of-date or wrong.

### PR DESCRIPTION
**Pull request by shubheksha**
### Related issues (optional)
Fixes #205

### CODE REVIEW

**Comment by shubheksha** [comment]
@londoncalling, what's up with the CI on this PR?

**Comment by londoncalling** [comment]
@shubheksha yes I'm not sure. Can you make some minor change and push again? Even add a space at the end of a line or something if you don't have other tweaks?

**Comment by londoncalling** [comment]
@shubheksha it's a problem with Netlify. I'll fix it asap, sorry. It's blocking a PR of mine too.

**Comment by londoncalling** [comment]
LGTM

**Pull request merged**
