### PR TITLE
Macos client binaries

### PR DESCRIPTION
**Pull request by paigehargrave**
#8229

### CODE REVIEW

**Comment by JL2210** [comment]
This is still under `install/linux`. Maybe move it to `install/macos`?

**Comment by bermudezmt** [comment]
Hey @JL2210 - we are working on a larger content restructure which will move this to a macOS-specific location. In the meantime, this is @paigehargrave 's interim fix to hopefully lessen confusion. I'm closing #8229 in favor of this PR. Thank you for bringing this to our attention, please check back in a few months after our content refactor is complete to make sure this is resolved to your satisfaction.

**Comment by JL2210** [comment]
Just a quick question, can you build Docker without Docker installed? I'm
trying to install Docker in a system where every directory in the
filesystem but /usr/local and /home are read-only.

**Comment by bermudezmt** [comment]
@JL2210 We don't believe that is supported by Docker but here's a couple resources you can check out:

- https://stackoverflow.com/questions/47708983/build-docker-image-without-docker-installed
- https://jvns.ca/blog/2016/10/26/running-container-without-docker/

For additional assistance, please feel free to start a discussion on the Docker Forums at https://forums.docker.com.

**Pull request merged**
