### PR TITLE
updates per machine docs pr#3799

### PR DESCRIPTION
**Pull request by londoncalling**
@nathanleclaire @ mrburrito please review these changes to AWS driver docs, same as on [Update AWS Credentials lookup to use AWS default provider chain](https://github.com/docker/machine/pull/3799).

@nathanleclaire can these changes be published on docs site, or do we have to wait for future release with regard to any driver code changes?

Signed-off-by: Victoria Bialas <victoria.bialas@docker.com>

### CODE REVIEW

**Comment by londoncalling** [comment]
closing, dev already submitted https://github.com/docker/docker.github.io/pull/37

**Comment by nathanleclaire** [comment]
Should I ask them to take the changes out of the Machine PR?

**Comment by londoncalling** [comment]
@nathanleclaire I think they already did. We duplicated the PRs to github.io, so I closed mine (this one) and didn't merge it. The new dev-created PRs are merged already to github.io (see https://github.com/docker/docker.github.io/pull/37 and https://github.com/docker/docker.github.io/pull/36) and up on docs.docker.com: https://docs.docker.com/machine/drivers/aws/

I think it's all good, unless you still see these same docs updates on the Machine repo in an open PR, then yes you can remove them, but I believe we are about to scrub that docs repo and replace it with a README if we haven't done so already.

Ping @johndmulhausen , are you about to also nuke: https://github.com/docker/machine/tree/master/docs and leave the README there?

For now, I think we could manage that single `docs/reference/` folder over on https://github.com/docker/docker.github.io/tree/master/machine until we have automated CLI docs generation.

**Comment by johndmulhausen** [comment]
@nathanleclaire @londoncalling Yes, I have this PR to do the nuking: https://github.com/docker/machine/pull/3804

**Comment by mrburrito** [comment]
@nathanleclaire do you want me to remove the docs changes from the machine PR? I figured I'd leave them in until docs were completely migrated to the common location.

**Pull request closed without merging**
