### PR TITLE
overflow the highlighter rouge code tag

### PR DESCRIPTION
**Pull request by anagio**
### Related issues 
Fixes issues:   #3237

### CODE REVIEW

**Comment by mstanleyjones** [comment]
@johndmulhausen PTAL

**Comment by johndmulhausen** [comment]
Doesn't look right to me:
https://deploy-preview-3239--docker-docs.netlify.com/compose/install/

@anagio Can you do more to hide the scrollbars when they aren't needed?

**Comment by anagio** [comment]
@johndmulhausen sure, i'm seeing two types of scrollbars I may have missed some styles. I'll send an update

**Comment by johndmulhausen** [comment]
@anagio Any news here?

**Comment by johndmulhausen** [comment]
Closing. I think we're overflowing properly. When we don't need scrollbars we don't have them, when we do, we do.

**Pull request closed without merging**
