### PR TITLE
Update Ruby, Rails versions in rails.md

### PR DESCRIPTION
**Pull request by gsaraf**
### Proposed changes
While following the guide I noticed it was using old versions of Ruby and Rails. So updating :)

Rails 6 requires Yarn, the source of which needs to be added to apt. See installation instructions https://classic.yarnpkg.com/en/docs/install/#debian-stable

Tested by following instructions and getting to working Rails setup.

### Unreleased project version (optional)
None :)

### Related issues (optional)
None :)

### CODE REVIEW

**Comment by gsaraf** [comment]
Hi! Some time has passed - what should I do to get this reviewed?

Not super critical, just a small addition that will make it easier for future people :)

**Comment by JJ** [comment]
There's apparently a conflict now...

**Comment by gsaraf** [comment]
@JJ - Thanks, I've fixed the merge conflict.

**Comment by gsaraf** [comment]
Closing to clean up my queue.

**Pull request closed without merging**
