### PR TITLE
Update json-file.md

### PR DESCRIPTION
**Pull request by freesoft**
### Proposed changes

Added a section for Docker for Mac to find docker container's log file, which isn't defined or specified in current documentation.

### CODE REVIEW

**Comment by freesoft** [comment]
I'm not sure what to do to pass that deploy/netlify check. Can someone tell me what to do?

**Comment by mstanleyjones** [comment]
This is unsupported so we can't document it. If you need the info yourself, maybe you can put it into a Gist or on a blog. Sorry!

**Comment by freesoft** [comment]
If logging in Docker for Mac isn't supported, how I was able to find the log in there?

**Comment by mstanleyjones** [comment]
@dsheets PTAL, am I incorrect?

**Comment by dsheets** [comment]
While retrieving the logs by logging into the VM is possible, we don't support this method of interacting with the product. Instead, we recommend (and support) retrieving logs with something like:

```
$ CONTAINER_ID=45f1f00f0e2b9dae791351a409ed71feaef62776270161b1bc4c190bbc4fec81
$ docker run -it --rm -v /var/lib/docker/containers/${CONTAINER_ID}/${CONTAINER_ID}-json.log:/log alpine cat /log
```

**Comment by mstanleyjones** [comment]
@freesoft do you mind updating your PR to use @dsheets suggested approach?

**Comment by freesoft** [comment]
Sure. I'll do it shortly.

**Comment by mstanleyjones** [comment]
@freesoft If you get a chance to update the PR that would be great. It would be good to have this info out there, in a way that is supported. Thanks!

**Comment by johndmulhausen** [comment]
@freesoft Any updates here?

**Comment by mstanleyjones** [comment]
Out of date. Please open a new PR if you decide to continue working on this.

**Pull request closed without merging**
