### PR TITLE
Get started updates

### PR DESCRIPTION
**Pull request by bpelikan**
### Proposed changes

Changing repository name from image tag to be te same as created repository name.
(Two repositories were being created at the moment)

### CODE REVIEW

**Comment by bpelikan** [comment]
@DawnWood-Docker

**Comment by DawnWood-Docker** [comment]
@bpelikan looking into it now

**Comment by bpelikan** [comment]
@DawnWood-Docker 
`Part6.md` is still in the repository so it's accesible at https://docs.docker.com/get-started/part6/.
The content is not up to date with the current version, so I think it should be removed

**Comment by DawnWood-Docker** [comment]
@bpelikan you are absolutely right. I'm working on the redirects today.

**Comment by bpelikan** [comment]
@DawnWood-Docker Ok, so I deleted this file, because it is unnecessary with current version.

**Comment by DawnWood-Docker** [comment]
Hey again @bpelikan We decided to change line 35 in part5.md "Fill out the Repository Name as **bulletinboard**".  The retag is meant to make the point that you have to add your dockerID so it's a bit cleaner to do it this way. Thank you *very much* for pointing this error out.

**Comment by bpelikan** [comment]
@DawnWood-Docker Great to hear that! But Keep in mind that screenshot also should be replaced to point bulletinboard 😉

**Comment by DawnWood-Docker** [comment]
@bpelikan You are so right!! I will do that today. Appreciate it!!

**Pull request closed without merging**
