### PR TITLE
Correct swarm init default-address-pool to default-addr-pool

### PR DESCRIPTION
**Pull request by trapier**
### What I did:

```
git grep -l default-address-pool  |\
xargs sed -i 's:default-address-pool:default-addr-pool:g'
```

### References:

client version 18.09.3.

```
$ docker swarm init --help |grep -- '--default-addr.*-pool '
      --default-addr-pool ipNetSlice           default address pool in CIDR format (default [])
```

### CODE REVIEW

**Comment by trapier** [comment]
brush probably too broad (server 18.09.3):

```
$ dockerd --help |grep default-addr
      --default-address-pool pool-options       Default address pools for node specific local networks
```

**Comment by trapier** [comment]
Updated to apply to `docker swarm init` docs only.

**Comment by traci-morrison** [comment]
@DawnWood-Docker PTAL.

**Comment by traci-morrison** [comment]
> merge conflict

Right, this is on hold until I can work with @trapier to get the merge conflict resolved. It dropped on the priority list. Thanks.

**Comment by trapier** [comment]
Rebased and addressed merge conflict.

**Comment by DawnWood-Docker** [comment]
lgtm!

**Pull request merged**
