### PR TITLE
fixed link in voting app tutorial

### PR DESCRIPTION
**Pull request by londoncalling**
@mstanleyjones @ManoMarks 

Just fixed a link to go to Mano's voting app in the labs.

Signed-off-by: Victoria Bialas <victoria.bialas@docker.com>

### CODE REVIEW

**Comment by ManoMarks** [comment]
LGTM

**Comment by londoncalling** [comment]
@ManoMarks thanks, there's a problem w/Jenkins I think related to the rebases earlier tonight.

@johndmulhausen @mstanleyjones (also waiting on ability to merge Piñata 1.13.0 docs for same reason)

**Comment by mstanleyjones** [comment]
Did you mean to close this? I can help you make it mergable.

**Comment by mstanleyjones** [comment]
I'll wait for Netlify and merge if it's green.

**Comment by mstanleyjones** [comment]
@londoncalling John is working on Jenkins. Can you verify that this PR has the right changes? When I look at the diff I can't really see a difference between the red and green line.

**Comment by johndmulhausen** [comment]
Thanks, @londoncalling 

I don't see a URL change but I do see that the [] and () are on the same line; perhaps that was causing the problem.

**Pull request merged**
