### PR TITLE
Via @thaJeztah we no longer support Wheezy

### PR DESCRIPTION
**Pull request by fxdgear**
https://github.com/docker/docker/issues/15692#issuecomment-174098882

### CODE REVIEW

**Comment by thaJeztah** [comment]
Hm, actually, I may have been mistaken there (sorry it's been a while), I thought it was discussed at some point, but not sure what the current status is. Not sure if we should _recommend_ it though, with "stretch" probably becoming the current version soon

**Comment by fxdgear** [comment]
> Not sure if we should recommend it though

So maybe we should remove it from the docs? And then if people want to use it they can.

**Comment by mstanleyjones** [comment]
@fxdgear as I pointed out, there are additional steps for Wheezy that we can't pull until we no longer support it.

**Comment by mstanleyjones** [comment]
Closing for now. Sorry about the confusion.

**Pull request closed without merging**
