### PR TITLE
Moving NFS persistent storage info

### PR DESCRIPTION
**Pull request by paigehargrave**
Moving https://docs.docker.com/ee/ucp/admin/configure/use-nfs-volumes/ to the 'Deploy apps with Kubernetes' section.

### CODE REVIEW

**Comment by paigehargrave** [comment]
@mark-church Hi Mark, this is related to https://github.com/docker/docs-private/issues/795. PTAL and see if where I put this makes sense. Very sorry for the delayed response on this.

**Comment by mark-church** [comment]
@paigehargrave this is better but the docs under Swarm and K8s are still a flat list with no organization. It's becoming a dumping ground for unrelated topics. We need to have some more organization. The Openshift docs are a good example: https://docs.google.com/presentation/d/1NI-x0X5wcdPjHP6Xb3gpuLwoMgTIso8wHRXYPTRT9vI/edit?usp=sharing

They are organized something like:

- Architecture
  - User Management
  - Networking
  - Storage
  - ...
- Configuration
  - User Management
  - Networking
  - Storage
  - ...
- Operations
  - User Management
  - Networking
  - Storage
  - ...


We have a bigger challenge because we have two separate orchestrators in the product. We need to move to a more organized layout. I would suggest that topics that are not orchestrator specific lie in general areas and that the orchestrator specific topics are underneath each orchestrator. Something like:

- Installation
- Configuration
  - Swarm
     - Storage
         - topic 1
         - topic 2
     - Networking
         - topic 1
         - topic 2
  - Kubernetes
     - Storage
         - topic 1
         - topic 2
     - Networking
         - topic 1
         - topic 2
- Operations
  - Swarm
     - topic 1
     - topic 2
  - Kubernetes
     - topic 1
     - topic 2

**Comment by paigehargrave** [comment]
@mark-church - Thank you for looking at this! Let me get with Maria and see what we can do.

**Comment by paigehargrave** [comment]
@mark-church Are you OK with us merging this fix as an interim solution, and then leaving the original issue open and labelling it for the refactor?

**Comment by mark-church** [comment]
Yes sorry I forgot to mention that, go ahead and thank you!

**Comment by paigehargrave** [comment]
@mark-church OK - thank you! I've copied your comments to the original issue for the refactor.

**Pull request merged**
