### PR TITLE
Update compose cli documentation to version v2.4.0

### PR DESCRIPTION
**Pull request by glours**
Signed-off-by: Guillaume Lours <guillaume.lours@docker.com>

### Proposed changes
Update Compose cli reference documentation to match the changes coming with version `v2.4.0`

### CODE REVIEW

**Comment by thaJeztah** [comment]
do we need to wait with merging until it shipped with docker desktop?

**Comment by usha-mandya** [comment]
@thaJeztah I don't think we need to wait. Let's try to get this out. @glours WDYT?

**Comment by thaJeztah** [comment]
mostly wondering if users will get confused if they try the ssh feature on docker desktop, and find it doesn't work 😅

**Comment by usha-mandya** [comment]
@thaJeztah Makes sense. Let's merge with for the Desktop 4.7 release. I'll update the description so we don't accidentally merge the PR.

**Comment by glours** [comment]
Yes I agree with @thaJeztah, we should wait for the next Desktop release to publish those changes

**Pull request merged**
