### PR TITLE
live-restore not compatible with any type of swarm

### PR DESCRIPTION
**Pull request by trapier**
Intent is to make it clearer that live-restore is incompatible with both swarm
mode and standalone swarm.

Signed-off-by: Trapier Marshall <trapier.marshall@docker.com>

### CODE REVIEW

**Comment by trapier** [comment]
Thanks for the edit. Please hold off on merging. May have been premature and have a caveat from the Swarm classic team.

**Comment by mstanleyjones** [comment]
Ping.

**Comment by johndmulhausen** [comment]
@trapier Do you still want us to hold off on merging?

**Comment by mstanleyjones** [comment]
@trapier what's the news here?

**Comment by trapier** [comment]
Didn't get a concrete answer on this, so closing it out.  Sorry for the delay.

**Pull request closed without merging**
