### PR TITLE
[WIP] machine: Document --google-service-account flag

### PR DESCRIPTION
**Pull request by pschultz**
### Proposed changes

Document the `--google-service-account` flag introduced in docker/machine#4527.

### Unreleased project version (optional)

The option is not released yet. This PR is based on the vnext-machine branch.

### CODE REVIEW

**Comment by bermudezmt** [comment]
@JustinINevill since we haven't worked on `vnext` branches for other products, can we discuss before merging this PR?

**Comment by bermudezmt** [comment]
@L-Hudson I have added "WIP" to the title for now so this doesn't get merged. We should discuss with @JustinINevill at our next team meeting.

**Comment by bermudezmt** [comment]
@chris-crone FYI.

**Comment by paigehargrave** [comment]
@bermudezmt - Is this OK to merge now? Let's review during our next working meeting - thanks!

**Comment by bermudezmt** [comment]
@paigehargrave  I don't think so since this code change has been merged into master after the [v0.16.1](https://github.com/docker/machine/releases/tag/v0.16.1) release.

**Pull request closed without merging**
