### PR TITLE
Add Ubuntu 16.10 Yakkety Yak

### PR DESCRIPTION
**Pull request by thaJeztah**
### Describe the proposed changes

Support for Ubuntu 16.10 was added in
https://github.com/docker/docker/pull/27993
(https://github.com/docker/docker/pull/27993/commits/27beb64d468614db0eb7344340d39b5619219a7d)

### Unreleased project version

This is for Docker 1.13

### Related issue or PR in another project

https://github.com/docker/docker/pull/27993

### Please take a look

@mlaventure @mstanleyjones

### CODE REVIEW

**Comment by mstanleyjones** [comment]
@thaJeztah LGTM but there is a merge conflict. Can you take care of it?

**Comment by thaJeztah** [comment]
oh! yes, I saw that one coming, I'll update

**Comment by thaJeztah** [comment]
@mstanleyjones fixed!

**Comment by tkothe** [comment]
interestingly my Ubuntu can not find the package

```
ubuntu@ubuntu:~$ cat /etc/apt/sources.list.d/docker.list
deb https://apt.dockerproject.org/repo ubuntu-yakkety main
ubuntu@ubuntu:~$ sudo apt-get update
Hit:1 http://de.archive.ubuntu.com/ubuntu yakkety InRelease
Hit:2 http://de.archive.ubuntu.com/ubuntu yakkety-updates InRelease
Hit:3 http://de.archive.ubuntu.com/ubuntu yakkety-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu yakkety-security InRelease
Hit:5 https://apt.dockerproject.org/repo ubuntu-yakkety InRelease
Reading package lists... Done
ubuntu@ubuntu:~$ apt-cache policy docker-engine
N: Unable to locate package docker-engine
```

is it me or is something wrong with the repo?


I also can not find the instructions I found here on the website yet... https://docs.docker.com/engine/installation/linux/ubuntulinux/

**Comment by thaJeztah** [comment]
@tkothe this is scheduled for the upcoming 1.13 release (also see the milestone attached to this PR)

**Comment by tkothe** [comment]
@thaJeztah got it. Thanks! Until then, does it make sense to try the xenial packages? Or should I just wait?
(Or jump back to Ubuntu 16.04 :) )

**Comment by thaJeztah** [comment]
Xenial packages _probably_ work (haven't tried)

> Or jump back to Ubuntu 16.04

Depends; keep in mind that 16.10 Yakkety Yak is not a LTS version, so it [will reach end of life in July 2017](https://lists.ubuntu.com/archives/ubuntu-announce/2016-October/000213.html). After that, no more updates (including security updates) are provided by Ubuntu. If this is a production machine and you don't want to have to go through updates in July, 16.04 is a good choice

**Pull request merged**
