### PR TITLE
build: multi-stage builds

### PR DESCRIPTION
**Pull request by crazy-max**
carry a commit from #14905 to move "multi stage build" page to `Build section > Building images`.

Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>

### CODE REVIEW

**Comment by jedevc** [comment]
Hm having a section called "guides" in the "manuals" feels confusing.

Since this relates to Dockerfiles, I wonder if we should have a `Dockerfile` section under `Docker Build`? This would be a good first page to put there, but I can easily imagine lots of other content ending up there, like our best practices.

**Comment by crazy-max** [comment]
> Since this relates to Dockerfiles, I wonder if we should have a `Dockerfile` section under `Docker Build`?

That SGTM but what about our guides in https://github.com/docker/buildx/tree/master/docs/guides? I recall you had some ideas for a folder under `Docker Build` section for them.

**Comment by jedevc** [comment]
> but what about our guides in https://github.com/docker/buildx/tree/master/docs/guides? I recall you had some ideas for a folder under Docker Build section for them

Good point :laughing: I think they probably belong in the Buildx section directly, or maybe in an Advanced section under that, if we really start to get too many. I'm not quite sure, I think some of those guides, probably need some love and care before we put them on the site, especially some of the older ones, just to bring them into line with the style of the ones we've already got there.

**Comment by crazy-max** [comment]
@jedevc Moved to "Building images" section and rebased. PTAL.

**Review by jedevc — APPROVED** [review]

**Review by usha-mandya — APPROVED** [review]
LGTM

**Pull request merged**
