### PR TITLE
Fix JSON example on webhooks page

### PR DESCRIPTION
**Pull request by johanbrandhorst**
### Proposed changes
Correct the JSON example on the Webhooks page. The comment_count parameter in the JSON body is a number, not a string.

### CODE REVIEW

**Comment by joaofnfernandes** [comment]
@lilybguo can you confirm?

**Comment by lilybguo** [comment]
@joaofnfernandes I found this bug during one of the testing sessions where we used testkit clusters. I don't know how to load unmerged code onto a cluster and verify. can someone else verify it?

**Comment by manishtomar** [comment]
@lilybguo I believe this about hub webhook documentation. Did you misunderstand to be something else?

**Comment by lilybguo** [comment]
@manishtomar Ha I'm sorry, I was also looking at an orca bug, confused the two.

I don't have any context on this bug. The fix looks good, but I don't think I'm the right person to confirm

**Comment by joaofnfernandes** [comment]
Thanks @manishtomar. Let's ship it!

**Pull request merged**
