### PR TITLE
Publish updates from master

### PR DESCRIPTION
**Pull request by usha-mandya**
Publish the latest changes from master

### CODE REVIEW

**Review by StefanScherer — APPROVED** [review]
LGTM

**Comment by StefanScherer** [comment]
Small nit: ReplaceKeyPrefixWith is now used with both `null` and `""`, but the outcome is the same. So, it's fine.

**Comment by thaJeztah** [comment]
> Small nit: ReplaceKeyPrefixWith is now used with both null and "", but the outcome is the same. So, it's fine.

Thanks! I wasn't sure if it would treat `null` as "don't do anything" and `""` as "replace", so I verged on the "safe side"; we can update in a follow up (perhaps even _remove_ the fields that are empty?)

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
