### PR TITLE
Publish updates from master

### PR DESCRIPTION
**Pull request by thaJeztah**
Looks like for some reason, the last publish omitted the "registry" spec. I tried reproducing the problem locally, but was not able to, so it may have been a temporary glitch or issue with GitHub's svn service

Let's try another publish to see if it resolves the problem

fixes / relates to https://github.com/docker/docker.github.io/issues/11816
fixes / relates to https://github.com/docker/docker.github.io/issues/11822
fixes / relates to https://github.com/docker/docker.github.io/issues/11823
fixes / relates to https://github.com/docker/docker.github.io/issues/11824
fixes / relates to https://github.com/docker/docker.github.io/issues/11828
fixes / relates to https://github.com/docker/docker.github.io/issues/11829
fixes / relates to https://github.com/docker/docker.github.io/issues/11830
fixes / relates to https://github.com/docker/docker.github.io/issues/11831
fixes / relates to https://github.com/docker/docker.github.io/issues/11832
fixes / relates to https://github.com/docker/docker.github.io/issues/11833
fixes / relates to https://github.com/docker/docker.github.io/issues/11834
fixes / relates to https://github.com/docker/docker.github.io/issues/11835

### CODE REVIEW

**Comment by thaJeztah** [comment]
@usha-mandya @StefanScherer PTAL

**Comment by thaJeztah** [comment]
Staging looks ok, but not sure if that was built from this PR?

- https://docs-stage.docker.com/registry/spec/api/
- https://docs-stage.docker.com/registry/spec/manifest-v2-1/
- https://docs-stage.docker.com/registry/spec/manifest-v2-2/
- https://docs-stage.docker.com/registry/spec/deprecated-schema-v1/

**Comment by StefanScherer** [comment]
@thaJeztah docs-stage gets updated when we merge PR's to master. This PR can only be viewed on netlify

**Review by StefanScherer — APPROVED** [review]
LGTM

**Pull request merged**
