### PR TITLE
Added Template Archive pages for Docker for AWS and Azure

### PR DESCRIPTION
**Pull request by kencochrane**
### Proposed changes

I added a template archive page for Docker for AWS and Azure, so that people can find the templates for previous releases. I also fixed an issue on the release notes page, where the buttons were in the wrong place.

/cc @FrenchBen 

Signed-off-by: Ken Cochrane <KenCochrane@gmail.com>

### CODE REVIEW

**Comment by johndmulhausen** [comment]
Looks great to me. Couple of easy nits:

1. Let's not do the `<br/>` thing please and thanks :)
2. Add a blank space between `## Headings` and content

**Comment by kencochrane** [comment]
@johndmulhausen we need the `<br />`'s or else the formatting on the page is broken. 

### See current prod. Notice the button messing up the New list items.
screenshot 2017-04-03 20 41 12

### With my fixes.
screenshot 2017-04-03 20 40 50

If you know of a better way to fix this, I'm all for it.

**Comment by FrenchBen** [comment]
@kencochrane this is a CSS issue that I fixed here:
https://github.com/docker/docker.github.io/pull/2183

Doesn't look like the fix was ever deployed - @johndmulhausen when is the next docs publish?

**Comment by kencochrane** [comment]
I removed the Br tags since Ben's PR will fix this issue ones that is deployed.

**Comment by mstanleyjones** [comment]
Sorry for the delay on this. Please resolve the conflicts and let's see how this looks.

**Comment by kencochrane** [comment]
@mstanleyjones resolved conflicts

**Pull request merged**
