### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by sampablokuper**
### Proposed changes

Commit a20ff823038673ee45edca576e95ba386050fbac fixed 5 out of the 6 links in `nav.html` . This commit fixes the remaining link.

### Related issues (optional)

Related: #5742

### CODE REVIEW

**Comment by johndmulhausen** [comment]
Hm, this one slipped by me. Would prefer we use "pretty" URLs. i.e. just `/get-started/` rather than `/get-started/index.html` -- can you update?

**Comment by sampablokuper** [comment]
@johndmulhausen slipped by me too ;-) (although I haven't made a build environment for this repo, so couldn't really test it properly). Anyhow, updated.

**Comment by mistyhacks** [comment]
Sorry, looks like you have a conflict. Please rebase to resolve it.

**Comment by sampablokuper** [comment]
Thanks for your notification above. Sorry I didn't get around to addressing the merge conflict. And thank you for merging, too: that nav is now working as desired on the live site :)

**Pull request merged**
