### PR TITLE
Improve section about AWS policy

### PR DESCRIPTION
**Pull request by ddc67cd**
Added missing parts of the policy, note about mybucket.

### CODE REVIEW

**Comment by johndmulhausen** [comment]
Deploy preview ready!

Built with commit 44bb613fa4057f9a83ed82a81d52e9ee24bfb5f7

https://deploy-preview-816--docker-docs.netlify.com

**Comment by joaofnfernandes** [comment]
Thanks for contributing!
I agree that it's not obvious that you should edit `mybucket` and change it to your particular S3 bucket name. Can you change to to use `<s3-bucket-name>` instead, to make this a bit more obvious?

E.g.

```
"Resource": "arn:aws:s3:::<s3-bucket-name>/*"
```

**Comment by joaofnfernandes** [comment]
@aaronlehmann do you mind reviewing this change?

**Comment by ddc67cd** [comment]
You're right, this is even better. Renamed to S3_BUCKET_NAME.

**Comment by aaronlehmann** [comment]
Looks good.

**Comment by joaofnfernandes** [comment]
Then let's ship it 🚀

**Pull request merged**
