### PR TITLE
Fix ipv6 netmask

### LINKED ISSUE #825: Incorrect netmask for ipv6
File: [engine/userguide/networking/default_network/ipv6.md](https://docs.docker.com/engine/userguide/networking/default_network/ipv6/)
This line is below one of the earlier examples:
"In this setup the subnet 2001:db8:23:42::/80 with a range from 2001:db8:23:42:0:0:0:0 to 2001:db8:23:42:0:ffff:ffff:ffff is attached to eth0, with the host listening at ..."

Shouldn't it be a ::/64 network that was attached to the eth0? As per the Figure?

### LINKED ISSUE #933: Mistake in netmask for ipv6
File: [engine/userguide/networking/default_network/ipv6.md](https://docs.docker.com/engine/userguide/networking/default_network/ipv6/)

I think this line is incorrect: So if you have a /64 for your whole environment use /78 subnets for the hosts and /80 for the containers. This way you can use 4096 hosts with 16 /80 subnets each.

2^12 = 4096
2^4 = 16

I think it should be a /76 subnet: 12 bits = 4096 hosts and 4 bits = 16 /80 subnets

### PR DESCRIPTION
**Pull request by shubheksha**
### Related issues (optional)
Fixes #933 

cc/ @drnybble, @aboch, @JimGalasyn

### CODE REVIEW

**Comment by aboch** [comment]
Looks good to me

**Comment by mstanleyjones** [comment]
LGTM! Did you update the image as well? That's not included in this PR yet.

**Comment by shubheksha** [comment]
The image is for the other netmask issue. #825
This is a fix for an already merged PR which had wrong info.

**Comment by johndmulhausen** [comment]
Thanks for the fix, @shubheksha !

**Pull request merged**
