### PR TITLE
Edit to remove reference to missing image

### PR DESCRIPTION
**Pull request by dockertopia**
Removed a line that references a missing image.

### Related issues
Fixes #14965

### CODE REVIEW

**Comment by thaJeztah** [comment]
I'm a bit confused; because the part that's removed was not an image? The other PR updated the link to point to https://docs.docker.com/network/, which is the (in-depth) section about Docker Networking, which could be a good resource of information for how docker networks work

**Comment by dockertopia** [comment]
> oh! looks like the last link in this document also is broken (linking to the same content);
> 
> Screenshot 2022-07-06 at 13 32 50

Yeah, what replaces this resource "https://success.docker.com/Architecture/Docker_Reference_Architecture%3A_Designing_Scalable%2C_Portable_Docker_Container_Networks ?"
I can add a cross-reference to this page in this branch https://docs.docker.com/engine/swarm/networking/. Let me know.

**Comment by dockertopia** [comment]
@thaJeztah PTAL, tks.

**Review by usha-mandya — APPROVED** [review]
LGTM. Thank you

**Pull request merged**
