### PR TITLE
Add changes for 18.09 version

### PR DESCRIPTION
**Pull request by RomainBelorgey**
The configuration of telemetry changes since 18.09 ee version.

For full information, internal escalation: https://docker.atlassian.net/browse/FIELD-1702

### CODE REVIEW

**Comment by ollypom** [comment]
Hey @RomainBelorgey thanks for the PR. I've just reorded the text a little bit. Is my commit ok? 

@DawnWood-Docker Also PTAL :)

**Comment by RomainBelorgey** [comment]
@ollypom Thanks ok for me

**Comment by DawnWood-Docker** [comment]
Hi @ollypom the changes look fine to me but there is a build error. I am hesitant to check this in until that is resolved. Thoughts?

**Comment by DawnWood-Docker** [comment]
according to Ally, this is an error we can ignore.

**Pull request merged**
