### PR TITLE
Moved 2 Known issues to last version before fix

### PR DESCRIPTION
**Pull request by darwin-traver**
### Proposed changes

Multiple edits for Known issues list for UCP:

This was fixed in UCP 3.0.10 & 3.1.4, so last versions to display this Known Issue should be UCP 3.0.9 and 3.1.3:
 * By default, Kubelet begins deleting images, starting with the oldest unused images, after exceeding 85% disk space utilization. This causes an issue in an air-gapped environment. (docker/orca#16082)

And this Known Issue was fixed in UCP 3.1.3, so the last versions to display this issue should be UCP 3.1.2
* In the UCP web interface, LDAP settings disappear after submitting them. However, the settings are properly saved. (docker/orca#15503)

### CODE REVIEW

**Comment by bermudezmt** [comment]
@darwin-traver - I added these updates to https://github.com/docker/docs-private/pull/1023. PTAL - thank you!

**Comment by darwin-traver** [comment]
LGTM, thanks!

**Comment by paigehargrave** [comment]
@darwin-traver Thank you! I'll leave this open until you confirm.

**Comment by bermudezmt** [comment]
Thanks for doing that, @darwin-traver . The changes in this PR look to be reflected on the `master` branch now, so going to close this one.

**Pull request closed without merging**
