### PR TITLE
docker-hub: remove duplicated api latest page

### PR DESCRIPTION
**Pull request by crazy-max**
follow-up https://github.com/docker/docker.github.io/pull/14685#issuecomment-1120810195

Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
Interesting; Netlify build failed? Not sure i've seen that before 😅

**Comment by thaJeztah** [comment]
oh; it's running again 🤞

**Comment by crazy-max** [comment]
> Interesting; Netlify build failed? Not sure i've seen that before 😅

Yes looks like a dir has not been cleaned up correctly i ntheir pipeline:

```
11:17:10 PM: mv: target '/opt/build/cache/node_version/' is not a directory
11:17:10 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
11:17:10 PM: Creating deploy upload records
11:17:11 PM: Failing build: Failed to build site
11:17:11 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
11:17:11 PM: Finished processing build request in 1m0.681372451s
```

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
