### PR TITLE
Changing RHEL version requirements

### PR DESCRIPTION
**Pull request by david-yu**
Removing RHEL 7.2 to 7.x requirements by linking to Compatibility Matrix

### CODE REVIEW

**Comment by justinclift** [comment]
Looking at that [Compatibility Matrix](https://success.docker.com/article/compatibility-matrix), the `s390x` entries only seem to list RHEL 7.4, not 7.3.  Am I misreading? :smile:

**Comment by ahh-docker** [comment]
Approving with @bermudezmt

**Comment by justinclift** [comment]
So, it's been approved even though it's **wrong**, the incorrect info was pointed out ages ago, and - checking again - it's **still wrong**?

**Comment by ahh-docker** [comment]
Relates to https://github.com/docker/docker.github.io/pull/6452 as well.

**Comment by bermudezmt** [comment]
@justinclift sorry we missed your previous comment. We're looking into correcting this at the moment.

**Comment by ahh-docker** [comment]
@david-yu Can you please address @justinclift's comment? https://github.com/docker/docker.github.io/pull/7201#issuecomment-411930390 CC: @bermudezmt

**Comment by david-yu** [comment]
Opened another PR to address those issues that conflict to the compat matrix: https://github.com/docker/docker.github.io/pull/7933

**Pull request merged**
