### PR TITLE
Update product version references

### PR DESCRIPTION
**Pull request by sgerrand**
### Proposed changes

Update the version strings for the latest GA releases of Docker Engine, Compose, and Machine.

### CODE REVIEW

**Comment by mistyhacks** [comment]
@gbarr01 consider using the site-scoped variables for these so they are always up to date.

**Comment by sgerrand** [comment]
Sure, that makes sense. Will do.

**Comment by gbarr01** [comment]
Hm, I wonder if it makes more sense to remove that stuff. The user can check for the latest versions in the [release notes](https://docs.docker.com/docker-for-mac/release-notes/).

**Comment by sgerrand** [comment]
Thanks @gbarr01. 🙇

**Comment by gbarr01** [comment]
No problem, @sgerrand ... seems useful to keep around. Let's see what happens when I merge. :)

**Pull request merged**
