### PR TITLE
Add ARM64 to platform matrix

### PR DESCRIPTION
**Pull request by seemethere**
Signed-off-by: Eli Uriegas <eli.uriegas@docker.com>

### Proposed changes

Add ARM64 to platform matrix, since we support it now.
### Unreleased project version (optional)
`17.12.0-ce`

### CODE REVIEW

**Comment by mistyhacks** [comment]
Or we could merge it into `vnext-engine`.... ;)

**Comment by mistyhacks** [comment]
@seemethere can you please deal with the conflict? 👼

**Comment by seemethere** [comment]
@mistyhacks fixed

**Comment by mistyhacks** [comment]
Netlify error seems to be their fault, but retrying it just in case.

**Comment by mistyhacks** [comment]
Your rebase didn't work because you were still getting 6 unrelated commits. I fixed it now.

**Pull request merged**
