### PR TITLE
Relnotes 02 2019 updates

### PR DESCRIPTION
**Pull request by paigehargrave**
Added updates to DTR, UCP, and Engine release notes.

Also attempted to carry known issues forward (for each major release) to address feedback indicating that not carrying this information forward is confusing, and might convey that previous known issues were fixed.

### CODE REVIEW

**Comment by david-yu** [comment]
@paigehargrave It looks like you might have the wrong folks assigned as approvers here, I would recommend adding @jose-bigio and @caervs

**Comment by paigehargrave** [comment]
@david-yu Thank you! I'm still trying to keep 'who's who' straight. :)

**Comment by ry4nz** [comment]
@paigehargrave There are lots of `known issues` added to UCP release notes.  Is it intentional ?

**Comment by paigehargrave** [comment]
@ry4nz Hi Ryan - Sorry for the extra hassle here. We got feedback that the whole Known Issues info is confusing. Known issues get mentioned in one release and then they 'disappear', which leads people to believe that they got fixed, which is usually not the case. So what I did was try to consolidate the known issues for each release. Where I had issue numbers, I tried to remove the ones that got fixed. However, in the majority of cases, there is no issue number to check, SO if you can scan the known issues to see what still applies, that would be great.

**Pull request closed without merging**
