### PR TITLE
Add overlay2 support for Docker EE 17.06.2-ee-5 on RHEL

### PR DESCRIPTION
**Pull request by xinfengliu**
Since https://success.docker.com/Policies/Compatibility_Matrix has added statement:
`Beginning with Docker EE daemon version 17.06.2-ee-5 the overlay2 storage driver is supported, and is the recommended storage driver.`
Propose to add it to docker ee installation guide as well to make the information consistent.

### CODE REVIEW

**Comment by mistyhacks** [comment]
Please make this change for EE CentOS and Oracle files as well. Thanks!

**Comment by xinfengliu** [comment]
Hi @mistyhacks , I'm sorry https://success.docker.com/Policies/Compatibility_Matrix currently only says overlay2-support applies to RHEL, not other OSes. So I'm wondering if it is appropriate to propagate the change to CentOS, Oracle Linux now. 
In addition, https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/#configure-docker-with-the-overlay-or-overlay2-storage-driver mentions: 
>To use overlay2 on CentOS (Docker CE only)...
So, more doc files need check before we make changes.

**Comment by mistyhacks** [comment]
Now I'm confused. @friism PTAL

**Comment by friism** [comment]
I think it's confusing too - @dmp42 would like to keep it ambiguous.

**Comment by dmp42** [comment]
Ok people.
overlay2 support is dependent on a number of factors.

Since @friism is our overlay2 lover/expert/champion and really wanted this documented, he will come up with a clear matrix on where we support it (architecture, version, OS, kernel), validated by QA (for each supported environment, they will confirm that they are indeed testing it).

When he is done, we will have clarity and will be able to document appropriately.

@friism let me know if you have questions about this, or need help.

**Comment by joaofnfernandes** [comment]
@xinfengliu  Given the feedback above and that there's conflicts in this PR, I'll push a change to this branch that resolves the conflicts but maintains your change for consistency with the compatibility matrix.

**Comment by joaofnfernandes** [comment]
Let's ship it 🚀🚀🚀 @xinfengliu thanks for helping us keep the docs up to date!

**Pull request merged**
