### PR TITLE
26861 clarify insecure cn example

### PR DESCRIPTION
**Pull request by nwright-nz**
### Describe the proposed changes

Changed the CN example in the section 'Test an Insecure Registry' to provide clarity around the CN prompt. Docs in the past instructed people to use a specific CN (which potentially already exists) rather than a CN of their choice.

### Related issue or PR in another project

https://github.com/docker/docker/issues/26861

### CODE REVIEW

**Comment by johndmulhausen** [comment]
Deploy preview ready!

Built with commit 901aadb0741835c2677df5c5c1e514e87180989d

https://deploy-preview-665--docker-docs.netlify.com

**Comment by johndmulhausen** [comment]
@nwright-nz Can you back out your changes to the Dockerfile? Pretty sure they don't need to be here. :) It's also causing a merge conflict.

**Comment by joaofnfernandes** [comment]
@nwright-nz it looks like you changed the `Dockerfile` file by accident. Can you remove that change from this PR?

**Comment by nwright-nz** [comment]
Oof - sorry everyone. Still learning. will get this sorted ASAP

**Comment by joaofnfernandes** [comment]
It seems that you've closed this PR :( Are you opening a new one, or do you need any help?

**Pull request closed without merging**
